- LICENSE.txt
This PR applies the same the MIT license as RuboCop Core.
The contents of the license file are the same as RuboCop Core.
https://github.com/rubocop-hq/rubocop/blob/v0.57.1/LICENSE.txt
> Add the MIT license file

- lib/rubocop-rails.rb
- lib/rubocop/rails/version.rb
- rubocop-rails.gemspec
This PR adds gemspec for initial version.
The initial version was set to 0.5.0.
That's because rubocop-rails 0.9 or lower was used up to 0.4.1.
https://rubygems.org/gems/rubocop-rails/versions
> Create gemspec for initial version

- config/default.yml
- config/disabled.yml
- config/enabled.yml
This PR imports settings of default.yml, disabled.yml and enabled.yml related to Rails department from RuboCop Core.
The following is an important point.
This PR does not import the following setting from RuboCop Core.
```yaml
Rails:
Enabled: false
```
https://github.com/rubocop-hq/rubocop/blob/v0.58.1/config/disabled.yml#L45-L48
Because disabling the Rails department by default is hard to use as an extracted RuboCop Rails gem.
If users specify `rubocop-rails` in Gemfile, I think that they expect the behavior equivalent to now `rubocop -R` / `rubocop --rails` option.
In the future, I think that these `rubocop -R` / `rubocop --rails` options will be removed from `rubocop` command.
> Import Rails cop configs from RuboCop Core

- spec/rubocop/cop/rails/bulk_change_table_spec.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
The `let`s :rails_version and :cop_config should only be overwritten within a `context`. Overwriting them in global scope makes Ruby emit a warning.
These warnings are now no longer present in output on CI:
```
/home/ubuntu/rubocop-rails/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/memoized_helpers.rb:291: warning: method redefined; discarding old rails_version
/home/ubuntu/rubocop-rails/vendor/bundle/ruby/2.2.0/gems/rubocop-0.59.2/lib/rubocop/rspec/cop_helper.rb:11: warning: previous definition of rails_version was here
/home/ubuntu/rubocop-rails/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/memoized_helpers.rb:298: warning: method redefined; discarding old rails_version
/home/ubuntu/rubocop-rails/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/co …
```
> Remove spec warnings

- .travis.yml
RubyGems 3.0.0 requires Ruby 2.3.0 or higher.
https://github.com/rubygems/rubygems/blob/v3.0.0/rubygems-update.gemspec#L32
This PR fixes the following build error.
```console
$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.0.gem (100%)
ERROR:  Error installing rubygems-update:
rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .
```
https://travis-ci.org/rubocop-hq/rubocop-rails/jobs/471037127#L480-L487
> Fix a build error for Ruby 2.2 matrix on Travis CI

- .circleci/config.yml
It is supposed to do the same as the Travis CI configuration file, except:
- Not testing on jruby-head, since there is not (yet) such an image available.
- Tests on ruby-head is not an “allowed failure” – it doesn't exist on CircleCI.
Comparing the build times (https://travis-ci.org/rubocop-hq/rubocop-rails/builds/471091505 and https://circleci.com/workflow-run/3cd0a5c8-3edd-464e-8c87-d6872d12f1bf) is not completely fair, since the slow jruby-build is not run on CircleCI. But even compensating for that difference, CircleCI is significantly faster than Travis.
> Add CircleCI configuration file

- .circleci/config.yml
Ruby 2.6.0 has been released and this Ruby version is available on CircleCI.
- https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/
- https://hub.docker.com/r/circleci/ruby/tags/
> CI against Ruby 2.6.0

- lib/rubocop-rails.rb
- lib/rubocop/cop/rails/http_status.rb
- rubocop-rails.gemspec
- spec/rubocop/cop/rails/http_status_spec.rb
I'm not sure the status of this repository. So if this pull request is not mergeable now, I think we keep open this pull request.
`Rails/HttpStatus` cop uses rack gem as an additional dependency to display more descriptive offense messages. The runtime dependencies do not include rack because RuboCop needs the gem only for the cop.
I think we can add rack to runtime dependencies after separating `rubocop-rails` gem.
`rubocop` is used without rack sometimes, but `rubocop-rails` gem will be used with rails gem in most cases, so the environment includes rack already.
If we add rack, installed gems does not increase.
> Add `rack` to runtime dependency

- config/default.yml
- manual/cops_rails.md
- tasks/cops_documentation.rake
`Rails/HelperInstanceVariable` cop added by rubocop-hq/rubocop-rails#29 isn't backported to RuboCop core.
2.0 has been proposed as the release version of RuboCop Rails, it did so.
https://github.com/toshimaru/rubocop-rails/issues/31#issuecomment-449617550
Cops importing from the RuboCop core has lower than 1.0 so I think it works.
And this PR updates `rake yard_for_generate_documentation` task to add metadata and adds document regenerated by `rake yard_for_generate_documentation`.
> Add metadata to default.yml

- Gemfile
This PR uses edge RuboCop core for development.
It is for RuboCop Performance to early catch change of RuboCop Core
which is the runtime dependency gem.
Related PR ... https://github.com/rubocop-hq/rubocop-performance/pull/44
> Use edge RuboCop core for development

- lib/rubocop/rails/inject.rb
Follow up https://github.com/rubocop-hq/rubocop/pull/7048.
This PR fixes the following warning.
```console
% cd path/to/rubocop-performance
% bundle exec rake generate_cops_documentation
Files:          54
Modules:         4 (    2 undocumented)
Classes:        55 (    0 undocumented)
Constants:     122 (  122 undocumented)
Attributes:      1 (    0 undocumented)
Methods:       117 (  100 undocumented)
25.08% documented
Warning: AllCops does not support TargetRailsVersion parameter.
Supported parameters are:
- RubyInterpreters
- Include
- Exclude
- DefaultFormatter
- DisplayCopNames
- DisplayStyleGuide
- StyleGuideBaseURL
- ExtraDetails
- StyleGuideCopsOnly
- EnabledByDefault
- DisabledByDefault
- UseCache
- MaxFilesInCache
- CacheRootDirectory
- AllowSymlinksInCacheRootDirectory
- …
```
> Specify `unset_nil: false` to `ConfigLoader.merge_with_default`

- README.md
- manual/index.md
- manual/installation.md
- manual/usage.md
This PR adds some documents with reference to RuboCop Performance.
https://github.com/rubocop-hq/rubocop-performance/pull/29
> Add some documents

- README.md
Follow up https://github.com/rubocop-hq/rubocop-rails/issues/55#issuecomment-494617358.
This PR updates `rubocop` command option in README.md.
`rubocop --rails` command option is required while `rubocop` command supports `--rails` option.
> Update `rubocop` command option in README.md

- rubocop-rails.gemspec
This PR updates metadata for gemspec.
The following URL is published and specified in gemspec.
https://rubocop-rails.readthedocs.io/
> Update metadata for gemspec

- README.md
This PR adds a reference to `rubocop-rails_config` gem in README.md
Fixes #56.
Follow up https://github.com/rubocop-hq/rubocop-rails/pull/57#issuecomment-494311746.
Follow up https://github.com/rubocop-hq/rubocop/issues/5976#issuecomment-495244393.
> [Fix #56] Add a reference to `rubocop-rails_config` gem in README.md

- spec/rubocop/config_spec.rb
- spec/spec_helper.rb
- spec/support/file_helper.rb
- spec/support/shared_contexts.rb
This PR imports `target_rails_version` spec from RuboCop core.
The following warning will be resolved with rubocop-hq/rubocop#7095.
```console
(snip)
WARNING: Shared example group 'with Rails 3' has been previously defined
at:
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/rspec/shared_contexts.rb:85
...and you are now defining it at:
/Users/koic/src/github.com/rubocop-hq/rubocop-rails/spec/support/shared_contexts.rb:3
The new definition will overwrite the original one.
WARNING: Shared example group 'with Rails 4' has been previously defined
at:
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/rspec/shared_contexts.rb:89
...and you are now defining it at:
/Users/koic/src/github.com/rubocop-hq/rubocop-rails/spec/support/shared_contexts.rb:7
The new …
```
> Import `target_rails_version` spec from RuboCop core

- README.md
Follow up https://github.com/rubocop-hq/rubocop/issues/7104 and https://github.com/rubocop-hq/rubocop-jp/issues/53 (JA) .
This PR adds a way to specify multiple extensions to README.md.
> Add a way to specify multiple extensions to README.md

- rubocop-rails.gemspec
This is related to #37. `rack` was recently made a runtime dependency: #36:
```ruby
s.add_runtime_dependency 'rack', '>= 2.0'
```
Now this conflicts with an older Rails 4 app of ours which requires an older rack version:
```
actionpack (4.2.11.1)
rack (~> 1.6)
```
The only rack interface that is used seems to be `::Rack::Utils::SYMBOL_TO_STATUS_CODE` which first appeared in rack 1.1: https://github.com/rack/rack/commit/5c4bd17d791d97310667acf6b458456aa1f8af0d
Is there a particular reason why you enforce rack >= 2.0 or could we relax that dependency?
> Relax rack dependency for Rails 4

- CHANGELOG.md
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
The `change_column_null` method does not have corresponding method to 
use in the suggested `change_table` version.
We should remove it from the offended methods list.
> [Fix #43] Remove `change_column_null` from `BulkChangeTable`

- CHANGELOG.md
- README.md
- lib/rubocop/cop/rails/action_filter.rb
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/action_filter_spec.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
- spec/support/shared_contexts.rb
This PR drops Rails 3 support.
RuboCop core was supported Rails 4+.
https://github.com/rubocop-hq/rubocop/tree/v0.71.0#compatibility
> The Rails cops support the following versions:
>
> - Rails 4.0+
It conforms to the expected behavior of RuboCop core originally.
And Rails is maintained at 4.2.Z or higher.
> 4 Severe Security Issues
> For severe security issues all releases in the current major series, and
> also the last major release series will receive patches and new
> versions. The classification of the security issue is judged by the core
> team.
>
> Currently included series: 5.2.Z, 5.1.Z, 5.0.Z, 4.2.Z.
https://guides.rubyonrails.org/maintenance_policy.html
The following is the RuboCop Rails and Rails 4 use case.
https://github.com/rubocop-hq/rubocop-rails/pull/68 …
> RuboCop Rails supports Rails 4 or higher

- .rubocop.yml
- Rakefile
This PR fixes the following build error when using rubocophq/circleci-ruby-snapshot:latest image.
```console
$ docker run --rm -it rubocophq/circleci-ruby-snapshot:latest
$ cd
$ git clone https://github.com/rubocop-hq/rubocop-rails
$ cd rubocop-rails
$ bundle install
$ bundle exec rake
bundle exec rubocop
Traceback (most recent call last):
1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file --
/usr/local/lib/bin/bundle (LoadError)
rake aborted!
Command failed with status (1): [bundle exec rubocop...]
/home/circleci/rubocop-rails/Rakefile:30:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => default => …
```
> Fix a build error

- lib/rubocop/cop/rails/action_filter.rb
- manual/cops_rails.md
Follow up #74.
RuboCop Rails doesn't support Rails 3 or lower.
> Remove outdated doc for `Rails/ActionFilter`

- CHANGELOG.md
- lib/rubocop/cop/rails_cops.rb
Avoids the following error in conjunction with rubocop v0.72:
`RuboCop::Cop::Rails not defined (NameError)`
Fixes #79 
Before, it attempted to remove the constant whether `Rubocop::Cop::Rails` was defined or if `::Rails` was defined. Turning off the `inherit` flag while checking `const_defined?` remedies this.
> [Fix #79] Rubocop::Cop::Rails constant removal

- lib/rubocop/cop/rails_cops.rb
Follow up https://github.com/rubocop-hq/rubocop-rails/pull/80.
(Thank you for this PR that solved issue #79 early.)
Rails cops has been removed from RuboCop 0.72.
https://github.com/rubocop-hq/rubocop/releases/tag/v0.72.0
As a result of verification, the code to guard a warning is not necessary already.
> Remove unnecessary code to suppress warnings

- CHANGELOG.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
Fixes #67.
Closes #71.
This PR fixes an incorrect auto-correct for `Rails/TimeZone` when using `DateTime`.
```diff
- DateTime.new
+ DateTime.zone.new
```
```ruby
DateTime.zone.new # NoMethodError: undefined method `zone' for
DateTime:Class
```
This PR changes to ignore `DateTime` with the following as background.
`DateTime` is not mentioned in The Rails Style Guide and `Rails/TimeZone` cop's examples.
- https://rails.rubystyle.guide/#time-now
- https://docs.rubocop.org/projects/rails/en/stable/cops_rails/#railstimezone
Recently, #81 and #82 have been feedback.
I think breaking by auto-correction should be fixed with the highest priority in this case.
Also, `DateTime` and `Time` are not replaced from `DateTime` to `Time` by auto-correct because they are different objects. …
> [Fix #67] Fix an incorrect auto-correct for `Rails/TimeZone`

- CHANGELOG.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
Fixes #86.
This PR fixes an incorrect auto-correct for `Rails/TimeZone` when using `Time.new`.
```diff
- Time.new
+ Time.zone.new  #=> NoMethodError: undefined method `new'
- Time.new(2019, 7, 7, 10, 15, 25)
+ Time.zone.new(2019, 7, 7, 10, 15, 25) #=> NoMethodError: undefined method `new'
```
```diff
- Time.new
+ Time.zone.now
- Time.new(2019, 7, 7, 10, 15, 25)
+ Time.zone.local(2019, 7, 7, 10, 15, 25)
```
> [#86] Fix an incorrect auto-correct for `Rails/TimeZone`

- config/default.yml
- lib/rubocop/cop/rails/dynamic_find_by.rb
- lib/rubocop/cop/rails/time_zone.rb
- manual/cops_rails.md
Follow up https://github.com/rubocop-hq/rubocop/issues/7120.
This PR updates the Rails Style Guide URL.
> Update The Rails Style Guide URL

- lib/rubocop/cop/rails/enum_hash.rb
- spec/rubocop/cop/rails/enum_hash_spec.rb
Rails/EnumHash cop has been introduced in #94. Thanks!
But the cop has two false negatives. This pull request will fix them.
This cop does not detect `enum` call with non-symbol key. For example:
```ruby
KEY = :status
enum KEY => %i[active archived]
```
`enum` allows defining multiple enums in one `enum` method call.
```ruby
enum status: %i[active archived],
role: %i[owner member]
```
But the cop is not aware of the code.
The cop has not been released yet, so I did not write any changelog for the pull request.
I wait merging #95 to review this pull request. Thanks.
> Fix false negatives for Rails/EnumHash cop

- lib/rubocop/cop/rails/enum_hash.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/enum_hash_spec.rb
Resolves #78.
Adds autocorrect feature for #78.
Depends on #94.
> [#78] Autocorrect EnumHash Cop

- CHANGELOG.md
- config/default.yml
- manual/cops_rails.md
We faced an issue where our custom `update_attributes` method call was changed to `update` but the method name remained same in the method definition.
```ruby
def update_attributes
end
update_attributes
```
```ruby
def update_attributes
end
update
```
So the cop is not safe for auto correct.
> Mark ActiveRecord/Aliases as unsafe autocorrect

- CHANGELOG.md
- config/default.yml
- manual/cops_rails.md
We faced an issue where our custom `update` method call was changed to `update!` but the method name remained same in the method definition.
```ruby
def update
end
update!
```
```ruby
def update
end
update
```
So the cop is not safe for auto correct.
> Mark Rails/SaveBang as unsafe autocorrect

- CHANGELOG.md
- lib/rubocop/cop/rails/enum_uniqueness.rb
- spec/rubocop/cop/rails/enum_uniqueness_spec.rb
Fixing `Rails/EnumUniqueness` cop per conversation in https://github.com/rubocop-hq/rubocop-rails/pull/96#issuecomment-515776639
> Fix false negatives for Rails/EnumUniqueness cop

- CHANGELOG.md
- config/default.yml
Resolves #104.
`bin/bundle` was generated by Bundler. And Bundler doesn't depend on Active Support (Rails).
This PR prevents the following error.
```console
% cd path/to/new-rails-app
% bin/rails -v
Rails 6.0.0.rc2
% bundle exec rubocop -a --only Rails/Present
% g diff
diff --git a/bin/bundle b/bin/bundle
index 4f5e057..fa7b83b 100755
--- a/bin/bundle
+++ b/bin/bundle
@@ -39,7 +39,7 @@ m = Module.new do
def gemfile
gemfile = ENV["BUNDLE_GEMFILE"]
-    return gemfile if gemfile && !gemfile.empty?
+    return gemfile if gemfile.present?
File.expand_path("../../Gemfile", __FILE__)
end
% ./bin/bundle
Traceback (most recent call last):
2: from ./bin/bundle:101:in `<main>'
1: from ./bin/bundle:71:in `load_bundler!'
./bin/bundle:42:in `gemfile': undefined method `present?' for
nil:NilClass …
```
> [Fix #104] Exclude Rails-independent `bin/bundle` by default

- CHANGELOG.md
- config/default.yml
Fixes #107.
This PR fixes style guide URLs when specifying `rubocop --display-style-guide` option.
The following is an execution using RuboCop Rails.
```console
% bundle exec rubocop --display-style-guide --only Style/StringLiterals
Inspecting 2 files
C.
Offenses:
Gemfile:3:8: C: Style/StringLiterals: Prefer single-quoted strings when
you don't need string interpolation or special
symbols. (https://rails.rubystyle.guide#consistent-string-literals)
source "https://rubygems.org"
^^^^^^^^^^^^^^^^^^^^^^
2 files inspected, 1 offense detected
```
The correct URL is `https://rubystyle.guide#consistent-string-literals` instead of `https://rails.rubystyle.guide#consistent-string-literals`.
and description in …
> [Fix #107] Fix style guide URLs

- CHANGELOG.md
- lib/rubocop/cop/rails/presence.rb
- spec/rubocop/cop/rails/presence_spec.rb
Fixes #111.
This PR fixes an incorrect autocorrect for `Rails/Presence` when method arguments of `else` branch is not enclosed in parentheses.
The following is a reproduction procedure.
```console
% cat example.rb
if value.present?
value
else
do_something value
end
```
```console
% bundle exec rubocop -a --only Rails/Presence
E
Offenses:
example.rb:1:1: C: [Corrected] Rails/Presence: Use value.presence ||
do_something value instead of if value.present?
value
else
do_something value
end.
if value.present? ...
^^^^^^^^^^^^^^^^^
example.rb:1:32: E: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter,
under AllCops)
value.presence || do_something value
^^^^^
1 file inspected, 2 offenses detected, 1 offense corrected …
```
> [Fix #111] Fix an incorrect autocorrect for `Rails/Presence`

- CHANGELOG.md
- lib/rubocop/cop/rails/validation.rb
- spec/rubocop/cop/rails/validation_spec.rb
Fixes #118.
This PR fixes an incorrect autocorrect for `Rails/Validation` when attributes are specified with symbol array literal.
The following auto-corrected causes `NoMethodError`.
```ruby
validates %i[full_name birth_date], presence: true
```
This PR will auto-correct it to the following code.
```ruby
validates :full_name, :birth_date, presence: true
```
> [Fix #118] Fix an incorrect autocorrect for `Rails/Validation`

- CHANGELOG.md
- lib/rubocop/cop/rails/presence.rb
- spec/rubocop/cop/rails/presence_spec.rb
Fixes #116 and adds regression tests for #115.
This PR fixes an incorrect autocorrect for `Rails/Presence` when `else` branch of ternary operator is not nil.
The following is a reproduction procedure.
```ruby
a.blank? ? 1 : a
```
```console
% bundle exec rubocop --only Rails/Presence -a
C
Offenses:
example.rb:1:1: C: [Corrected] Rails/Presence: Use a.presence instead of
a.blank? ? 1 : a.
a.blank? ? 1 : a
^^^^^^^^^^^^^^^^
1 file inspected, 1 offense detected, 1 offense corrected
```
```diff
-a.blank? ? 1 : a
+a.presence
```
This PR will auto-correct it to `a.presence || 1`.
> [Fix #116] Fix an incorrect autocorrect for `Rails/Prensence`

- spec/rubocop/cop/rails/bulk_change_table_spec.rb
- spec/rubocop/cop/rails/file_path_spec.rb
- spec/rubocop/cop/rails/helper_instance_variable_spec.rb
- spec/rubocop/cop/rails/output_safety_spec.rb
The `strip_indent` method was removed from RuboCop in https://github.com/rubocop-hq/rubocop/pull/7323.
Since rubocop-rails has never supported Ruby 2.2, we can safely replace all instances of `strip_indent` with squiggly heredocs.
> Replace use of strip_indent with squiggly heredoc

- rubocop-rails.gemspec
`$RS` is defined in English library, but the gemspec does not require it. So `$RS` is `nil`.
I found the problem with Ruby warning.
```bash
$ ruby -w rubocop-rails.gemspec
rubocop-rails.gemspec:19: warning: global variable `$RS' not initialized
```
> Add `require 'English'` to enable `$RS` global variable

- spec/rubocop/cop/rails/save_bang_spec.rb
Follow ruby/ruby#2437.
This PR fixes the following `FrozenError` for save_bang_spec.rb
```Failures:
% ruby -v
ruby 2.7.0dev (2019-10-09T16:08:42Z master 42edb05626) [x86_64-darwin17]
% bundle exec rspec ./spec/rubocop/cop/rails/save_bang_spec.rb
(snip)
1) RuboCop::Cop::Rails::SaveBang update behaves like
checks_common_offense when using update without arguments
Failure/Error: inspect_source(method.to_s)
FrozenError:
can't modify frozen String: "update"
Shared Example Group: "checks_common_offense" called from
./spec/rubocop/cop/rails/save_bang_spec.rb:541
in <top (required)>'
```
> Fix `FrozenError` for save_bang_spec.rb

- lib/rubocop/cop/rails/presence.rb
- spec/rubocop/cop/rails/presence_spec.rb
when trying autofix code like below:
`params[:foo].present? ? params[:foo] : params[:bar]`
the existing code will change it to:
`params[:foo].presence || params(:bar)`
essentially replaces the content of the `else` or `other` end of the ternary expression.
the culprit is this method `build_source_for_or_method` did not consider the parameter `other` (which is a `SendNode`) might be a `[]` method call.
this tiny patch fixes it.
That being said, I am not confident that this fixes all related problems.
> presence cop: fix [] for ternary expr other hand

- Gemfile
- relnotes/v2.0.0.md
- relnotes/v2.0.1.md
- relnotes/v2.1.0.md
- relnotes/v2.2.0.md
- relnotes/v2.2.1.md
- relnotes/v2.3.0.md
- relnotes/v2.3.1.md
- relnotes/v2.3.2.md
- tasks/cut_release.rake
This PR adds the following rake tasks.
```console
% rake -T | grep cut_release
rake cut_release:major                    # Cut a new major release,
create release notes and update documents
rake cut_release:minor                    # Cut a new minor release,
create release notes and update documents
rake cut_release:patch                    # Cut a new patch release,
create release notes and update documents
rake cut_release:pre                      # Cut a new pre release,
create release notes and update documents
```
And the release notes from v2.0.0 to v2.3.2 already released will be added.
> Add release task and release notes

- spec/rubocop/cop/rails/presence_spec.rb
This PR suppresses the following offense for rails/presence_spec.rb.
```console
(snip)
Offenses:
spec/rubocop/cop/rails/presence_spec.rb:70:66: W:
Lint/UnneededCopDisableDirective: Unnecessary disabling of
Metrics/LineLength.
it_behaves_like 'offense', <<~RUBY.chomp, <<~FIXED.chomp, 1, 7
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
126 files inspected, 1 offense detected
RuboCop failed!
```
https://circleci.com/gh/rubocop-hq/rubocop-rails/1721
> Suppress an offense for rails/presence_spec.rb

- CHANGELOG.md
- lib/rubocop/cop/rails/enum_hash.rb
- spec/rubocop/cop/rails/enum_hash_spec.rb
Closes #114.
This PR fixes an incorrect autocorrect for `Rails/EnumHash` when using nested constants.
> Fix an incorrect autocorrect for `Rails/EnumHash`

- CHANGELOG.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
The `change_table` method is reversible when using `change_default` with the :from and :to options.
However, RuboCop detects `Rails/ReversibleMigration` incorrectly, so it fixes.
> Fix a false positive for `Rails/ReversibleMigration`

- .rubocop.yml
Follow https://github.com/rubocop-hq/rubocop/pull/7468
The pull request renamed Layout/AlignHash to Layout/HashAlignment.
Our .rubocop.yml includes the cop, so the CI builds are failing.
example: https://circleci.com/gh/rubocop-hq/rubocop-rails/1776?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
This pull request will fix the problem.
> Follow renaming Layout/AlignHash to HashAlignment

- CHANGELOG.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
Fixes #144
I've made this commit based on `change_column_default` logic, so I'm not sure if the pattern is the best one.
I've also thought about grouping the checks from `change_column_default`, `change_table_comment` and `change_column_comment` into a more generic check that looks if a method has a hash with `:from`/`:to` keys, but I'm not sure if it's the best approach. Let me know which way is better :)
> [Fix #144] false positive for `Rails/ReversibleMigration`

- CHANGELOG.md
- lib/rubocop/cop/rails/unknown_env.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/unknown_env_spec.rb
`Rails/UnknownEnv` is not aware of `Rails.env == 'unknown_env'` style comparetion.
```ruby
if Rails.env == 'proudction'
end
```
This pull request adds the check to Rails/UnknownEnv cop.
Note
===
This pull request also change the offense message.
I removed `?` from the environment name in the message.
```diff
- Unknown environment `proudction?`. Did you mean `production?`?
+ Unknown environment `proudction`. Did you mean `production`?
```
Because `production?` is not an environment name.
> Make `Rails/UnknownEnv` cop aware of `Rails.env == 'unknown_env'`

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/rails/file_path.rb
- manual/cops_rails.md
This PR changes default of `EnforcedStyle` from `arguments` to `slashes` for `Rails/FilePath`.
The following is why `slashes` by default.
- `Rails.root` is an instance of `Pathname`, so the separator (`/`) works for example on the Windows platform.
- Since it can be expressed by a single string, the number of string instances can be reduced.
- Clarified because the argument is fixed to one.
`EnforcedStyle`'s default was `arguments` because it was mainly due to Windows platform considerations, but it seems to have been a mistake.
https://github.com/rubocop-hq/rubocop-rails/pull/128#issuecomment-530671304
> Change default of `EnforcedStyle` to `slashes` for `Rails/FilePath`

- CHANGELOG.md
- lib/rubocop/cop/rails/enum_hash.rb
- spec/rubocop/cop/rails/enum_hash_spec.rb
update code and tests so autocorrect for enum hash handle % array notations such as 
`%w[done todo archived]` are well corrected
> FIX #159 enum hash auto correct for % arrays

- config/default.yml
- lib/rubocop/cop/rails/rake_environment.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/rake_environment_spec.rb
The new [`Rails/RakeEnvironment`](https://github.com/rubocop-hq/rubocop-rails/blob/5707bb91e2581ce91e3fcaa92fbc362e6912acad/lib/rubocop/cop/rails/rake_environment.rb) task from @pocke is great! 😄 But there are a few copy edits that could make the offense more readable. 
This PR tweaks the wording of the offense and supporting documentation to increase readability. This is somewhat subjective, so let me know what you think!
* [ x Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* _should I do this?_
> Copyedit Rails/RakeEnvironment cop documentation.

- Gemfile
This PR solves the following "The manual directory is out of sync" error.
```console
% ruby -v
ruby 2.7.0dev (2019-12-03T05:51:14Z master e42d9d8df8) [x86_64-darwin17]
% CI=true bundle exec rake
(snip)
The manual directory is out of sync. Run `rake
generate_cops_documentation` and commit the results.
```
https://circleci.com/gh/rubocop-hq/rubocop-rails/2180
This issue will be resolved with the release of YARD 0.9.21 or higher, which includes the following changes:
https://github.com/lsegal/yard/pull/1290
> Workaround for broke CI with YARD 0.9.20

- CHANGELOG.md
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
The `Rails/BulkChangeTable` cop currently won't suggest combining table change method calls if there is another method call between them. However, this logic fails if the intervening call has a block, like so:
```ruby
add_column :users, :name, :string, null: false
User.find_each do |user|
user.update(name: user.nick_name)
end
remove_column :users, :nickname
```
This pull request fixes that problem by looking at all of the method body's children, not just the `:send` nodes.
> Don't register BulkChangeTable offense if block intervenes

- lib/rubocop/cop/rails/date.rb
This PR suppresses the following deprecation warning when using Ruby 2.7.0-dev.
```console
% ruby -v
ruby 2.7.0dev (2019-12-11T07:52:06Z master 3098798044) [x86_64-darwin17]
(snip)
/Users/koic/src/github.com/rubocop-hq/rubocop-rails/lib/rubocop/cop/rails/date.rb:87:
warning: The last argument is used as the keyword parameter
/Users/koic/src/github.com/rubocop-hq/rubocop-rails/lib/rubocop/cop/rails/date.rb:87:
warning: for method defined here; maybe ** should be added to the call?
```
https://bugs.ruby-lang.org/issues/14183
> Suppress a deprecation warning when using Ruby 2.7.0-dev

- spec/project_spec.rb
Follow rubocop-hq/rubocop#7542.
This PR suppresses the following warning.
```console
(snip)
Running RuboCop...
spec/project_spec.rb: Metrics/LineLength has the wrong namespace -
should be Layout
Inspecting 130 files
```
> Move `LineLength` cop from `Metrics` to `Layout` department

- lib/rubocop/cop/rails/relative_date_constant.rb
- manual/cops_rails.md
The current good example seems to discourage the usage of a constant
completely. Add another good example to showcase how to continue using a
constant and have things working dynamically.
> Add another good example for RelativeDateConstant

- CHANGELOG.md
- config/default.yml
**Since these files are generated by Rails, Rucocop should not
report offenses on them.**
> [Fix #166] Ignore db/schema and bin

- CHANGELOG.md
- lib/rubocop/cop/rails/rake_environment.rb
- spec/rubocop/cop/rails/rake_environment_spec.rb
> [Fix #184] Fix Rake/Environment to allow task with no block

- CHANGELOG.md
- config/default.yml
Fixes #122.
`Exclude` defined in RuboCop core was not inherited.
https://github.com/rubocop-hq/rubocop/blob/v0.79.0/config/default.yml#L60-L64
This PR fixes `Exclude` paths that were not inherited.
This bug was caused by #108.
> [Fix #122] Fix `Exclude` paths that were not inherited

- CHANGELOG.md
- lib/rubocop/rails/inject.rb
- spec/rubocop/rails/inject_spec.rb
`bin/*` and `db/schema.rb` were not excluded.
Exclude files should be absolute paths internally, so it fixes to call the `make_excludes_absolute` method.
Ref: https://github.com/rubocop-hq/rubocop/commit/cb63798f6ae27c54db566a88e143bd5354095226
> Fix the issue that excluded files in rubocop-rails did not work

- CHANGELOG.md
- lib/rubocop/cop/rails/http_positional_arguments.rb
- spec/rubocop/cop/rails/http_positional_arguments_spec.rb
Fixes #180
This PR fixes a false positive for `HttpPositionalArguments` when using `get` method with `:to` option.
> [Fix #180] Fix a false positive for `HttpPositionalArguments`

- CHANGELOG.md
- lib/rubocop/cop/rails/environment_comparison.rb
- spec/rubocop/cop/rails/environment_comparison_spec.rb
Fixes #193.
This PR makes `Rails/EnvironmentComparison` aware of the following comparisons:
- When `Rails.env` is used on RHS
- When `!=` is used to compare with `Rails.env`
> [Fix #193] Make `Rails/EnvironmentComparison` aware of several comparisons

- .rubocop.yml
- CHANGELOG.md
- config/default.yml
- lib/rubocop-rails.rb
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- lib/rubocop/cop/rails_cops.rb
- lib/rubocop/rails/schema_loader.rb
- lib/rubocop/rails/schema_loader/schema.rb
- manual/cops.md
- manual/cops_rails.md
- rubocop-rails.gemspec
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
- spec/rubocop/rails/schema_loader_spec.rb
The target is the ActiveRecord's uniqueness validation.
When you define uniqueness validation in a model, you also should add a unique index.
It has two reasons.
First, duplicated records may occur even if ActiveRecord's validation is defined.
The Rails Guide mentions this problem.
> This helper validates that the attribute's value is unique right before the object gets saved. It does not create a uniqueness constraint in the database, so it may happen that two different database connections create two records with the same value for a column that you intend to be unique. To avoid that, you must create a unique index on that column in your database.
https://guides.rubyonrails.org/active_record_validations.html#uniqueness
Second, it will cause slow queries.
The validation executes a …
> Add Rails/UniqueValidationWithoutIndex cop

- rubocop-rails.gemspec
Fixes #199.
This PR fixes the homepage URI.
> [Fix #199] Fix the homepage URI

- lib/rubocop/rails/schema_loader/schema.rb
- spec/rubocop/rails/schema_loader_spec.rb
This pull request fixes #200 
The error occurred on Rails 5 expression index.
> [Fix #200] Make SchemaLoader aware of Rails 5 expression index

- CHANGELOG.md
- lib/rubocop/cop/rails/reversible_migration.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/reversible_migration_spec.rb
The other table can be specified either as the second argument, or in the :to_table key of a hash as the second argument. The latter was not supported.
```ruby
def change
remove_foreign_key :accounts, to_table: :branches
end
```
> # Address false positive when reversing remove_foreign_key

- CHANGELOG.md
- config/default.yml
- manual/cops_rails.md
It excludes the directory where Capistrano tasks are located.
Because these tasks don't need to invoke the `:environment` task, and the directory structure is the official way.
ref: https://github.com/capistrano/capistrano/tree/v3.12.0#capify-your-project
Fixes #206
> [Fix #206] Fix a false positive for `Rails/RakeEnvironment` when using Capistrano

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/mixin/index_method.rb
- lib/rubocop/cop/rails/index_by.rb
- lib/rubocop/cop/rails/index_with.rb
- lib/rubocop/cop/rails_cops.rb
- manual/cops.md
- manual/cops_rails.md
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
Active Support provides [`Enumerable#index_by`](https://api.rubyonrails.org/classes/Enumerable.html#method-i-index_by), which creates a hash by yielding each element and using the result as the key and the original element as the value, and [`Enumerable#index_with`](https://api.rubyonrails.org/classes/Enumerable.html#method-i-index_with), which uses the result as the value and the original element as the key.
These cops identify and correct some patterns for doing the same thing using `each_with_object`, `map { ... }.to_h`, or `Hash[map { ... }]`.
This is heavily based on @djudd-stripe's work in https://github.com/rubocop-hq/rubocop/pull/7663, adapted to detect the same patterns when called on an enumerable rather than a hash.
Before submitting the PR make sure the …
> Add new Rails/IndexBy and Rails/IndexWith cops

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/rails/refute_methods.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/refute_methods_spec.rb
Fixes #150.
This PR adds `EnforcedStyle: refute` for `Rails/RefuteMethods`.
`EnforcedStyle: refute` is an alternative style to `EnforcedStyle: assert_not`.
```ruby
#
```
The default style keeps `EnforcedStyle: assert_not` because following the Rails coding style conventions..
> Use `assert_not` methods instead of refute.
https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#follow-the-coding-conventions
> [Fix #150] Add `EnforcedStyle: refute` for `Rails/RefuteMethods`

- lib/rubocop/rails/schema_loader/schema.rb
This PR fixes the following typo.
```diff
-Reprecent
+Represent
```
> Fix a typo

- CHANGELOG.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
Hey everybody!
This fixes a false positive for `Rails/UniqueValidationWithoutIndex` when using conditions, such as:
```rb
class User < ApplicationRecord
validates :email, uniqueness: true, unless: :guest?
end
```
--- 
> Fix false positive for `UniqueValidationWithoutIndex` when using conditions

- CHANGELOG.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
Fixes #215.
This PR fixes a false positive for `Rails/UniqueValidationWithoutIndex` when using Expression Indexes for PostgreSQL.
Since it is difficult to predict a kind of string described in Expression Indexes, this implementation judges based on whether or not an Expression Indexes include a column name.
There is a possibility of false negative, but in most cases I expect it works.
- https://www.postgresql.org/docs/12/indexes-expressional.html
- https://github.com/rails/rails/commit/edc2b7718725016e988089b5fb6d6fb9d6e16882
[1]: …
> [Fix #215] Fix a false positive for `Rails/UniqueValidationWithoutIndex`

- CHANGELOG.md
- lib/rubocop/rails/schema_loader/schema.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
Fixes #214.
This PR fixes an error for `Rails/UniqueValidationWithoutIndex` when a table has no column definition.
> [Fix #214] Fix an error for `Rails/UniqueValidationWithoutIndex`

- CHANGELOG.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- lib/rubocop/rails/schema_loader/schema.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
- spec/rubocop/rails/schema_loader_spec.rb
Fixes #221.
This PR makes `Rails/UniqueValidationWithoutIndex` aware of `add_index` in db/schema.rb.
Rails 4.0 and Rails 4.1 support will drop shortly, but Rails 4.2 may be a bit ahead. There may be changes to these support after the bug fix release of RoboCop Rails 2.5 series.
> [Fix #221] Make `Rails/UniqueValidationWithoutIndex` aware of `add_index`

- CHANGELOG.md
- config/default.yml
- manual/cops_rails.md
We have a controller class which inherits `ActionController::Base` directly.
That controller is for health check endpoint.
```ruby
class HealthCheckController < ActionController::Base
def index
head :ok
end
end
```
```ruby
class ApplicationController < ActionController::Base
end
```
In such case, automatically modifying the `ActionController :: Base`->` ApplicationController` is not safe .
> Mark `Rails/ApplicationController` and similar cops as unsafe autocorrect

- CHANGELOG.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- lib/rubocop/rails/schema_loader.rb
- spec/rubocop/cop/active_record_helper_spec.rb
Fixes #227.
This PR makes `Rails/UniqueValidationWithoutIndex` aware of updating db/schema.rb
`Rails/UniqueValidationWithoutIndex` cop needs to know both model and db/schema.rb changes to register an offense. However, with default RuboCop, only changes to the model affect cache behavior.
This PR ensures that changes to db/schema.rb affect the cache by overriding the following method:
```ruby
#
#
#
def external_dependency_checksum
nil
end
```
https://github.com/rubocop-hq/rubocop/blob/v0.81.0/lib/rubocop/cop/cop.rb#L222-L239
See for more details: https://github.com/rubocop-hq/rubocop/pull/7496
> [Fix #227] Make `Rails/UniqueValidationWithoutIndex` aware of updating schema.rb

- CHANGELOG.md
- lib/rubocop/cop/rails/skips_model_validations.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
Fixes https://github.com/rubocop-hq/rubocop-rails/issues/12.
The `Rails/SkipsModelValidations` cop currently incorrectly registers an offense for the `touch` method from Shoulda Matchers' associations DSL:
```ruby
it { is_expected.to belong_to(:user).touch(true) }
```
Active Record's `touch` method accepts attribute names, so we can treat `touch` calls that pass boolean literal arguments as false positives.
> [Fix #12] Allow passing boolean literals to touch

- .circleci/config.yml
- .rubocop.yml
- CHANGELOG.md
- rubocop-rails.gemspec
Follow rubocop-hq/rubocop#7869.
> Drop support for Ruby 2.3

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/rails/dynamic_find_by.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/dynamic_find_by_spec.rb
In `Rails/DynamicFindBy`.
Fixes https://github.com/rubocop-hq/rubocop-rails/issues/51.
> [Fix #51] Add ability to whitelist receiver class names

- CHANGELOG.md
- lib/rubocop/cop/mixin/index_method.rb
- spec/rubocop/cop/rails/index_by_spec.rb
I believe that the test cases included in this commit express well the
problem I'm trying to address, but running the auto-correction against
the following snippet of code:
```rb
x.map { |el| [el.to_sym, el] }.
to_h
```
Would yield:
```rb
x.index_by { |el| el.to_sym }. # notice the ending "dot"
```
The output isn't parseable/valid Ruby. I belive the problem has to do
with the fact that correction code assumes that the `.to_h` statement is
always grouped together (which isn't true).
The proposed solution was to compute the trailing characters to be
stripped by subtracting the end position of the map block (the `}` character)
from end position of the whole expression.
and description in grammatically correct, …
> Fixes Rails/IndexBy correction when .to_h is separated by a newline

- CHANGELOG.md
- README.md
- lib/rubocop/cop/rails/http_positional_arguments.rb
- lib/rubocop/cop/rails/inverse_of.rb
- lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb
- manual/cops_rails.md
- rubocop-rails.gemspec
- spec/rubocop/config_spec.rb
- spec/rubocop/cop/rails/redundant_receiver_in_with_options_spec.rb
- spec/support/shared_contexts.rb
Follow up to #222.
This PR drops support for Rails 4.1 or lower.
RuboCop Rails 2.6 will drop support for Rails 4.1 or lower. Maybe RuboCop Rails 3.0 will drop Rails 4 series support in future. RuboCop Rails is currently negative support for Rails 4 series, and new features for Rails 4 will basically not be accepted.
> Drop support for Rails 4.1 or lower

- CHANGELOG.md
- config/default.yml
Resolves #210.
The following idioms exist for `return` and` raise` in Ruby.
- `do_something and return`
- `do_something || raise`
And Rails will also show users the error message using this idiom.
> `"redirect_to(...) and return\"`
https://github.com/rails/rails/blob/v6.0.2.2/actionpack/lib/abstract_controller/rendering.rb#L10
This is the same for `render :action and return` and others.
`Style/AndOr` cop default rule (`EnforcedStyle: always`) does seem to unmatch for these cases. I think these cases need to be accepted.
So, this PR changes it to `EnforcedStyle: conditionals` at least in Rails. The enforced style cannot catch all cases, but probably the closest to solving the issue.
and description in …
> [Fix #210] Change enforced style to conditionals for `Style/AndOr`

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/rails/rake_environment.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/rake_environment_spec.rb
> Add autocorrect to `Rails/RakeEnvironment` cop

- spec/rubocop/cop/rails/unknown_env_spec.rb
This PR fixes the following test failure for JRuby on CI.
```console
1) RuboCop::Cop::Rails::UnknownEnv registers an offense for typo of
environment name with `==` operator
Failure/Error: spell_checker =
DidYouMean::SpellChecker.new(dictionary: environments)
NameError:
uninitialized constant DidYouMean::SpellChecker
`unknown_environment_equal?'
(snip)
rspec ./spec/rubocop/cop/rails/unknown_env_spec.rb:27 #
RuboCop::Cop::Rails::UnknownEnv registers an offense for typo of environment name with `==` operator
rspec ./spec/rubocop/cop/rails/unknown_env_spec.rb:16 #
RuboCop::Cop::Rails::UnknownEnv registers an offense for typo of environment name
```
https://circleci.com/gh/rubocop-hq/rubocop-rails/3393
and …
> Fix `NameError` for JRuby on CI

- lib/rubocop/cop/rails/content_tag.rb
- manual/cops_rails.md
- spec/rubocop/cop/rails/content_tag_spec.rb
Follow up to #242.
This PR allows `content_tag` when the first argument is a variable because `content_tag(name)` is simpler rather than `tag.public_send(name)`.
When `public_send` is used, it becomes complicated as follows.
First, `content_tag(name)` cannot be corrected to `tag.name` when the first argument is a variable.
So use `public_send` and prevent the following errors in that case:
Original code:
```ruby
content_tag(name, 'foo', class: 'bar')
```
Auto-corrected code (before):
```ruby
tag(name, 'foo', class: 'bar')
#=> NoMethodError (undefined method `each_pair' for "foo":String)
```
Auto-corrected code (after):
```ruby
tag.public_send(name, 'foo', class: 'bar')
```
Original code:
```ruby
content_tag(name, 'foo', {'class' => 'bar'})
```
Auto-corrected code (before):
```ruby …
```
> Fix an incorrect autocorrect for `Rails/ContentTag` cop

- tasks/cops_documentation.rake
Follow up to https://github.com/rubocop-hq/rubocop/pull/7947.
> Add required Ruby version to generated cops manual

- CHANGELOG.md
- lib/rubocop/cop/rails/save_bang.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
We can't detect `Hash#update` false positives in the general case, but when the receiver is `ENV` we know it's not an Active Record instance.
> Ignore ENV.update calls in Rails/SaveBang

- CHANGELOG.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
This cop looks for file paths constructed manually by interpolating `Rails.root` into a string. It currently assumes that some literal characters will follow that interpolation, which isn't always the case.
> Ignore Rails.root interpolation at end of string

- config/default.yml
Fixed typo in config/default.yml.
> Fix typo `redirect_to`

- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
This cop currently crashes when it encounters a `content_tag` method call with no arguments. The Rails method requires at least one argument, so we can treat a call with no arguments as a false positive.
This is a bug fix for an unreleased cop, so I don't think it needs a changelog entry. Please let me know if I should add one, though.
> Handle content_tag method calls with no arguments

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/uniq_before_pluck.rb
- spec/rubocop/cop/rails/uniq_before_pluck_spec.rb
Resolves #91 
Notes:
- I'm not sure if we need a separate cop to change `uniq` for `distinct` or if it's fine to convert `Model.pluck(:id).uniq` to `Model.distinct.pluck(:id)` within this cop.
- I'm not sure if we want to rename the cop to be `DistinctBeforePluck` or not, since that would be a breaking change.
> Fix UniqBeforePluck cop

- CHANGELOG.md
- rubocop-rails.gemspec
Follow up to https://github.com/rubocop-hq/rubocop-performance/issues/111.
This PR prepares to use RuboCop's new development API.
> Drop support for RuboCop 0.81 or lower

- lib/rubocop/cop/rails/uniq_before_pluck.rb
This PR suppresses the following Ruby's warning.
```console
% cd path/to/repo/rubocop-rails
(snip)
/Users/koic/src/github.com/rubocop-hq/rubocop-rails/lib/rubocop/cop/rails/uniq_before_pluck.rb:71:
warning: too many arguments for format string
```
> Suppress Ruby's warning

- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/uniq_before_pluck.rb
Follow up #135.
`Model.pluck(:id).distinct` happens the following `NoMethodError`.
```
NoMethodError: undefined method `distinct' for [42]:Array
```
This PR replaces it with `Array#uniq`.
> Fix a typo for `Rails/UniqBeforePluck`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- legacy-docs/cops_rails.md
- lib/rubocop/cop/rails/skips_model_validations.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
Use terminology which is more descriptive and is consistent with the direction of some upstream libraries:
https://github.com/rubocop-hq/rubocop/pull/6467
https://github.com/rails/rails/pull/33681
> Change terminology to `ForbiddenMethods` and `AllowedMethods`

- CHANGELOG.md
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
> Fix auto correction for `Rails/ContentTag` when `content_tag` is called with options hash and block

- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/pick.rb
Followup to https://github.com/rubocop-hq/rubocop-rails/pull/249.
- Fix a grammatical error.
- Explain why `pick` is preferable.
- Update an example to show that `pick` works on all enumerables.
> Update Rails/Pick documentation

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/skips_model_validations.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
Follows https://github.com/rails/rails/commit/0cb67a6307e0850dae285120e0292b7056c05237 and https://github.com/rails/rails/commit/e6f8bfe1dc2675eedc5fa42eb8ee92504ec11240.
> Detect insert_all and friends in Rails/SkipsModelValidations

- lib/rubocop/cop/rails/skips_model_validations.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
Adding `insert` to the forbidden methods list for SkipsModelValidations in https://github.com/rubocop-hq/rubocop-rails/pull/289 introduced false positives, particularly since [`String#insert`](https://ruby-doc.org/core-2.7.1/String.html#method-i-insert) and [`Array#insert`](https://ruby-doc.org/core-2.7.1/Array.html#method-i-insert) are commonly used.
We can reduce the impact by matching on the arguments: [Active Record's `insert` method](https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert) takes one positional argument and two optional keyword arguments (`:returning` and `:unique_by`). Anything else can be ignored.
> Fix insert false positives in SkipsModelValidations

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/active_record_callbacks_order.rb
- lib/rubocop/cop/rails_cops.rb
- spec/rubocop/cop/rails/active_record_callbacks_order_spec.rb
https://rails.rubystyle.guide/#callbacks-order
I always wanted to have a similar cop, and here it is 😄
> Add new `Rails/ActiveRecordCallbacksOrder` cop

- CHANGELOG.md
- lib/rubocop/cop/rails/unknown_env.rb
- spec/rubocop/cop/rails/unknown_env_spec.rb
The rubocop gem itself has a closed issue here:
https://github.com/rubocop-hq/rubocop/issues/7979
It details the fact that the DidYouMean constants are sometimes not
loaded even though the DidYouMean gem has been a part of Ruby since 2.3,
and should be required by default. The rubocop gem maintainers
determined this to be an upstream issue.
Here are some other relevant links to issues/PRs:
https://github.com/ruby/did_you_mean/issues/117
https://github.com/rubocop-hq/rubocop/pull/8143
My solution is mostly a band-aid fix to handle this problem until it is
fixed - use the DidYouMean spell checker if it is defined, otherwise
skip spell checking if it is not.
The changes to the specs might be considered "questionable", as I also added a
`defined?` check to the spec. This should also fix the …
> Handle undefined DidYouMean constants in UnknownEnv cop

- tasks/cops_documentation.rake
Seen in https://github.com/rubocop-hq/rubocop-rails/pull/299
This PR modifies `generate_cops_documentation` rake to support [v1-style autocorrect by extending AutoCorrector](https://docs.rubocop.org/rubocop/v1_upgrade_notes.html).
Fix taken from rubocop: https://github.com/rubocop-hq/rubocop/blob/343f62e4555be0470326f47af219689e21c61a37/tasks/cops_documentation.rake#L50
> Fix documentation rake task to support v1-style autocorrect

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
Fixes #301.
This PR sets disabled by default for `Rails/PluckId`.
An array object does not support `ids` method, that only works for an AR object. So, this PR defaults to prevent false alarms cause by it.
> [Fix #301] Set disabled by default for `Rails/PluckId`

- CHANGELOG.md
- lib/rubocop/cop/rails/render_inline.rb
- spec/rubocop/cop/rails/render_inline_spec.rb
Closes: https://github.com/rubocop-hq/rubocop-rails/issues/300
> [Fix #300] Fix `Rails/RenderInline` error on variable key in render options

- CHANGELOG.md
- lib/rubocop/cop/rails/match_route.rb
- spec/rubocop/cop/rails/match_route_spec.rb
> [Fix #305] Fix crash in `Rails/MatchRoute` cop when `via` option is a variable

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
Renaming a constant is always an unsafe operation.
> Mark Rails/MailerName as unsafe for auto-correct

- CHANGELOG.md
- lib/rubocop/cop/rails/active_record_callbacks_order.rb
- spec/rubocop/cop/rails/active_record_callbacks_order_spec.rb
This cop registers an offense when a callback appears after another callback that will be executed later in the record's lifecycle.
The auto-correct logic currently always moves the offending callback to before the first callback in the class. This does eventually produce the correct result, but it's not very efficient, and can reorder callbacks of the same type, which changes the order in which they're executed.
By moving the offending callback above the preceding one, the sort becomes stable and the original callback execution order is preserved.
> Preserve original callback execution order

- CHANGELOG.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
AST tree for a frozen object looks like:
```ruby
=> s(:send,
s(:array,
s(:sym, :b_id),
s(:sym, :c_id)), :freeze)
```
The type for that is `send`, so it fails to detect the correct type for a scope.
> [Bugfix] Allow to use frozen scope for Rails/UniqueValidationWithoutIndex

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
Adds missing offenses for `remove_columns` and `remove_index` methods.
This is my first Rubocop contribution, so please review carefully!
> Register new offenses for

- CHANGELOG.md
- lib/rubocop/cop/rails/helper_instance_variable.rb
- spec/rubocop/cop/rails/helper_instance_variable_spec.rb
Fixes #311
This PR makes `Rails/HelperInstanceVariable` aware of memoization.
> [Fix #311] Make `Rails/HelperInstanceVariable` aware of memoization

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/pluck_in_where.rb
- spec/rubocop/cop/rails/pluck_in_where_spec.rb
Fixes #310.
This PR adds `EnforcedStyle` to `Rails/PluckInWhere`. By default, it does not register an offense if `pluck` method's receiver is a variable.
> [Fix #310] Add `EnforcedStyle` to `Rails/PluckInWhere`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/uniq_before_pluck.rb
`Rails/UniqBeforePluck` is unsafe depending on the database collation.
Here is an example of an unsafe case for the three databases that Rails supports(MySQL, SQLite, PostgreSQL).
The default collation is `utf8mb4_general_ci`(in Rails), so it is unsafe.
An example is as follows.
- Create table
```
class CreateUsers < ActiveRecord::Migration[6.0]
def change
create_table :users do |t|
t.string :name
end
end
end
```
- Create data
```
User.create!(name: 'A')
User.create!(name: 'a')
```
before autocorrect
```
User.pluck(:name).uniq #=> ["A", "a"]
```
after autocorrect
```
User.distinct.pluck(:name) #=> ["A"]
```
The default collation is `BINARY`, so it is safe.
If you change the collation to `NOCASE`, the collation is unsafe.
The following is an example.
- Create table
```
class CreateUsers < …
```
> Mark `Rails/UniqBeforePluck` cops as unsafe

- CHANGELOG.md
- lib/rubocop/cop/rails/inquiry.rb
- spec/rubocop/cop/rails/inquiry_spec.rb
Fixes #319.
This PR fixes a false positive for `Rails/Inquiry` when `#inquiry`'s receiver is a variable.
It should only detect when receiver is an array literal and a string literal.
> [Fix #319] Fix a false positive for `Rails/Inquiry`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/mixin/index_method.rb
- lib/rubocop/cop/rails/index_by.rb
- lib/rubocop/cop/rails/index_with.rb
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
Followup to https://github.com/rubocop-hq/rubocop-rails/pull/208.
See also https://github.com/rubocop-hq/rubocop/pull/8517.
Since Ruby 2.6, `Enumerable#to_h` accepts a block which is called with each element and must return a key and value to include in the new hash: https://rubyreferences.github.io/rubychanges/2.6.html#to_h-with-a-block
If the element is always returned as either the key or the value, using `Enumerable#index_by` or `Enumerable#index_with` is faster and clearer.
This is similar to the existing logic that detects `map { ... }.to_h`.
> Handle to_h with block in Rails/IndexBy and Rails/IndexWith

- CHANGELOG.md
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
Allow auto-correction of tag names with hyphen, e.g. `trix-editor` to
`tag.trix_editor` instead of correcting to deprecated
`tag('trix-editor')` syntax.
The deprecated syntax does not support a content parameter, so the
arguments in the corrected code were incorrect when correcting a
method name with a hyphen and content, such as
`content_tag('trix-editor' 'my content!')`
> Fixes auto-correct of content_tag with hyphenated tag name

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
Follow #320 and https://github.com/rubocop-hq/rubocop/pull/8529.
This PR changes the mark of `Rails/UniqBeforePluck` from `Safe: false` to `SafeAutoCorrect: false`.
False positives to detection are not a concern. Only worry about incompatibilities with auto-correction.
Below is an excerpt from the official document.
> * Safe (true/false) - indicates whether the cop can yield false positives (by design) or not.
>
> * SafeAutoCorrect (true/false) - indicates whether the auto-correct a cop does is safe (equivalent) by design. If a cop is unsafe its auto-correct automatically becomes unsafe as well.
https://docs.rubocop.org/rubocop/0.89/usage/auto_correct.html#safe-auto-correct
Cc @kunitoo 
and description in …
> Mark `Rails/UniqBeforePluck` cop as unsafe auto-correction

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/where_exists.rb
- spec/rubocop/cop/rails/where_exists_spec.rb
Fixes #341.
Adds `EnforcedStyle` to `Rails/WhereExists` to allow the preferred style to be configurable. The previous preference of `exists?(...)` is retained as the default, but `EnforcedStyle: where` allows `where(...).exists?` to be prefered instead.
> [Fix #341] Add EnforcedStyle to Rails/WhereExists to allow where(...).exists? to be the enforced style

- CHANGELOG.md
- lib/rubocop/cop/rails/after_commit_override.rb
- spec/rubocop/cop/rails/after_commit_override_spec.rb
Fixes #345 
I got the same error on our Rails project, and I've confirmed the error is fixed by this patch. 
> [Fix #345] Fix error of `Rails/AfterCommitOverride` on `after_commit`with a lambda

- CHANGELOG.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
`Rails/UniqueValidationWithoutIndex` dies with following error:
When the table does not exist:
```
An error occurred while Rails/UniqueValidationWithoutIndex cop was inspecting <filename>.
undefined method `each_node' for nil:NilClass
.../lib/rubocop/cop/mixin/active_record_helper.rb:14:in `find_set_table_name'
```
When defining `module` instead of `class`:
```
An error occurred while Rails/UniqueValidationWithoutIndex cop was inspecting <filename>.
undefined method `with_column?' for nil:NilClass
.../lib/rubocop/cop/mixin/active_record_helper.rb:55:in `resolve_relation_into_column'
```
> Fix errors of `Rails/UniqueValidationWithoutIndex`

- CHANGELOG.md
- lib/rubocop/cop/rails/index_by.rb
- lib/rubocop/cop/rails/index_with.rb
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
If the `each_with_object` hash is used in the transformed key or value, `Rails/IndexBy` or `Rails/IndexWith` can't be used.
> [Fix #338][Fix #350] Fix a false positive for Rails/IndexBy and Rails/IndexWith

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/where_not.rb
- spec/rubocop/cop/rails/where_not_spec.rb
SQL standard defines `<>` as not-equal operator. `!=` is a de facto standard.
cf. https://www.postgresql.org/docs/12/functions-comparison.html
(I'm afraid I have no pointer to SQL standard documentation.)
> Add `<>` operator to `Rails/WhereNot` cop.

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/http_positional_arguments.rb
- spec/rubocop/cop/rails/http_positional_arguments_spec.rb
The following code will no longer register an offense:
```ruby
[{ format: :json }, { format: :html }].each do |args|
get :nothing, **args
end
```
Fixes #352.
> [Fix #352] Do not register an offense for `Rails/HttpPositionalArguments` when given a splatted hash

- spec/rubocop/cop/active_record_helper_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8707
This PR suppresses the following RuboCop's offense.
```console
(snip)
Offenses:
spec/rubocop/cop/active_record_helper_spec.rb:6:3: W:
Lint/ConstantDefinitionInBlock: Do not define constants within a block.
module RuboCop ...
^^^^^^^^^^^^^^
185 files inspected, 1 offense detected, 1 offense auto-correctable
RuboCop failed!
```
> Suppress RuboCop's offense

- CHANGELOG.md
- lib/rubocop/cop/rails/dynamic_find_by.rb
- spec/rubocop/cop/rails/dynamic_find_by_spec.rb
This PR fixes a false positive for `Rails/DynamicFindBy` when any of the arguments are splat argument.
```console
% cat example.rb
find_by_scan(*args)
% bundle exec rubocop -a example.rb
(snip)
E
Offenses:
example.rb:1:1: C: [Corrected] Rails/DynamicFindBy: Use find_by instead
of dynamic find_by_scan.
find_by_scan(*args)
^^^^^^^^^^^^^^^^^^^
example.rb:1:15: E: Lint/Syntax: unexpected token tSTAR
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter,
under AllCops)
find_by(scan: *args)
^
1 file inspected, 2 offenses detected, 1 offense corrected
% cat example.rb
find_by(scan: *args)
% ruby -c example.rb
example.rb:1: syntax error, unexpected *
find_by(scan: *args)
```
and …
> Fix a false positive for `Rails/DynamicFindBy`

- CHANGELOG.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
Fixes #357.
This PR fixes a false positive for `Rails/ReversibleMigration` when keyword arguments of `change_column_default` are in the
order of `to`, `from`.
> [Fix #357] Fix a false positive for `Rails/ReversibleMigration`

- CHANGELOG.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- spec/rubocop/cop/active_record_helper_spec.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
There is a problem that `Rails/UniqueValidationWithoutIndex` doesn't work
because it can't find the table name in the class defined with compact style.
This commit adds test code to ensure existing behavior and adds support for
classes defined with compact style.
> Add Support for classes defined with compact style

- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/attribute_default_block_value.rb
- spec/rubocop/cop/rails/attribute_default_block_value_spec.rb
The [Attributes API](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute) also allows defining attributes that are arrays or hashes.
```ruby
#
#
```
This PR patches up the `AttributeDefaultBlockValue` cop accordingly.
Reason why array and hash literals should also be passed as a block is the fact that defining them without one creates a class attribute, not instance.
```ruby
class Simple < ActiveType::Object
attribute :mutable_attribute, default: {}
end
```
```bash
[1] pry(main)> first = Simple.new
=> #<Simple mutable_attribute: {}>
[2] pry(main)> first.mutable_attribute.merge!(a: 3)
=> {:a=>3}
[3] pry(main)> second = Simple.new
=> #<Simple mutable_attribute: {:a=>3}>
[4] pry(main)> second.mutable_attribute
=> {:a=>3}
[5] pry(main)> …
```
> Add array and hash literal offenders to AttributeDefaultBlockValue

- .rubocop.yml
This PR disables `RSpec/FactoryBot/CreateList` as a workaround for https://github.com/rubocop-hq/rubocop-rails/issues/374.
> Disable `RSpec/FactoryBot/CreateList` cop

- CHANGELOG.md
- lib/rubocop/cop/rails/active_record_callbacks_order.rb
- spec/rubocop/cop/rails/active_record_callbacks_order_spec.rb
> Fix an infinite loop error for `Rails/ActiveRecordCallbacksOrder` when callbacks have inline comments

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/negate_include.rb
Fixes #384
This PR marks unsafe for `Rails/NegateInclude` because false positive will occur for a receiver object that do not have `exclude?` method. (e.g. `IPAddr`)
> [Fix #384] Mark unsafe for `Rails/NegateInclude`

- spec/rubocop/cop/rails/action_filter_spec.rb
- spec/rubocop/cop/rails/blank_spec.rb
- spec/rubocop/cop/rails/date_spec.rb
- spec/rubocop/cop/rails/dynamic_find_by_spec.rb
- spec/rubocop/cop/rails/find_each_spec.rb
- spec/rubocop/cop/rails/output_spec.rb
- spec/rubocop/cop/rails/pluralization_grammar_spec.rb
- spec/rubocop/cop/rails/presence_spec.rb
- spec/rubocop/cop/rails/present_spec.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
- spec/rubocop/cop/rails/safe_navigation_spec.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
- spec/rubocop/cop/rails/uniq_before_pluck_spec.rb
- spec/rubocop/cop/rails/validation_spec.rb
This PR uses new `expect_offense`, `expect_correction` instead of `cop.offenses`, `cop.highlights`, and `cop.messages` APIs.
> Use new `expect_offense`, `expect_correction` instead of old APIs

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/squished_sql_heredocs.rb
> [Fix #365] Mark `Rails/SquishedSQLHeredocs` unsafe for autocorrection

- lib/rubocop/cop/mixin/enforce_superclass.rb
- lib/rubocop/cop/rails/application_controller.rb
- lib/rubocop/cop/rails/application_job.rb
- lib/rubocop/cop/rails/application_mailer.rb
- lib/rubocop/cop/rails/application_record.rb
- lib/rubocop/cop/rails_cops.rb
Follow rubocop-hq/rubocop#7868.
This PR imports enforce superclass module  and uses `Cop::Base` API for cops mixing `EnforceSuperclass` module.
> Import `EnforceSuperclass` module

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/find_each.rb
- spec/rubocop/cop/rails/find_each_spec.rb
Closes #389
Also add `lock` to `IgnoredMethods`.
> [Fix #389] Add `IgnoredMethods` configuration option for `Rails/FindEach` cop

- CHANGELOG.md
- lib/rubocop/cop/rails/redundant_allow_nil.rb
- spec/rubocop/cop/rails/redundant_allow_nil_spec.rb
Fix [367](https://github.com/rubocop-hq/rubocop-rails/issues/376)
The issue occurs because we are checking the presence of allow_nil and allow_blank within the whole node tree
What we need to do is to check only the presence of this both when they are used on the same helper / level
If you want a specific message depending on the helper, it makes sense to have one or the other in different helpers of the same validation (CF issue)
> [Fix 376] Fix redunctantAllowNil false positive offense

- CHANGELOG.md
- lib/rubocop/cop/rails/find_each.rb
- spec/rubocop/cop/rails/find_each_spec.rb
Fixes a bug in https://github.com/rubocop-hq/rubocop-rails/pull/392
It never worked, because it was comparing strings (from config) to symbols (from [`method_name`](https://rubydoc.info/github/rubocop-hq/rubocop-ast/RuboCop%2FAST%2FDefNode:method_name)). The tests only passed because of what was in `SCOPE_METHODS`.
> Fix bug in `Rails/FindEach`

- CHANGELOG.md
- lib/rubocop/cop/rails/where_equals.rb
- spec/rubocop/cop/rails/where_equals_spec.rb
Fixes #401.
This PR fixes an error for `Rails/WhereEquals` when using only named placeholder template without replacement argument.
> [Fix #401] Fix an error for `Rails/WhereEquals`

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/helper_instance_variable.rb
- spec/rubocop/cop/rails/helper_instance_variable_spec.rb
Fixes #404.
This PR makes `Rails/HelperInstanceVariable` accept of instance variables when class inherited `ActionView::Helpers::FormBuilder`.
It may be too broad to accept all instance variables, but view helper and form builder have different uses, so let's take a look first.
> [Fix #404] Make `Rails/HelperInstanceVariable` accept of instance variables

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/where_equals.rb
- spec/rubocop/cop/rails/where_equals_spec.rb
With this change, the cops suggestions and autocorrect splits a namespaces column reference into 
`table: { column: value }`.
Example:
```
Comment.joins(:post).where('posts.title = ?', 'Title')
```
turns into -> 
```
Comment.joins(:post).where(posts: { title: 'Title' })
```
> Rails/WhereEquals add table/column split

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/where_not.rb
- spec/rubocop/cop/rails/where_not_spec.rb
With this change, the cops suggestions and autocorrect splits a namespaces column reference into 
`table: { column: value }`.
Example:
```
Comment.joins(:post).where.not('posts.title = ?', 'Title')
```
turns into -> 
```
Comment.joins(:post).where.not(posts: { title: 'Title' })
```
PS: Almost the same as #406 
> `Rails/WhereNot` add table/column split

- CHANGELOG.md
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes #415
This pull request makes `Rails/HasManyOrHasOneDependent` accept combination of association extension and `with_options`.
```ruby
class Person < ApplicationRecord
with_options dependent: :destroy do
has_many :foo do
def bar
end
end
end
end
```
The code above is going to be parsed as below.
```
s(:class,
s(:const, nil, :Person),
s(:const, nil, :ApplicationRecord),
s(:block,
s(:send, nil, :with_options,
s(:hash,
s(:pair,
s(:sym, :dependent),
s(:sym, :destroy)))),
s(:args),
s(:block,
s(:send, nil, :has_many,
s(:sym, :foo)),
s(:args),
s(:def, :bar,
s(:args), nil))))
```
> [Fix #415] Make `Rails/HasManyOrHasOneDependent` accept association extension

- CHANGELOG.md
- lib/rubocop/cop/rails/link_to_blank.rb
- spec/rubocop/cop/rails/link_to_blank_spec.rb
Fixes #421.
This PR fixes incorrect auto-correct for `Rails/LinkToBlank` when using `target: '_blank'` with hash brackets for the option.
> [Fix #421] Fix incorrect auto-correct for `Rails/LinkToBlank`

- lib/rubocop/cop/rails/http_positional_arguments.rb
- spec/rubocop/cop/rails/http_positional_arguments_spec.rb
This PR tweaks offense highlight range for `Rails/HttpPositionalArgument`.
> Tweak offense highlight range for `Rails/HttpPositionalArgument`

- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
noticed that Rails/FilePath was the only cop not following the "Prefer" / "Use" convention :trollface:
> stop being nice

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
Fixes #432.
This PR excludes gemspec file by default for `Rails/TimeZone` cop.
> [Fix #432] Exclude gemspec file by default for `Rails/TimeZone` cop

- CHANGELOG.md
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
Fixes #436.
This PR fixes a false positive for `Rails/ContentTag` when the first argument is a splat argument.
> [Fix #436] Fix a false positive for `Rails/ContentTag`

- CHANGELOG.md
- lib/rubocop/cop/rails/belongs_to.rb
- spec/rubocop/cop/rails/belongs_to_spec.rb
Fixes #435.
This PR fixes a false negative for `Rails/BelongsTo` when using `belongs_to` lambda block with `required` option.
> [Fix #435] Fix a false negative for `Rails/BelongsTo`

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
Fixes #440.
This PR makes `Rails/TimeZone` aware of timezone specifier.
> [Fix #440] Make `Rails/TimeZone` aware of timezone specifier

- CHANGELOG.md
- config/default.yml
Follows rubocop-hq/rubocop#8950.
Adds Rails' duration methods to the `IgnoredMethods` list for `Lint/NumberConversion`, so that calling `to_i` on one of them does not register an offense.
> Update IgnoredMethods for Lint/NumberConversion

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/blank.rb
Fixes ##444.
This PR marks `Rails/Blank` as unsafe auto-correction because `' '.empty?` returns false, but `' '.blank?` returns true. Therefore, auto-correction is not compatible if the receiver is a non-empty blank string, tab, or newline meta characters.
> [Fix #444] Mark `Rails/Blank` as unsafe auto-correction

- CHANGELOG.md
- lib/rubocop/cop/rails/relative_date_constant.rb
- spec/rubocop/cop/rails/relative_date_constant_spec.rb
Fixes #451.
This PR fixes a false negative for `Rails/RelativeDateConstant` when a method is chained after a relative method and
makes `Rails/RelativeDateConstant` aware of `yesterday` and `tomorrow` methods.
> [Fix #451] Fix a false negative for `Rails/RelativeDateConstant`

- CHANGELOG.md
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
Closes https://github.com/rubocop/rubocop-rails/issues/450
Similar approach as this one: https://github.com/rubocop/rubocop/pull/8893/files
> Fix a crash for `Rails/ContentTag` cop with nested tags

- .circleci/config.yml
- .rubocop.yml
- CHANGELOG.md
- lib/rubocop/cop/rails/attribute_default_block_value.rb
- rubocop-rails.gemspec
- tasks/cops_documentation.rake
Follow https://github.com/rubocop/rubocop/pull/9648.
> Drop Ruby 2.4 support

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/where_exists.rb
This cop is unsafe because the behavior may change on the following case:
```ruby
Author.includes(:articles).where(articles: {id: id}).exists?
#=> Perform `eager_load` behaviour (`LEFT JOIN` query) and get result.
Author.includes(:articles).exists?(articles: {id: id})
#=> Perform `preload` behaviour and `ActiveRecord::StatementInvalid` error occurs.
```
And this cop may be considered disabled by default as there is no consensus on the default style.
- https://github.com/rubocop/rubocop-rails/pull/286
- https://github.com/rubocop/rubocop-rails/pull/342
> Mark `Rails/WhereExists` as unsafe auto-correction

- CHANGELOG.md
- config/obsoletion.yml
- lib/rubocop/rails.rb
- rubocop-rails.gemspec
- spec/project_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/9206 and https://github.com/rubocop-hq/rubocop/pull/9143.
This PR requires RuboCop 1.7 or higher due to support obsoletion configuration and reverts https://github.com/rubocop/rubocop-rails/commit/151b8a6.
> Require RuboCop 1.7 or higher due to support obsoletion configuration

- CHANGELOG.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/cop/rails/find_each.rb
- spec/rubocop/cop/rails/find_each_spec.rb
Fixes #103.
This PR fixes a false positive for `Rails/FindEach` when not inheriting `ActiveRecord::Base` and using `all.each`.
> [Fix #103] Fix a false positive for `Rails/FindEach`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
Fixes #379.
This PR marks `Rails/DynamicFindBy` as unsafe.
> [Fix #379] Mark `Rails/DynamicFindBy` as unsafe

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes #147.
Closes #176.
This PR fixes a false positive for `Rails/HasManyOrHasOneDependent` when specifying default `dependent: nil` strategy.
> [Fix #147] Fix a false positive for `Rails/HasManyOrHasOneDependent`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
Fixes #403 and #418.
This PR marks `Rails/WhereEquals` as unsafe auto-correction.
> [Fix #403] Mark `Rails/WhereEquals` as unsafe auto-correction

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/reflection_class_name.rb
Fixes #106.
This PR marks `Rails/ReflectionClassName` as unsafe.
And it would be possible to exclude `to_s` call other than constants. I will consider opening it as a separate PR.
> [Fix #106] Mark `Rails/ReflectionClassName` as unsafe

- CHANGELOG.md
- lib/rubocop/cop/rails/reflection_class_name.rb
- spec/rubocop/cop/rails/reflection_class_name_spec.rb
Follow https://github.com/rubocop/rubocop-rails/pull/469
Fixes #106.
This PR makes `Rails/ReflectionClassName` aware of the use of string with `to_s`.
> [Fix #106] Make `Rails/ReflectionClassName` aware of the use of string with `to_s`

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes #137.
This PR makes `Rails/HasManyOrHasOneDependent` aware of `readonly?` is `true`.
There may be false positives or false negatives with just `def readonly? = true`, but it makes it possible to detect perhaps general definition of `readonly?` method.
> [Fix #137] Make `Rails/HasManyOrHasOneDependent` aware of `readonly` is `true`

- CHANGELOG.md
- lib/rubocop/cop/rails/safe_navigation.rb
- spec/rubocop/cop/rails/safe_navigation_spec.rb
This PR fixes a false negative for `Rails/SafeNavigation` when using `try!` without receiver.
> Fix a false negative for `Rails/SafeNavigation`

- CHANGELOG.md
- lib/rubocop/cop/rails/safe_navigation.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/spec_helper.rb
- spec/support/cli_spec_behavior.rb
Fixes #126.
This PR fixes an incorrect auto-correct for `Rails/SafeNavigation` with `Style/RedndantSelf`.
> [Fix #126] Fix an incorrect auto-correct for `Rails/SafeNavigation`

- CHANGELOG.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
Fixes #476.
This PR fixes a false positive for `Rails/ReversibleMigratin` when using `drop_table` with symbol proc.
> [Fix #476] Fix a false positive for `Rails/ReversibleMigration`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
`Include` instead of `include`, otherwise the cop will target all Ruby files
Related to #457
> Fix ReversibleMigrationMethodDefinition "Include" case

- CHANGELOG.md
- lib/rubocop/rails/schema_loader/schema.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
Fixes #419.
This PR fixes an error for `Rails/UniqueValidationWithoutIndex` when using a unique index and `check_constraint` that has `nil` first argument.
> [Fix #419] Fix an error for `Rails/UniqueValidationWithoutIndex`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/date.rb
- spec/rubocop/cop/rails/date_spec.rb
Fixes #288.
This PR adds `AllowToTime` option (`true` by default) to `Rails/Date`.
> [Fix #288] Add `AllowToTime` option to `Rails/Date`

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
Fixes #70.
This PR fixes a false positive for `Rails/TimeZone` when setting `EnforcedStyle: strict` and using `Time.current`.
> [Fix #70] Fix a false positive for `Rails/TimeZone`

- CHANGELOG.md
- lib/rubocop/cop/rails/reversible_migration_method_definition.rb
- spec/rubocop/cop/rails/reversible_migration_method_definition_spec.rb
Fixes #488.
This PR fixes a false positive for `Rails/ReversibleMigrationMethodDefinition` when using cbase migration class.
> [Fix #488] Fix a false positive for `Rails/ReversibleMigrationMethodDefinition`

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Rakefile
- spec/project_spec.rb
- tasks/changelog.rake
- tasks/changelog.rb
- tasks/cut_release.rake
Follow https://github.com/rubocop/rubocop/pull/8930 and https://github.com/rubocop/rubocop/commit/3fc75c4.
> Add rake tasks for alternative way to specify Changelog entries

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/http_status.rb
- spec/rubocop/cop/rails/http_status_spec.rb
Fixes #490.
This PR makes `Rails/HttpStatus` aware of `head` method.
> [Fix #490] Make `Rails/HttpStatus` aware of `head` method

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/find_by.rb
- spec/rubocop/cop/rails/find_by_spec.rb
Fixes #499.
This PR add `IgnoreWhereFirst` option (`true` by default) to `Rails/FindBy` cop.
> [Fix #499] Add `IgnoreWhereFirst` to `Rails/FindBy` cop

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
This PR sets disabled by default for `Rails/EnvironmentVariableAccess`.
The default status will be set to `pending` again when migration doc is written.
https://github.com/rubocop/rubocop-rails/pull/442#issuecomment-835790239
> Set disabled by default for `Rails/EnvironmentVariableAccess`

- CHANGELOG.md
- lib/rubocop/cop/rails/find_by.rb
- spec/rubocop/cop/rails/find_by_spec.rb
Follow up https://github.com/rubocop/rubocop-rails/pull/506#issuecomment-865651860.
This PR fixes an error for `Rails/FindBy` when calling `take` after block.
> Fix an error for `Rails/FindBy`

- lib/rubocop/cop/rails/find_by.rb
- spec/rubocop/cop/rails/find_by_spec.rb
Fixes - https://github.com/rubocop/rubocop-rails/issues/504
If I'm not mistaken the https://github.com/rubocop/rubocop-rails/pull/502 PR removed an important part of the `Rails/FindBy` cop which was checking for a presence of `where()` method call in the method chain.
Without this check the cop tries to autocorrect an offence for regular enumerable `first` and `take` methods
This PR basically brings the check back with a bit different name.
> [Fix #504] Rails/FindBy being wrongly triggered on non Active Record methods

- CHANGELOG.md
- lib/rubocop/cop/rails/reflection_class_name.rb
- spec/rubocop/cop/rails/reflection_class_name_spec.rb
This PR fixes bug introduced in https://github.com/rubocop/rubocop-rails/pull/471.
> Fix an error for `Rails/ReflectionClassName` when using `class_name: to_s`

- CHANGELOG.md
- lib/rubocop/cop/rails/find_by.rb
- spec/rubocop/cop/rails/find_by_spec.rb
Upgrading rubocop-rails from 2.10.1 to 2.11.0 caused the following crash:
```
An error occurred while Rails/FindBy cop was inspecting /Users/paj/src/sso-server/app/models/username_suggestor.rb:63:6.
For /Users/paj/src/sso-server: configuration from /Users/paj/src/sso-server/.rubocop.yml
configuration from /Users/paj/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.11.3/config/default.yml
configuration from /Users/paj/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.11.3/config/default.yml
Default configuration from /Users/paj/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.17.0/config/default.yml
configuration from /Users/paj/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-rails-2.11.0/config/default.yml
configuration …
```
> Fix an error for `Rails/FindBy` when calling `#first` or `#take` on a `Range` object.

- CHANGELOG.md
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
Fixes #515
Follow up https://github.com/ruby/psych/pull/487 and https://github.com/rails/rails/commit/255b5ff
This PR fixes an error for `Rails/BulkChangeTable` when using Psych 4.0.
> [Fix #515] Fix an error for `Rails/BulkChangeTable`

- CHANGELOG.md
- lib/rubocop/cop/rails/find_by.rb
- spec/rubocop/cop/rails/find_by_spec.rb
Fix #512
This PR fixes a false positive for `Rails/FindBy` when using `take` with arguments.
> [Fix #512] Fix a false positive for `Rails/FindBy`

- CHANGELOG.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
This PR fixes the `UniqueValidationWithoutIndex` cop when the `scope` of the uniqueness constraint is a polymorphic association. The issue detailed in https://github.com/rubocop/rubocop-rails/issues/231#issuecomment-660521974.
Thanks!
> Fix `UniqueValidationWithoutIndex` cop when validating uniqueness on a polymorphic relation scope

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/output.rb
- spec/rubocop/cop/rails/output_spec.rb
This PR supports auto-correction for `Rails/Output`.
> Support auto-correction for `Rails/Output`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/scope_args.rb
- spec/rubocop/cop/rails/scope_args_spec.rb
This PR supports auto-correction for `Rails/ScopeArgs`.
> Support auto-correction for `Rails/ScopeArgs`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
Fix #260
This PR fixes target of `Rails/ContentTag` cop.
The reason is that it is unclear wheather `content_tag` is deprecated, and auto-correction may cause performance regression.
Following test cases are added. 
- If first argument is kebab case, it can be autocorrected to snake case method.
- If first argument is snake case, it cannot be autocorrected.
```rb
#!/usr/bin/env rails runner
helper = ApplicationController.helpers
puts helper.tag("foo-bar")
puts helper.tag("foo_bar")
puts helper.tag.foo_bar
puts helper.tag("-foo")
puts helper.tag("_foo")
puts helper.tag._foo
```
> [Fix #260] Fix target of `Rails/ContentTag`

- CHANGELOG.md
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes #528.
This PR fixes a false positive for `Rails/HasManyOrHasOneDependent` when specifying `:dependent` strategy with double splat.
> [Fix #528] Fix a false positive for `Rails/HasManyOrHasOneDependent`

- CHANGELOG.md
- lib/rubocop/cop/rails/lexically_scoped_action_filter.rb
- spec/rubocop/cop/rails/lexically_scoped_action_filter_spec.rb
Fixes #529.
This PR fixes a false positive for `Rails/LexicallyScopedActionFilter` when action method is aliased by `alias_method`.
> [Fix #529] Fix a false positive for `Rails/LexicallyScopedActionFilter`

- CHANGELOG.md
- lib/rubocop/cop/rails/http_positional_arguments.rb
- spec/rubocop/cop/rails/http_positional_arguments_spec.rb
Fixes #532.
This PR fixes a false positive for `Rails/HttpPositionalArguments` when defining `get` in `Rails.application.routes.draw` block.
> [Fix #532] Fix a false positive for `Rails/HttpPositionalArguments`

- CHANGELOG.md
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes #535.
This PR fixes an error for `Rails/HasManyOrHasOneDependent` when using lambda argument and not specifying any options.
> [Fix #535] Fix an error for `Rails/HasManyOrHasOneDependent`

- CHANGELOG.md
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes #541.
This PR fixes a false positive for `Rails/HasManyOrHasOneDependent` when using lambda argument and specifying `:dependent` strategy.
> [Fix #541] Fix a false positive for `Rails/HasManyOrHasOneDependent`

- changelog/fix_error_for_rails_content_tag.md
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
Fixes #543.
This PR fixes an error for `Rails/ContentTag` when `tag` is not a top-level method.
> [Fix #543] Fix an error for `Rails/ContentTag`

- changelog/change_exclude_models_by_default_for_rails_content_tag.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
Fixes #546
This PR excludes `app/models` by default for `Rails/ContentTag`. Because it prevents false positives for `tag` calls to `has_one: tag`. No helpers are used in normal models.
> [Fix #546] Exclude `app/models` by default for `Rails/ContentTag`

- changelog/fix_a_false_positive_for_rails_find_each.md
- lib/rubocop/cop/rails/find_each.rb
- spec/rubocop/cop/rails/find_each_spec.rb
Fixes #551.
This PR fixes a false positive for `Rails/FindEach` when using `model.errors.where` in Rails 6.1.
> [Fix #551] Fix a false positive for `Rails/FindEach`

- changelog/fix_error_for_rails_relative_date_constant.md
- lib/rubocop/cop/rails/relative_date_constant.rb
- spec/rubocop/cop/rails/relative_date_constant_spec.rb
Fixes #559.
This PR fixes an error for `Rails/RelativeDateConstant` when using multiple assignment.
> [Fix #559] Fix an error for `Rails/RelativeDateConstant`

- config/default.yml
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
Based on [this StackOverflow question](https://stackoverflow.com/questions/69323472/rubocop-uniqueness-validation-should-be-with-a-unique-index-in-values-that-star), I think the wording can be improved.
> Improve wording for `Rails/UniqueValidation` description

- changelog/fix_a_false_positive_for_rails_content_tag.md
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
Fixes #556.
This PR fixes a false positive for `Rails/ContentTag` when using using the `tag` method with 3 or more arguments.
> [Fix #556] Fix a false positive for `Rails/ContentTag`

- .github/workflows/spell_checking.yml
- codespell.txt
- config/default.yml
- relnotes/v2.7.1.md
- spec/rubocop/cop/rails/redundant_receiver_in_with_options_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/10128.
> Add spell checking GitHub Actions workflow

- CHANGELOG.md
- changelog/new_schema_comment_cop.md
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/mixin/active_record_migrations_helper.rb
- lib/rubocop/cop/rails/create_table_with_timestamps.rb
- lib/rubocop/cop/rails/schema_comment.rb
- lib/rubocop/cop/rails_cops.rb
- spec/rubocop/cop/rails/schema_comment_spec.rb
Hi, this is my first contribuiton here, so I'm sorry if got something wrong and I hope we can fix it together :)
Some databases like MySQL and Postgres supports comments and [Rails migrations also support adding it](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_column). Some teams follow the good practice of adding comments to new columns or tables whenever creating them. This cops enforces this behaviour, but is disabled by default since this practice may not be widely spread.
PS: If this cop is accepted, I will also create one for table comments
> Add new rails Schema Comment cop

- changelog/change_unmark_autocorrect_false_from_rails_uniq_before_pluck.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
This `AutoCorrect: false` looks like it was set when there was no way to safe autocorrect by `SafeAutocorrect: false`.
Test code for the autocorrection exists. So it can be enabled by default. However, it is still unsafe because `SafeAutocorrect: false`.
> Unmark `AutoCorrect: false` from `Rails/UniqBeforePluck`

- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/uniq_before_pluck.rb
- spec/rubocop/cop/rails/uniq_before_pluck_spec.rb
Follow-up to https://github.com/rubocop/rubocop-rails/pull/580#discussion_r744146536
Removed detection of `distinct` after `pluck`:
```ruby
> User.pluck(:email).distinct
(1.3ms)  SELECT "users"."email" FROM "users"
NoMethodError: undefined method `distinct' for ["user@example.com"]:Array
```
Improved examples and reasoning text.
Unfold specs.
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry …
> Iron out Rails/UniqBeforePluck

- rubocop-rails.gemspec
Follows rubocop/rubocop#10239. Update gemspec to require MFA for privileged operations.
> Set `rubygems_mfa_required` in gemspec

- changelog/change_unmark_autocorrect_false_from_rails_relative_date_constant.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/relative_date_constant.rb
Follow up to https://github.com/rubocop/rubocop/pull/6177.
This `AutoCorrect: false` looks like it was set when there was no way to safe autocorrect by `SafeAutocorrect: false`.
> Change from `AutoCorrect: false` to `SafeAutoCorrect: false` for `Rails/RelativeDateConstant`

- CHANGELOG.md
- changelog/change_add_change_column_check_to_railsreversiblemigration.md
- changelog/change_add_remove_reference_check_to_railsreversiblemigration.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
#591 
`change_column` is not on the [list of the migration definitions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method) supported by the `change` method. This is easy to miss as there are a couple `change_column_*` methods that are supported.
When trying to rollback a migration that uses `change_column` in the `change` method, the rollback will fail.  This change adds the check to `Rails/ReversibleMigration`.
```
➜  $ rubocop -V
1.23.0 (using Parser 3.0.3.1, rubocop-ast 1.13.0, running on ruby 3.0.3 x86_64-darwin20)
- rubocop-performance 1.12.0
- rubocop-rails 2.12.4
- rubocop-rspec 2.5.0
```
[1]: …
> [Fix #591] Add `change_column` check to `Rails/ReversibleMigration`

- Gemfile
This allows adding dev gems e.g. `pry-byebug` without keeping a dirty `Gemfile`.
It's done in RuboCop itself https://github.com/rubocop/rubocop/blob/e919a8c216731fadf12c50d2658f9a67a30c5cc7/Gemfile#L29
Luckily enough, `Gemfile.local` is already in `.gitignore`, so this wasn't needed
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format …
> Allow for Gemfile.local

- changelog/fix_handle_ignored_columns_from_mixins.md
- lib/rubocop/cop/rails/unused_ignored_columns.rb
- spec/rubocop/cop/rails/unused_ignored_columns_spec.rb
Ignored columns can be added from a rails concern. In such cases, Rubocop fails with error as fetching table logic fails.
Before
```
Failure/Error:
def_node_search :find_belongs_to, <<~PATTERN
(send nil? :belongs_to {str sym} ...)
PATTERN
NoMethodError:
undefined method `each_node' for nil:NilClass
```
> Handle ignored_columns from mixins

- changelog/fix_redundant_presence_validation_with_multi_attributes.md
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
- spec/rubocop/cop/rails/redundant_presence_validation_on_belongs_to_spec.rb
> [Fix #603] Teach RedundantPresenceValidationOnBelongsTo to work with multi-attribute validations

- changelog/fix_redundant_presence_validation_with_strict_validation.md
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
- spec/rubocop/cop/rails/redundant_presence_validation_on_belongs_to_spec.rb
> [Fix #608] skip strict validations

- changelog/change_read_write_attribute_to_be_aware_of_shadowed_methods.md
- lib/rubocop/cop/rails/read_write_attribute.rb
- spec/rubocop/cop/rails/read_write_attribute_spec.rb
Sometimes you might want to put a method "in front of" an attribute. In this case, that method will shadow the attribute name, and using `self[:foo]` within the method will be an infinite loop.
**Example:**
```ruby
class Foo < ApplicationModel
attribute :foo
def foo
bar || self[:foo]
end
def bar
nil
end
end
foo = Foo.new(foo: 1)
#=> (irb):11:in `foo': stack level too deep (SystemStackError)
```
This PR makes it so that no offense is registered if `#read_attribute` is used in a method named after that attribute. Same for `#write_attribute` if called inside a writer method (suffix `=`) of the same name.
> Make ReadWriteAttribute cop aware of shadowing methods

- CHANGELOG.md
- changelog/change_remove_remove_reference_checks_from.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
Fixes #604
This removes the new check for `remove_reference` in `Rails/ReversibleMigration` (#592), as well as the recently added check for `remove_belongs_to` - an alias of `remove_reference`.
As discussed in #604, both of these statements are reversible, since their inverse methods are included in [ActiveRecord::Migration::CommandRecorder](https://api.rubyonrails.org/classes/ActiveRecord/Migration/CommandRecorder.html)
It is true that any options that were used in the `add_reference/add_belongs_to` statements need to also be included in the `remove_reference` statement; otherwise, a rollback will not properly restore the schema back to its previous state; however, the same could be said of several other reversible statements, such as `remove_column`.
For example, if I add a column with …
> [Fix #604] Remove `remove_reference` checks from `Rails/ReversibleMigration`

- CHANGELOG.md
In #598 new `Rails/CompactBlank` cop was added,
but there's no entry for it in CHANGELOG.
> Add missing entry to CHANGELOG 

- changelog/change_mark_redundant_presence_validation_on_belongs_to_as_unsafe_autocorrect.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
Fixes #615
Change `Rails/RedundantPresenceValidationOnBelongsTo` to `SafeAutoCorrect: false`
As discussed in #615, this cop's autocorrect is unsafe because it changes the validation error message from "can't be blank" to "must exist". This can break tests and behavior that rely on the error message (such as localizations).
Basing my changes off of #582, I don't believe this requires any test changes, so I've just updated the documentation here.
> [Fix #615] Change Rails/RedundantPresenceValidationOnBelongsTo to SafeAutoCorrect: false

- CHANGELOG.md
- changelog/new_allow_ignoring_scopes_for_inverse_of_cop.md
- config/default.yml
- lib/rubocop/cop/rails/inverse_of.rb
- spec/rubocop/cop/rails/inverse_of_spec.rb
With https://github.com/rails/rails/pull/43358, Rails can now infer
inverse_of for associations with a scope when
`config.active_record.automatic_scope_inversing = true`.
This commit adds an `IgnoreScopes` option to the inverse_of cop allowing
us to disable the cop for scopes when the new Rails option is set to
`true`.
I considered having the default for `IgnoreScopes` change based on the
Rails version since this is the default for new Rails >= 7.0
applications, but existing applications that upgrade to 7.0 wouldn't
necessarily have the option set and in that case changing the
rubocop-rails default behavior would be a breaking change.
[1]: …
> Allow ignoring scopes for inverse_of cop

- lib/rubocop/cop/rails/read_write_attribute.rb
- spec/rubocop/cop/rails/read_write_attribute_spec.rb
This is almost a cosmetic change but I noticed that the cop has almost everything in place to produce a bit more dynamic violation messages to avoid confusions when possible.
So I changed it to build messages based on actual code instead of hardcoded examples.
The only case when I keep the hardcoded message is when the node is multiline. In this case the message was not really readable so I decided to keep it as is
I wonder if we could omit the `over ... ` part because it essentially duplicates the highlighted code ❓ 
> [ReadWriteAttribute] Improve cop message to be more dynamic

- changelog/fix_skip_method_shadowing_check_if_attr_is_non_str_or_sym.md
- lib/rubocop/cop/rails/read_write_attribute.rb
- spec/rubocop/cop/rails/read_write_attribute_spec.rb
Closes https://github.com/rubocop/rubocop-rails/issues/623
Fixes rubocop exceptions like:
```
undefined method `value' for s(:lvar, :column):RuboCop::AST::Node
```
for read/write methods used within a method and using non-string or non-symbol argument names 
for example: 
```ruby
def do_the_read
read_attribute(ATTR_NAME)
end
```
So I decided to skip the "shadowing" check if we can't explicitly know the attribute name.
Later we may want to exclude cases like this because it's also shadowing and should be fairly easy to detect this one. But for now I decided to fix the exception and consider an improvement in a separate PR 
```ruby
def define_date_column_writer(column, value)
define_method("#{column}=") do |value|
write_attribute(column, value)
end
end
```
Before submitting the PR make sure …
> [Fix #623] Skip method shadowing check if attr is not sym or str for ReadWriteAttribute

- changelog/fix_false_positive_for_rails_compact_blank.md
- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
Fixes #626.
Fix a false positive for `Rails/CompactBlank` when using the receiver of `blank?` is not a block variable.
> [Fix #626] Fix a false positive for `Rails/CompactBlank`

- changelog/fix_missing_duration_methods_for_rails_duration_arithmetic.md
- lib/rubocop/cop/rails/duration_arithmetic.rb
- spec/rubocop/cop/rails/duration_arithmetic_spec.rb
`month(s)` and `year(s)` were [inadvertently missed](https://github.com/rubocop/rubocop-rails/pull/571#discussion_r782330604) when implementation `Rails/DurationArithmetic`, so I've added them here! I've also add some additional test coverage to ensure we are accounting for all of these duration arithmetic methods.
> Add months and years to `Rails/DurationArithmetic` cop duration method set

- changelog/fix_a_false_positive_for_rails_redundant_presence_validation_on_belongs_to.md
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
- spec/rubocop/cop/rails/redundant_presence_validation_on_belongs_to_spec.rb
Fixes #620.
This PR fixes a false positive for `Rails/RedundantPresenceValidationOnBelongsTo` using presence with a message ~~and reverts #616 because accept the use case~~.
> [Fix #620] Fix a false positive for `Rails/RedundantPresenceValidationOnBelongsTo`

- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
Fixes #628.
This PR fixes a false positive for `Rails/CompactBlank` when using `collection.reject(&:empty?)`.
`compact_blank`'s implementation targets `blank?` only. `empty?` is irrelevant.
https://github.com/rails/rails/blob/v7.0.1/activesupport/lib/active_support/core_ext/enumerable.rb#L205-L220
> [Fix #628] Fix a false positive for `Rails/CompactBlank`

- changelog/change_update_railspluck_to_be_aware_of.md
- lib/rubocop/cop/rails/pluck.rb
- spec/rubocop/cop/rails/pluck_spec.rb
Fixed `Rails/Pluck` to catch `map { _1[:foo] }`.
> Update `Rails/Pluck` to be aware of numblocks

- docs/modules/ROOT/pages/installation.adoc
Remove confusion with README.md file in the GitHub repo and the official documentation site https://docs.rubocop.org/rubocop-rails/installation.html
> Remove confusing with README.md file

- changelog/fix_bulk_change_table_remove_multiple_columns.md
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
`t.remove` can take multiple columns, so a `change_table` block with a single `t.remove` can still benefit from `bulk: true`.
> Handle t.remove with multiple columns in Rails/BulkChangeTable

- changelog/new_rails_action_controller_test_case_cop.md
- config/default.yml
- lib/rubocop/cop/rails/action_controller_test_case.rb
- lib/rubocop/cop/rails_cops.rb
- spec/rubocop/cop/rails/action_controller_test_case_spec.rb
👋 I wrote a cop recently to list usage of all old controller tests. Essentially, it replaces `ActionController::TestCase` with `ActionDispatch::IntegrationTest`. The actual process of converting between the two test case types is a little more involved, but I think the cop is valuable just to keep track of this tech debt within a codebase. I thought that other developers could possibly benefit from this cop as well. Let me know what you think. Thanks!
Add controller testing cop to discourage use of `ActionController::TestCase`. `ActionDispatch::IntegrationTest` should be used instead to test controllers. See https://api.rubyonrails.org/classes/ActionController/TestCase.html
> Rails discourages the use of functional tests in favor of integration tests (use …
> Add Rails/ControllerTesting cop

- changelog/fix_a_false_positive_for_rails_content_tag.md
- config/default.yml
Fixes #636.
This PR fixes a false positive for `Rails/ContentTag` when using `tag` method in config/puma.rb.
> [Fix #636] Fix a false positive for `Rails/ContentTag`

- changelog/change_make_rails_compact_blank_aware_of_reject_delete_if.md
- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
Fixes #650.
This PR makes `Rails/CompactBlank` aware of `delete_if(&:blank)`.
It is unsafe because `compact_blank!` has different implementations for `Array`, `Hash`, and `ActionController::Parameters`.
`Array#compact_blank!`, `Hash#compact_blank!` are equivalent to `delete_if(&:blank?)`.
`ActionController::Parameters#compact_blank!` is equivalent to `reject!(&:blank?)`.
If the cop makes a mistake, auto-corrected code may get unexpected behavior.
This PR also updates unsafe document about it.
> [Fix #650] Make `Rails/CompactBlank` aware of `delete_if(&:blank)`

- changelog/change_exclude_db_schema_rb_and_db_configuration_namespace_schema_rb_by_default.md
- config/default.yml
- spec/rubocop/rails/inject_spec.rb
Fixes #646.
This PR excludes db/schema.rb and db/[CONFIGURATION_NAMESPACE]_schema.rb by default.
schema.rb will be the only file matched by `*schema.rb` directly under the db directory. So I don't think there is any concern about false positives for plain Rails application.
See: https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application
> [Fix #646] Exclude db/schema.rb and db/[CONFIGURATION_NAMESPACE]_schema.rb by default

- changelog/fix_only_consider_migration_classes_for_migration_class_name.md
- lib/rubocop/cop/rails/migration_class_name.rb
- spec/rubocop/cop/rails/migration_class_name_spec.rb
Adds a fix to #644 when calling using multiple classes inside a migration.
Currently, when using the pattern of redefining ActiveRecord classes inside the migration in order not to depend on the app’s classes:
```rb
class UpdateLocaleOnArticles < ActiveRecord::Migration[6.1]
class Article < ActiveRecord::Base
end
def up
Article.update_all(locale: "fr")
end
end
```
Produces:
```
db/migrate/20211025103032_update_locale_on_articles.rb:4:9: C: [Correctable] Rails/MigrationClassName: Replace with UpdateLocaleOnArticles that matches the file name.
class Article < ActiveRecord::Base
^^^^^^^
```
Which autocorrects to:
```
db/migrate/20211025103032_update_locale_on_articles.rb:4:9: C: [Correctable] Rails/MigrationClassName: Replace with UpdateLocaleOnArticles that matches the file name.
class …
```
> Only consider migration classes for `MigrationClassName`

- changelog/fix_a_false_positive_for_rails_transaction_exit_statement.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
Fixes #658.
This PR fixes a false positive for `Rails/TransactionExitStatement` when `break` is used in `loop` in transactions.
> [Fix #658] Fix a false positive for `Rails/TransactionExitStatement`

- changelog/fix_false_negatives_for_rails_transaction_exit_statement.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
#665 fixed a false positive when `break` is used in a block in transactions.
But it introduced a false negative on `return` or `throw`.
``` ruby
transaction do
loop do
break  # allowed
return # should be detected
throw  # should be detected
end
end
```
This PR does not cover following false positive.
It's too complex to detect. And a bad code I believe (should be extracted to method).
``` ruby
transaction do
catch :foo do
throw :foo if condition1 # false positive -- just exit catch
throw :bar if condition2 # true positive
end
end
```
> Fix a false negative for `Rails/TransactionExitStatement`

- changelog/fix_false_positive_for_rails_transaction_exit_statement.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
Fixes #669.
This PR fixes a false positive for `Rails/TransactionExitStatement` when `return` is used in `rescue`.
> [Fix #669] Fix a false positive for `Rails/TransactionExitStatement`

- changelog/fix_a_false_positive_for_rails_reversible_migration_method_definition.md
- lib/rubocop/cop/rails/reversible_migration_method_definition.rb
- spec/rubocop/cop/rails/reversible_migration_method_definition_spec.rb
Fixes #680.
This PR fixes a false positive for `Rails/ReversibleMigrationMethodDefinition` when using an inner class.
> [Fix #680] Fix a false positive for `Rails/ReversibleMigrationMethodDefinition`

- lib/rubocop-rails.rb
- lib/rubocop/cop/rails/safe_navigation.rb
Fixed as not to break future incompatible cop designations.
Reference: https://github.com/rubocop/rubocop-rspec/pull/1252#discussion_r834361929
~* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~
~* [ ] Added tests.~
~* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~
~* [ ] If this is a new cop, consider making a …
> Fix override RuboCop::Cop::Style::RedundantSelf.autocorrect_incompatible_with without breaking designation of future incompatible cop

- changelog/fix_an_error_for_rails_unused_ignored_columns.md
- lib/rubocop/rails/schema_loader/schema.rb
- spec/rubocop/cop/rails/unused_ignored_columns_spec.rb
Fixes #692.
This PR fixes an error for `Rails/UnusedIgnoredColumns` when using no tables db/schema.rb.
> [Fix #692] Fix an error for `Rails/UnusedIgnoredColumns`

- .circleci/config.yml
- .rubocop.yml
- changelog/change_drop_ruby_2_5_support.md
- lib/rubocop/cop/rails/ignored_skip_action_filter_option.rb
- lib/rubocop/cop/rails/safe_navigation.rb
- rubocop-rails.gemspec
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10577.
> Drop Ruby 2.5 support

- changelog/fix_false_negative_for_transaction_exit_with_rescue.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
The old logic for `in_rescue?` in the `TransactionExitStatement` case missed situations where a transaction contained an exit outside of a rescue. For example:
```ruby
ApplicationRecord.transaction do
return if user.active?
rescue
pass
end
```
This fix adds a new node matcher to find exit statements within the rescue body.
> Fix `TransactionExitStatement` `in_rescue?` Logic

- changelog/new_support_autocorrect_for_rails_deprecated_active_model_errors_methods.md
- config/default.yml
- lib/rubocop/cop/rails/deprecated_active_model_errors_methods.rb
- spec/rubocop/cop/rails/deprecated_active_model_errors_methods_spec.rb
This PR supports auto-correction for `Rails/DeprecatedActiveModelErrorsMethods`.
> Support auto-correction for `Rails/DeprecatedActiveModelErrorsMethods`

- changelog/fix_not_autocrrected_for_rails_duplicate_association.md
- lib/rubocop/cop/rails/duplicate_association.rb
- spec/rubocop/cop/rails/duplicate_association_spec.rb
This PR is fixed not auto-corrected case for `Rails/DuplicateAssociation`
The following problems that could'nt be corrected automatically
when exactly the same association was defined have been resolved.
```ruby
class Post < ApplicationRecord
belongs_to :foo
belongs_to :bar
belongs_to :foo
end
```
> Fix not auto-corrected for `Rails/DuplicateAssociation`

- changelog/new_make_keys_method_aware_of_rails_deprecated_active_model_errors_methods.md
- lib/rubocop/cop/rails/deprecated_active_model_errors_methods.rb
- spec/rubocop/cop/rails/deprecated_active_model_errors_methods_spec.rb
This PR makes `keys` method aware of `Rails/DeprecatedActiveModelErrorsMethods` cop. It can emulate the following Rails's warning.
```console
DEPRECATION WARNING: ActiveModel::Errors#keys is deprecated and will be removed in Rails 6.2.
```
The following is a bad / good example.
```ruby
user.errors.keys.include?(:attr)
user.errors.attribute_names.include?(:attr)
```
> Make `keys` method aware of `Rails/DeprecatedActiveModelErrorsMethods` cop

- changelog/change_enable_action_filter_cop_for_jobs_and_mailers.md
- config/default.yml
They use the same `filter`/`action` API.
* n/a Added tests.
* n/a If this is a new cop, consider making a corresponding update to the [Rails Style Guide](https://github.com/rubocop/rails-style-guide).
> Add jobs & mailers to default `filter`/`action` callbacks cops

- changelog/fix_an_error_when_a_variable_is_passed.md
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes #707.
RuboCop cannot determine whether `dependent` is included if a variable is passed,
but I thought it was fine to leave it as is to register the offense to make people aware of it.
> [Fix #707] Fix an error when a variable is passed to has_many or has_one with double splat

- CHANGELOG.md
- changelog/change_inspect_with_lock_for_rails_transaction_exit_statement_cop.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
`ActiveRecord::Locking::Pessimistic#with_lock` implicitly opens a transaction, so we should inspect this method as well as `ActiveRecord::Transactions#transaction`.
> Rails/TransactionExitStatement - Inspect `#with_lock` method too

- changelog/changelog/fix_recover_ruby_22_code_analysis.md
- lib/rubocop/cop/rails/safe_navigation.rb
- spec/rubocop/cop/rails/safe_navigation_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10644.
Reverts part of https://github.com/rubocop/rubocop/pull/7026.
This PR requires https://github.com/rubocop/rubocop/pull/10644 to pass the build.
> Recover Ruby 2.2 code analysis using `TargetRubyVersion: 2.2`

- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/time_zone_assignment.rb
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- lib/rubocop/rails/schema_loader/schema.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/rails/active_record_callbacks_order_spec.rb
- spec/rubocop/cop/rails/blank_spec.rb
- spec/rubocop/cop/rails/dynamic_find_by_spec.rb
- spec/rubocop/cop/rails/eager_evaluation_log_message_spec.rb
- spec/rubocop/cop/rails/find_by_spec.rb
- spec/rubocop/cop/rails/output_safety_spec.rb
- spec/rubocop/cop/rails/redundant_receiver_in_with_options_spec.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
- spec/rubocop/rails/schema_loader_spec.rb
- "assignement" -> "assignment"
- "indicies" -> "indices"
- "RedndantSelf" -> "RedundantSelf"
- "correcly" -> "correctly"
- "arugment" -> "argument"
- "undersoce"-> "underscore"
- "regesters" -> "registers"
- "whtn" -> "when"
- "ergister" -> "register"
- "redendant" -> "redundant"
- "officense" -> "offense"
- "exitted" -> "exited"
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry …
> Fix some typos

- changelog/fix_an_error_for_rails_deprecated_active_model_errors_methods.md
- lib/rubocop/cop/rails/deprecated_active_model_errors_methods.rb
- spec/rubocop/cop/rails/deprecated_active_model_errors_methods_spec.rb
Fixes #717.
This PR fixes an error for `Rails/DeprecatedActiveModelErrorsMethods` when root receiver is a variable.
> [Fix #717] Fix an error for `Rails/DeprecatedActiveModelErrorsMethods`

- changelog/fix_include_value_in.md
- config/default.yml
Include value in AttributeDefaultBlockValue is incorrect, so i fix it. 
(Although it has already been reported on https://github.com/rubocop/rubocop-rails/pull/339#issuecomment-933968162)
> Fix include value in `Rails/AttributeDefaultBlockValue`

- changelog/fix_a_false_negative_for_rails_to_formatted_s.md
- lib/rubocop/cop/rails/to_formatted_s.rb
- spec/rubocop/cop/rails/to_formatted_s_spec.rb
Fixes #719.
This PR fixes a false negative for `Rails/FormattedS` when using safe navigation operator.
> [Fix #719] Fix a false negative for `Rails/FormattedS`

- changelog/fix_an_incorrect_autocorrect_for_rails_dot_separated_keys.md
- lib/rubocop/cop/rails/dot_separated_keys.rb
- spec/rubocop/cop/rails/dot_separated_keys_spec.rb
Fixes #725.
This PR fixes an incorrect autocorrect for `Rails/DotSeparatedKeys` when a key starts with dot.
> [Fix #725] Fix an incorrect autocorrect for `Rails/DotSeparatedKeys`

- spec/rubocop/cop/rails/active_record_aliases_spec.rb
- spec/rubocop/cop/rails/delegate_spec.rb
While working on a fix for #712 I've noticed that the specs of Rails/Delegate use the old-fashioned auto-correction validation. I've updated everywhere that it doesn't make sense to use `autocorrect_source` (some cops still use it as they have additional specs on the correction and there is little gain in concerting those; and others because of the shared_examples usage)
> Update specs to use the expect_correction helper

- changelog/fix_fix_an_incorrect_autocorrect_for_strip_heredoc.md
- lib/rubocop/cop/rails/strip_heredoc.rb
- spec/rubocop/cop/rails/strip_heredoc_spec.rb
Fixes #731 
This PR fixes an incorrect autocorrect for Rails/StripHeredoc when squiggly already present
> [Fix #731] Fix an incorrect autocorrect for Rails/StripHeredoc

- changelog/fix_false_negative_when_nested_classes_has_private_or_protected_methods.md
- lib/rubocop/cop/rails/delegate.rb
- spec/rubocop/cop/rails/delegate_spec.rb
Reusing RuboCop's `VisibilityHelp` we no longer check preceding source lines for a visibility modifier, but the preceding nodes. Fixes #712 
> [Fix #712] Fixed false negative when visibility modifier is declared in nested class

- changelog/fix_false_negative_for_rails_expanded_date_range.md
- lib/rubocop/cop/rails/expanded_date_range.rb
- spec/rubocop/cop/rails/expanded_date_range_spec.rb
This PR makes `Rails/ExpandedDateRange` aware `beginning_of_week` with an argument.
```ruby
date.beginning_of_week(:sunday)..date.end_of_week(:sunday)
date.all_week(:sunday)
```
> Make `Rails/ExpandedDateRange` aware `beginning_of_week` with an argument

- changelog/fix_deprecated_errors_nil_dereference.md
- lib/rubocop/cop/rails/deprecated_active_model_errors_methods.rb
- spec/rubocop/cop/rails/deprecated_active_model_errors_methods_spec.rb
Fixes for Rails/DeprecatedActiveModelErrorsMethods:
- Fixed a NoMethodError on nil for `errors.keys` in a model.
- Made the range calculation more exact so the replacement is easier.
- Added missing correction assertions to most test cases.
- Added missing test cases.
- Improved test structure for future changes.
> Fix a NoMethodError for `errors.keys` in a model

- changelog/fix_deprecated_errors_bad_details_autocorrection.md
- lib/rubocop/cop/rails/deprecated_active_model_errors_methods.rb
- spec/rubocop/cop/rails/deprecated_active_model_errors_methods_spec.rb
Fixes for Rails/DeprecatedActiveModelErrorsMethods:
- Fixed a bad autocorrection of `errors.details[:name] << value`.
There isn't really a correct replacement for this one.
- Did some refactors prompted by rubocop complaints.
- Fixed a misspelling of autocorrectable.
- Added missing correction assertions to test cases.
> No correction for `errors.details[:n] << v`

- changelog/change_rubocop_dependency_version.md
- lib/rubocop/cop/rails/add_column_index.rb
- lib/rubocop/cop/rails/dot_separated_keys.rb
- lib/rubocop/cop/rails/redundant_foreign_key.rb
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
- rubocop-rails.gemspec
As https://github.com/rubocop/rubocop/pull/10748 allows
The CI will be red until the above PR is not merged and released
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
[1]: …
> Pass range as a positional arg

- changelog/fix_fix_railscompactblank_bug_when_offense.md
- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
I ran autocorrection of `Rails/CompactBlank` to my code and confirmed that the code is converted as follows:
```diff
-hash.transform_values { |value| value.reject(&:blank?) }
+hash.transform_values { |value| value.compact_blank
```
It appears that the offense range is incorrect.
```
hash.transform_values { |value| value.reject(&:blank?) }
^^^^^^^^^^^^^^^^^^ Use `compact_blank` instead.
```
Both the `.reject` call within a block and the `.reject` call with a block have a block node in the parent, so I think it's not sufficient to simply check whether the parent is a `block_type?`.
```console
$ cat example.rb 
a { b.reject(&:blank?) }
c.reject! { |d| d.blank? }
$ ruby-parse example.rb 
(begin
(block
(send nil :a)
(args)
(send
(send nil :b) :reject
(block-pass
(sym :blank?))))
(block
(send …
```
> Fix `Rails/CompactBlank` bug when offense is found in block

- changelog/change_deprecate_ignore_methods_parameter.md
- config/default.yml
- config/obsoletion.yml
- lib/rubocop/cop/rails/find_each.rb
- rubocop-rails.gemspec
- spec/rubocop/cop/rails/find_each_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10829.
This PR deprecates `IgnoredMethods` option in integrate to `AllowedMethods` and `AllowedPatterns` option.
It requires RuboCop 1.33.0 or higher.
> Deprecate `IgnoredMethods` option

- .rubocop_todo.yml
- changelog/fix_make_redundant_receiver_in_with_options_and_reversible_migration_aware_of_numblock.md
- lib/rubocop/cop/mixin/index_method.rb
- lib/rubocop/cop/rails/action_filter.rb
- lib/rubocop/cop/rails/rake_environment.rb
- lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/redundant_receiver_in_with_options_spec.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
This PR Make `Rails/RedundantReceiverInWithOptions` and `Rails/ReversibleMigration` cops aware of numbered block parameter.
`Rails/ActionFilter` and `Rails/RakeEnvironment` cops have block arguments, so numblock operation is unnecessary.
`Rails/IndexBy` and `Rails/IndexWith` cops is a slightly more complicated operation using multiple block arguments.
It'll take care of it another time using `rubocop:todo` comment because I think it's a really rare case.
> Make `Rails/RedundantReceiverInWithOptions` and `Rails/ReversibleMigration` aware of numblock

- changelog/new_add_railsactioncontrollerflashbeforerender.md
- config/default.yml
- lib/rubocop/cop/rails/action_controller_flash_before_render.rb
- lib/rubocop/cop/rails_cops.rb
- spec/rubocop/cop/rails/action_controller_flash_before_render_spec.rb
This PR suggests a new Cop for detecting `flash` assignment before `render` a page (the correct approach would be to assign a message to `flash.now` ([check on rails guides](https://guides.rubyonrails.org/action_controller_overview.html#flash-now)) .
This is a common mistake in Ruby on Rails, and it is easy to fall into this trap the flash will be rendered on the page. But the flash message still persisted and will show up on the following redirect.
This is an example of that issue: https://github.com/rubygems/rubygems.org/issues/3149
Solved here: https://github.com/rubygems/rubygems.org/pull/3198
This is a very simple version but helped me to find more 6 issues on that project.
I hope I can receive some suggestions on how to improve this solution.
Before submitting the …
> Add `Rails/ActionControllerFlashBeforeRender` cop

- .rubocop_todo.yml
- changelog/fix_a_false_positive_for_rails_reflection_class_name.md
- lib/rubocop/cop/rails/reflection_class_name.rb
- spec/rubocop/cop/rails/reflection_class_name_spec.rb
Fixes #757.
This PR fixes a false positive for `Rails/ReflectionClassName` when using Ruby 3.1's hash shorthand syntax.
> [Fix #757] Fix a false positive for `Rails/ReflectionClassName`

- changelog/fix_an_error_for_rails_freeze_time.md
- lib/rubocop/cop/rails/freeze_time.rb
- spec/rubocop/cop/rails/freeze_time_spec.rb
Fixes #762.
This PR fixes an error for `Rails/FreezeTime` when using `travel_to` with an argument of `current` method without receiver.
> [Fix #762] Fix an error for `Rails/FreezeTime`

- changelog/fix_an_incorrect_autocorrect_for_rails_freeze_time.md
- lib/rubocop/cop/rails/freeze_time.rb
- spec/rubocop/cop/rails/freeze_time_spec.rb
Fixes #764.
This PR fixes an incorrect autocorrect for `Rails/FreezeTime` when using `travel_to` with an argument of the current time and proc argument.
> [Fix #764] Fix an incorrect autocorrect for `Rails/FreezeTime`

- changelog/fix_an_incorrect_autocorrect_for_rails_root_pathname_methods.md
- config/default.yml
- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
Fixes #763.
This PR fix a false positive for `Rails/RootPathnameMethods` when using `Dir.glob`. And marks unsafe for autocorrection because `Dir`'s methods return string element, but `Pathname`'s methods return `Pathname` element.
> [Fix #763] Fix a false positive for `Rails/RootPathnameMethods`

- changelog/fix_a_false_positive_for_rails_freeze_time.md
- lib/rubocop/cop/rails/freeze_time.rb
- spec/rubocop/cop/rails/freeze_time_spec.rb
Fixes #769.
This PR fixes a false positive for `Rails/FreezeTime` when using `travel_to` with an argument of `DateTime.new` with arguments.
> [Fix #769] Fix a false positive for `Rails/FreezeTime`

- changelog/fix_a_false_positive_for_rails_top_level_hash_with_indifferent_access.md
- lib/rubocop/cop/rails/top_level_hash_with_indifferent_access.rb
- spec/rubocop/cop/rails/top_level_hash_with_indifferent_access_spec.rb
This PR fixes a false positive for `Rails/TopLevelHashWithIndifferentAccess` when using `HashWithIndifferentAccess` under namespace module.
> Fix a false positive for `Rails/TopLevelHashWithIndifferentAccess`

- changelog/fix_an_incorrect_autocorrect_for_rails_presence.md
- lib/rubocop/cop/rails/presence.rb
- spec/rubocop/cop/rails/presence_spec.rb
Fixes #776.
This PR fixes an incorrect autocorrect for `Rails/Presence` when using arithmetic operation in `else` branch.
> [Fix #776] Fix an incorrect autocorrect for `Rails/Presence`

- changelog/fix_an_incorrect_autocorrect_for_rails_eager_evaluation_log_message.md
- lib/rubocop-rails.rb
- lib/rubocop/cop/rails/eager_evaluation_log_message.rb
- spec/rubocop/cli/autocorrect_spec.rb
Fixes #782.
This PR fixes an incorrect autocorrect for `Rails/EagerEvaluationLogMessage` when using `Style/MethodCallWithArgsParentheses`'s autocorrection together.
> [Fix #782] Fix an incorrect autocorrect for `Rails/EagerEvaluationLogMessage`

- changelog/fix_a_false_negative_for_rails_action_controller_test_case.md
- lib/rubocop/cop/rails/action_controller_test_case.rb
- spec/rubocop/cop/rails/action_controller_test_case_spec.rb
Fixes #786.
This PR fixes a false negative for `Rails/ActionControllerTestCase` when extending `ActionController::TestCase` and having a method definition.
> [Fix #786] Fix a false negative for `Rails/ActionControllerTestCase`

- lib/rubocop/cop/rails/find_each.rb
- spec/rubocop/cop/rails/find_each_spec.rb
This PR is fix a wrong AllowedPatterns example in `Rails/FindEach` When specifying in the .rubocop.yml file, it is necessary to specify `AllowedPatterns: ['foo']` instead of `AllowedPatterns: [/foo/]`.
Follow up: https://github.com/rubocop/rubocop-rspec/issues/1395
The test code was also modified to match the actual behavior as mentioned in https://github.com/rubocop/rubocop-rspec/pull/1396#issuecomment-1257026847 .
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable …
> Fix a wrong AllowedPatterns example in `Rails/FindEach`

- changelog/fix_a_false_positive_for_rails_dynamic_find_by.md
- config/default.yml
- lib/rubocop/cop/rails/dynamic_find_by.rb
Fixes #781.
This PR makes `Rails/DynamicFindBy` aware of `find_by_token_for`. This default setting emphasizes suppressing false positive over false negative. `find_by_token_for` is probably rarely named, but it will always exist in Rails in the future.
> [Fix #781] Fix a false positive for `Rails/DynamicFindBy`

- spec/rubocop/cop/rails/file_path_spec.rb
CI seems to have failed because rubocop/rubocop#11002 was merged. (e.g. https://github.com/rubocop/rubocop-rails/pull/771/commits/2723be419d88169aee34ca64865411a3b2ab5300)
This commit is for fixing it.
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
* [-] If this is a new cop, consider making a corresponding update to the [Rails …
> Fix test case in file_path_spec.rb for `Style/RedundantStringEscape`

- changelog/fix_false_positive_for_rails_dynamic_find_by.md
- config/default.yml
- lib/rubocop/cop/rails/dynamic_find_by.rb
Fixes #778.
This PR fixes a false positive for `Rails/DynamicFindBy` when using `page.find_by_id` as a Capybara testing API. This default setting emphasizes suppressing false positive over false negative.
> [Fix #778] Fix a false positive for `Rails/DynamicFindBy`

- changelog/change_make_rails_pluck_aware_of_all_keys.md
- lib/rubocop/cop/rails/pluck.rb
- spec/rubocop/cop/rails/pluck_spec.rb
Fixes #787.
This PR makes `Rails/Pluck` aware of all keys.
> [Fix #787] Make `Rails/Pluck` aware of all keys

- changelog/fix_an_error_for_rails_redundant_receiver_in_with_option.md
- lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb
- spec/rubocop/cop/rails/redundant_receiver_in_with_options_spec.rb
Fixes #794.
This PR fixes an error for `Rails/RedundantReceiverInWithOptions` when calling a method with a receiver in `with_options` without block arguments
> [Fix #794] Fix an error for `Rails/RedundantReceiverInWithOptions`

- changelog/change_make_rails_time_zone_aware_of_timezone_offset.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
Fixes #800
This PR makes `Rails/TimeZone` aware of timezone UTC offset.
> [Fix #800] Make `Rails/TimeZone` aware of timezone offset

- changelog/new_action_order_cop.md
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/action_order.rb
- lib/rubocop/cop/rails_cops.rb
- spec/rubocop/cop/rails/action_order_spec.rb
Please excuse any obvious mistakes, this is my first cop.
Fix #540
> Action Order Cop

- changelog/change_add_several_dir_to_exclude_to_prevent_slow_investigation.md
- config/default.yml
Fixes #796.
This PR adds several directories to `Exclude` to prevent slow investigation. These directories (`log`, `public`, and `storage`) provided by `bin/rails` are expected not to contain Ruby code. And `tmp` and `vendor` directories have already been excluded in the RuboCop core.
https://github.com/rubocop/rubocop/blob/v1.36.0/config/default.yml#L65-L66
> [Fix #796] Add several directories to `Exclude`

- changelog/fix_errors_that_occur_when_unrelated_tag.md
- lib/rubocop/cop/rails/content_tag.rb
- spec/rubocop/cop/rails/content_tag_spec.rb
I encountered a strange error when running rubocop-rails on our Rails app that uses FactoryBot.
The file that caused the problem was, in simplified form, the following code:
```ruby
FactoryBot.define do
factory :article do
tag factory: :article_tag
end
end
```
and the error output was like this:
```
$ bundle exec rubocop spec/factories/articles.rb 
An error occurred while Rails/ContentTag cop was inspecting /workspace/spec/factories/articles.rb:3:4.
To see the complete backtrace run rubocop -d.
.
1 file inspected, no offenses detected
1 error occurred:
An error occurred while Rails/ContentTag cop was inspecting /workspace/spec/factories/articles.rb:3:4.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker. …
```
> Fix errors that occur when unrelated `tag` is investigated by `Rails/ContentTag`

- changelog/fix_an_error_for_rails_freeze_time.md
- lib/rubocop/cop/rails/freeze_time.rb
- spec/rubocop/cop/rails/freeze_time_spec.rb
Fixes #809.
This PR fixes an error for `Rails/FreezeTime` when using `travel_to` without argument.
> [Fix #809] Fix an error for `Rails/FreezeTime`

- changelog/fix_a_false_negative_for_rails_redundant_presence_validation_on_belongs_to.md
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
- spec/rubocop/cop/rails/redundant_presence_validation_on_belongs_to_spec.rb
Fix a false negative for `Rails/RedundantPresenceValidationOnBelongsTo` when belongs_to have one block and one hash like `belongs_to :company, -> { where(foo: true) }, inverse_of: :employee`
* [ x Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
> [Fix #792] Fixes a false negative for Rails/RedundantPresenceValidationOnBelongsTo

- lib/rubocop/cop/rails/presence.rb
- spec/rubocop/cop/rails/presence_spec.rb
Similar issue: https://github.com/rubocop/rubocop/pull/10784
Before
```diff
if a.present?
+^^^^^^^^^^^^^ Use `a.presence || b.to_f * 12.0` instead of `if a.present?
+  a
+else
+  b
+end`.
a
else
b
end
```
After
```diff
if a.present?
+^^^^^^^^^^^^^ Use `a.presence || b` instead of `if a.present? ... end`.
a
else
b
end
```
> Preserve multiline semantics on `Rails/Presence`

- changelog/change_add_mail_to_allowed_methods_of_style_symbol_proc.md
- config/default.yml
Fixes #779.
This PR adds `mail` to `AllowedMethods` of `Style/SymbolProc`. `define_methods` and `respond_to` inherit from RuboCop core.
> [Fix #779] Add `mail` to `AllowedMethods` of `Style/SymbolProc`

- changelog/change_extends_http_status_to_detect_redirect_routes.md
- lib/rubocop/cop/rails/http_status.rb
- spec/rubocop/cop/rails/http_status_spec.rb
Fixes #822.
This PR extends [`Rails/HttpStatus`](https://github.com/rubocop/rubocop-rails/blob/master/lib/rubocop/cop/rails/http_status.rb) cop to detects offenses in `routes.rb` on redirections:
```ruby
Rails.application.routes.draw do
get '/foobar', to: redirect('/foobar/baz', status: 301)
end
```
> [Fix #822] Extends `Rails/HttpStatus` cop to check `routes.rb`

- spec/support/file_helper.rb
This is in response to the following change:
- https://github.com/rubocop/rubocop/pull/11109
This repository refers to rubocop/rubocop on GitHub and does not stage Gemfile.lock in Git index, so if a cop that detects offenses to existing code is added on rubocop gem side,  the CI on rubocop-rails gem side will start to fail from that point on.
https://github.com/rubocop/rubocop-rails/blob/f913bb517e38849e7318055d93bfecbdb6b4db20/Gemfile#L12
I ran into this problem when I created the following Pull Request, so I decided to create this Pull Request too.
- https://github.com/rubocop/rubocop-rails/pull/827
- https://app.circleci.com/pipelines/github/rubocop/rubocop-rails/2069/workflows/84921743-0ec3-45af-aea8-ef00aa7d85e6/jobs/13915
Before submitting the PR make sure the …
> Ignore `InternalAffairs/CreateEmptyFile` in `#create_empty_file`

- changelog/change_revert_merge_pull_request_823_from.md
- lib/rubocop/cop/rails/http_status.rb
- spec/rubocop/cop/rails/http_status_spec.rb
This reverts commit e40d8b9e41daba64364b23df469d534383804951, reversing changes made to 6051ed83c97e99c008fa9d5c91ed5955d915c804.
The auto-corrected code is not compatible with Rails/Puma, resulting the error:
Puma caught this error: undefined method `to_i' for :moved_permanently:Symbol
status = status.to_i
^^^^^
Did you mean?  to_s (NoMethodError)
/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/request.rb:82:in `handle_request'
/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Before …
> Revert "Merge pull request #823 from anthony-robin/http-status-routes"

- changelog/fix_a_false_positive_for_rails_pluck.md
- lib/rubocop/cop/rails/pluck.rb
- spec/rubocop/cop/rails/pluck_spec.rb
This PR fixes a false positive for `Rails/Pluck`
when using block argument in `[]` to prevent the following incompatible autocorrect.
```diff
-x.collect { |a| a[foo...a.to_someghing] }
+x.pluck(foo...a.to_someghing)
```
The `a` is not defined in the autocorrected code.
> Fix a false positive for `Rails/Pluck`

- changelog/fix_a_false_positive_for_rails_action_controller_flash_before_render.md
- lib/rubocop/cop/rails/action_controller_flash_before_render.rb
- spec/rubocop/cop/rails/action_controller_flash_before_render_spec.rb
Fixes #825.
This PR fixes a false positive for `Rails/ActionControllerFlashBeforeRender` when using condition before `redirect_to`.
> [Fix #825] Fix a false positive for `Rails/ActionControllerFlashBeforeRender`

- changelog/fix_a_false_positive_for_rails_action_controller_flash_before_render.md
- lib/rubocop/cop/rails/action_controller_flash_before_render.rb
- spec/rubocop/cop/rails/action_controller_flash_before_render_spec.rb
Fixes #843.
This PR fixes a false positive for `Rails/ActionControllerFlashBeforeRender` when using `flash` in multiline `if` branch before `redirect_to`.
> [Fix #843] Fix a false positive for `Rails/ActionControllerFlashBeforeRender`

- changelog/fix_an_incorrect_autocorrect_for_rails_action_order.md
- lib/rubocop/cop/rails/action_order.rb
- spec/rubocop/cop/rails/action_order_spec.rb
Fixes #838.
This PR fixes an incorrect autocorrect for `Rails/ActionOrder` when using unconventional order of actions in conditions.
> [Fix #838] Fix an incorrect autocorrect for `Rails/ActionOrder`

- changelog/fix_railsrootpathnamemethods.md
- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
```ruby
file = File.open Rails.root.join 'spec', 'fixtures', 'pdfs', 'read_only.pdf'
file = Rails.root.join 'spec', 'fixtures', 'pdfs', 'read_only.pdf'.open
```
This autocorrection is invalid Ruby code. We can avoid it if we parenthesize `Pathname` methods before chaining like so:
```
file = Rails.root.join('spec', 'fixtures', 'pdfs', 'read_only.pdf').open
```
> Fix Rails/RootPathnameMethods autocorrection for Pathname calls without parens

- changelog/fix_incorrect_autocorrection_of_rails_action_order.md
- lib/rubocop/cop/rails/action_order.rb
- spec/rubocop/cop/rails/action_order_spec.rb
This change fixes the following Issue by extending the `Parser::Source::Range` used for replacement to include comment lines.
- Fix #837
I encountered a problem with `Rails/ActionOrder` Cop autocorrection where comments were not corrected properly.
```ruby
class FooController < ApplicationController
def show; end
def index; end
end
```
```ruby
class FooController < ApplicationController
def index; end
def show; end
end
```
```ruby
class FooController < ApplicationController
def index; end
def show; end
end
```
When creating this Pull Request, I confirmed that a similar issue had already been reported, so I decided to tie it.
> [Fix #837] Fix incorrect autocorrection of `Rails/ActionOrder` about comments

- changelog/fix_false_positive_for_rails_freeze_time.md
- lib/rubocop/cop/rails/freeze_time.rb
- spec/rubocop/cop/rails/freeze_time_spec.rb
Fixes #848.
This PR fixes a false positive for `Rails/FreezeTime` when using `travel_to` with an argument of `Time.new(...).in_time_zone`.
> [Fix #848] Fix a false positive for `Rails/FreezeTime`

- changelog/fix_i18n_lazy_lookup_configuration.md
- config/default.yml
- lib/rubocop/cop/rails/i18n_lazy_lookup.rb
Currently, `Rails/I18nLazyLookup` is a no-op out of the box because its default path is set incorrectly (`controllers` instead of `app/controllers`)
The cop is also missing `RESTRICT_ON_SEND` which makes it inefficient.
This PR fixes these issues.
> Fix default configuration for Rails/I18nLazyLookup

- changelog/fix_an_error_for_rails_action_order.md
- lib/rubocop/cop/rails/action_order.rb
- spec/rubocop/cop/rails/action_order_spec.rb
Fixes #841.
This PR fixes an error for `Rails/ActionOrder` when using unconventional order of multiple actions.
With this change, autocorrection blank line positions are not as expected, so they are left to autocorrection of `Layout/EmptyLineBetweenDefs` and `Layout/EmptyLinesAroundClassBody` cops.
This PR aims to fix the error, that it may be a better autocorrection later.
> [Fix #841] Fix an error for `Rails/ActionOrder`

- lib/rubocop/cop/rails/content_tag.rb
I created the following Pull Request and CI failed unexpectedly:
- https://github.com/rubocop/rubocop-rails/pull/863
I checked and found that it succeeds with rubocop 1.37, but fails with rubocop 1.38. So, I ran `rubocop --autocorrect` with rubocop 1.38 to fix it.
> Fix an offense on `Style/RedundantRegexpEscape`

- changelog/change_ignore_if_number_of_arguments_does_not_match.md
- lib/rubocop/cop/rails/dynamic_find_by.rb
- spec/rubocop/cop/rails/dynamic_find_by_spec.rb
If the number of arguments does not match with its method name, it means that dynamic `find_by` is not used, but a user-defined method is used, so I think it should not be an offense in this case. What do you think?
```ruby
Model.find_by_a_and_b(a)
Model.find_by_x(y, z)
```
> Ignore if number of arguments does not match on `Rails/DynamicFindBy`

- changelog/fix_support_rails_and_file_on_rails_file_path.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
`Rails/FilePath` does not work as intended when `cbase` is used, as in `::Rails.root.join` or `::File.join`.
> Support `::Rails` and `::File` on `Rails/FilePath` cop

- changelog/fix_autocorrection_bug_when_hash_is_used_on.md
- lib/rubocop/cop/mixin/index_method.rb
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
The following 2 cops currently support both `Hash[...] ` and `::Hash[...] `, but the autocorrection for `::Hash[...] ` yields incorrect result. This is because it assumes only `Hash[` and removes the first 5 characters from source code.
- `Rails/IndexBy`
- `Rails/IndexWith`
This problem was originally found at the following Pull Request:
- https://github.com/rubocop/rubocop-rails/pull/866#discussion_r1021050989
> Fix autocorrection bug when `::Hash` is used on `Rails/IndexBy` and `Rails/IndexWith`

- changelog/fix_false_positives_that_non_rails_formats.md
- lib/rubocop/cop/rails/to_s_with_argument.rb
- spec/rubocop/cop/rails/to_s_with_argument_spec.rb
We had `Rails/ToSWithArgument` Cop to replace `to_s` with `to_fs` where Rails' extended functionality is used, but there are frequent false-positives where `to_s` is used with non Rails extended formats like `value.to_s(2)` (`Integer#to_s`).
To prevent this, it would be better to check its 1st argument so that only cases that appear to use Rails-extended functionality are offended.
> Fix false-positives that non Rails formats are offended on `Rails/ToSWithArgument`

- changelog/fix_an_error_for_rails_root_pathname_methods.md
- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
Fixes #870.
This PR fixes an error for `Rails/RootPathnameMethods` when using `Rails.env` argument within `Dir.glob`.
> [Fix #870] Fix an error for `Rails/RootPathnameMethods`

- changelog/fix_make_rails_root_pathname_methods_aware_of_style_string_literals.md
- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
Follow up https://github.com/rubocop/rubocop-rails/pull/872#discussion_r1029972604.
This PR makes `Rails/RootPathnameMethods` aware of enforced style of `Style/StringLiterals`.
> Make `Rails/RootPathnameMethods` aware of enforced style of `Style/StringLiterals`

- changelog/fix_time_zone_to_accept_in_option.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
Closes #821.
`Time.{now,at,new}` were extended with the supported `:in` timezone option.
> Enhance `Rails/TimeZone` to accept methods with the `:in` timezone option

- changelog/change_add_i18nlocaletext_match_for_redirect_back.md
- lib/rubocop/cop/rails/i18n_locale_texts.rb
- spec/rubocop/cop/rails/i18n_locale_texts_spec.rb
`Rails/I18nLocaleTexts` was introduced in #643 and matches on `redirect_to`; this PR extends the cop to also match on the similarly behaved `redirect_back` method.
> Add Rails/I18nLocaleTexts match for `redirect_back`

- changelog/fix_support_conditions_option_of.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
First, a validation can be defined with options specific to the validator:
```ruby
class Article < ApplicationRecord
validates :user, uniqueness: { if: -> { false } }
end
```
And this should not add an offense, like when the `:if` is on the `validates`, because we don't know what the condition is and it could lead to a false positive.
Secondly, there's a `:conditions` option that can't be added on `validates` directly because it's specific to the `UniquenessValidator`, which can also lead to false positives, because it can refer to columns or otherwise reduce the uniqueness in a way that prevents a unique index from covering it in the schema.
> Fix false positive in UniquenessValidator with `conditions`

- changelog/fix_fix_a_false_positive_for_rails_where_missing.md
- lib/rubocop/cop/rails/where_missing.rb
- spec/rubocop/cop/rails/where_missing_spec.rb
This PR is fix a false positive for `Rails/WhereMissing` when `left_joins(:foo)` and `where(foos: {id: nil})` separated by `or`, `and`.
It is necessary to consider the following cases, which are separated by `or` or `and`.
```ruby
Foo.left_joins(:foo).or(Foo.where(foos: {id: nil}))
Foo.where(foos: {id: nil}).and(Foo.left_joins(:foo))
```
> Fix a false positive for `Rails/WhereMissing` when `left_joins(:foo)`and `where(foos: {id: nil})` separated by `or`, `and`

- changelog/fix_a_false_positive_for_rails_active_record_aliases.md
- lib/rubocop/cop/rails/active_record_aliases.rb
- spec/rubocop/cop/rails/active_record_aliases_spec.rb
Fixes #898.
This PR fixes a false positive for `Rails/ActiveRecordAliases` when arguments of `update_attributes` is empty.
> [Fix #898] Fix a false positive for `Rails/ActiveRecordAliases`

- changelog/change_ignore_redirect_method_for_style_format_string_token.md
- config/default.yml
This adds the `redirect` method as a default for the Style/FormatStringToken rule due to the change in https://github.com/rubocop/rubocop/pull/9369 where it was mentioned that it would be added as a default but since it wasn't, I'm contributing the change. I ran into this false positive with a rails route using both rubocop and rubocop-rails. Seems like a good default to have, if still desired.
> Ignore redirect method for Style/FormatStringToken by default

- changelog/fix_unused_ignored_columns_plus_equals.md
- lib/rubocop/cop/rails/unused_ignored_columns.rb
- spec/rubocop/cop/rails/unused_ignored_columns_spec.rb
[`Rails/IgnoredColumnsAssignment`](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsignoredcolumnsassignment) recommends adding to `ignored_columns` via `+=`, rather than simple assignment, but the `+=` syntax isn't recognized by [`Rails/UnusedIgnoredColumns`](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsunusedignoredcolumns).
This PR fixes `Rails/UnusedIgnoredColumns` to work with `+=`.
> Fix UnusedIgnoredColumns detection when using +=

- changelog/fix_not_null_column_to_accept_virtual_columns.md
- lib/rubocop/cop/rails/not_null_column.rb
- spec/rubocop/cop/rails/not_null_column_spec.rb
Fixes #887.
From [documentation](https://www.postgresql.org/docs/current/ddl-generated-columns.html):
> Several restrictions apply to the definition of generated columns and tables involving generated columns:
>  - A generated column cannot have a column default or an identity definition.
> Fix a false positive for `Rails/NotNullColumn` when adding a `:virtual` column

- changelog/change_raise_severity_of_some_cops_to_warning.md
- config/default.yml
The cops below belong to linting, not style preference, so make set the severity to warning.
The following emulates warnings for deprecated APIs:
- Rails/DeprecatedActiveModelErrorsMethods
- Rails/TopLevelHashWithIndifferentAccess
- Rails/WhereNotWithMultipleConditions
The following suggests incorrect usage of APIs:
- Rails/ActiveRecordOverride
- Rails/DuplicateAssociation
- Rails/DuplicateScope
> Raise severity of some cops to warning

- changelog/fix_set_minimum_target_rails_version_for_freeze_time.md
- lib/rubocop/cop/rails/freeze_time.rb
- spec/rubocop/cop/rails/freeze_time_spec.rb
`freeze_time` wasn't added until Rails 5.2, so running this cop against a Rails <= 5.1 app returns inaccurate offenses.
I have:
- Added specs and confirmed failures. 
- Set `minimum_target_rails_version` to `5.2` in  the `Rails/FreezeTime` Cop.
- Reran specs and confirmed no failures.
- Added a changelog entry
> Don't use FreezeTime cop in Rails <5.2

- changelog/fix_error_for_negate_include_without_receiver.md
- lib/rubocop/cop/rails/negate_include.rb
- spec/rubocop/cop/rails/negate_include_spec.rb
This PR fixes an error when there is no receiver. And handles the case when it is used within `exclude?` method (because correcting would cause infinite recursion).
Example from rails: https://github.com/rails/rails/blob/d75fdd1c2f6002d62e5ecf65dda2942065f071f0/activesupport/lib/active_support/core_ext/string/exclude.rb#L10-L12
> Fix an error for `Rails/NegateInclude` when there is no receiver

- changelog/fix_has_many_or_has_one_dependent_receiver.md
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
> Fix `Rails/HasManyOrHasOneDependent` to correctly handle association methods with receiver

- changelog/fix_invalid_squish_sql_heredoc.md
- lib/rubocop/cop/rails/squished_sql_heredocs.rb
- spec/rubocop/cop/rails/squished_sql_heredocs_spec.rb
Removes all strings and identifiers from the SQL and then checks it for single-comment markers, and does not apply the cop if they are present
> Only apply SquishSQLHeredoc when the SQL has no comments

- changelog/change_accept_actions_defined_via_alias_in_lexically_scoped_action_filter.md
- lib/rubocop/cop/rails/lexically_scoped_action_filter.rb
- spec/rubocop/cop/rails/lexically_scoped_action_filter_spec.rb
> Accept actions defined via `alias` in `Rails/LexicallyScopedActionFilter`

- changelog/fix_error_in_rails_presence_when_ternary.md
- lib/rubocop/cop/rails/presence.rb
- spec/rubocop/cop/rails/presence_spec.rb
When I run rubocop-rails against the following code, I get an error from `Rails/Presence` cop.
```ruby
a.present? ?
a :
b
```
After investigation, I have identified the problem and would like to fix it.
> Fix error in `Rails/Presence` when ternary operators are used in multiple lines

- .rubocop.yml
- changelog/change_make_style_inverse_methods_aware_of_active_support_methods.md
- config/default.yml
- lib/rubocop/rails.rb
This PR makes `Style/InverseMethods` aware of Active Support's `present?`, `blank?`, `include?`, and `exclude?` methods.
These methods are based on the following setting:
https://github.com/rubocop/rubocop/blob/v1.45.0/config/default.yml#L4030-L4033
> Make `Style/InverseMethods` aware of some Active Support methods

- changelog/change_make_style_inverse_methods_aware_of_valid_p_and_invalid_p.md
- config/default.yml
Fixes #914.
This commit makes `Style/InverseMethods` aware of `valid?` and `invalid?` methods.
> [Fix #914] Make `Style/InverseMethods` aware of `valid?` and `invalid?` methods

- changelog/fix_an_error_for_rails_where_not_with_multiple_conditions.md
- lib/rubocop/cop/rails/where_not_with_multiple_conditions.rb
- spec/rubocop/cop/rails/where_not_with_multiple_conditions_spec.rb
Fixes #938.
This PR fixes an error for `Rails/WhereNotWithMultipleConditions` when using `where.not.lt(condition)` as a Mongoid API'.
> [Fix #938] Fix an error for `Rails/WhereNotWithMultipleConditions`

- lib/rubocop/cop/rails/unique_validation_without_index.rb
This change adds just a missing period.
> Fix typo in `Rails/UniqueValidationWithoutIndex` doc

- lib/rubocop-rails.rb
When running `Rails/SchemaComment` on a project which uses rails `main`, I get:
```
An error occurred while Rails/SchemaComment cop was inspecting example.rb:4:4.
undefined method `present?' for "Comment":String
/Users/fatkodima/Desktop/oss/rubocop-rails/lib/rubocop/cop/rails/schema_comment.rb:57:in `block in comment_present?'
/Users/fatkodima/Desktop/oss/rubocop-rails/lib/rubocop/cop/rails/schema_comment.rb:46:in `times'
/Users/fatkodima/Desktop/oss/rubocop-rails/lib/rubocop/cop/rails/schema_comment.rb:46:in `comment_present?'
/Users/fatkodima/Desktop/oss/rubocop-rails/lib/rubocop/cop/rails/schema_comment.rb:60:in `add_column_with_comment?'
/Users/fatkodima/Desktop/oss/rubocop-rails/lib/rubocop/cop/rails/schema_comment.rb:89:in `add_column_without_comment?' …
```
> Require missing `#blank?` from ActiveSupport

- changelog/fix_a_false_positive_for_rails_pluck.md
- lib/rubocop/cop/rails/pluck.rb
- spec/rubocop/cop/rails/pluck_spec.rb
Fixes #860.
This PR fixes a false positive for `Rails/Pluck` when using regexp literal key for `String#[]`.
> [Fix #860] Fix a false positive for `Rails/Pluck`

- .rubocop.yml
- changelog/fix_remove_redundant_config_for_style_inverse_methods.md
- config/default.yml
Fixes #941.
This PR removes redundant config for `Style/InverseMethods`. So each invert rule was already supported by the following cops.
- `Rails/Present` cop ... `present?` / `blank?`
- `Rails/NegateInclude` cop ... `include?` / `exclude?`
> [Fix #941] Remove redundant config for `Style/InverseMethods`

- changelog/fix_a_false_negative_for_rails_output.md
- lib/rubocop/cop/rails/output.rb
- spec/rubocop/cop/rails/output_spec.rb
Fixes #934.
This PR fixes a false negative for `Rails/Output` when print methods without arguments.
https://github.com/rubocop/rubocop/issues/1184 reported the following problem, but it seems that it was mistakenly updated to allow no argument cases.
```console
expect(p.arity).to be 1
^
spec/models/cco/blog_cco2_spec.rb:46:16: C: Do not write to stdout. Use Rails' logger if you want to log.
```
It seems that https://github.com/rubocop/rubocop/pull/6829 has since used that mistake. So this PR steers `Rails/Output` back to its original intent.
> [Fix #934] Fix a false negative for `Rails/Output`

- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
Fixes #472.
This PR fixes incompatible suggestion message for `Rails/FilePath` when the return type should be `String` instead of `Pathname`.
> [Fix #472] Fix incompatible suggestion message for `Rails/FilePath`

- changelog/fix_a_false_positive_for_rails_http_positional_arguments.md
- lib/rubocop/cop/rails/http_positional_arguments.rb
- spec/rubocop/cop/rails/http_positional_arguments_spec.rb
Fixes #99.
This PR fixes a false positive for `Rails/HttpPositionalArguments` when using `include Rack::Test::Methods`.
> [Fix #99] Fix a false positive for `Rails/HttpPositionalArguments`

- changelog/change_add_autocorrect_to_reflection_class_name.md
- lib/rubocop/cop/rails/reflection_class_name.rb
- spec/rubocop/cop/rails/reflection_class_name_spec.rb
> Add autocorrection for `Rails/ReflectionClassName`

- changelog/change_mark_rails_response_parsed_body_as_unsafe.md
- config/default.yml
- lib/rubocop/cop/rails/response_parsed_body.rb
Fixes #940.
This PR marks `Rails/ResponseParsedBody` as unsafe because I was misleading below:
https://github.com/rubocop/rubocop-rails/pull/863#discussion_r1024247356
It's actually unsafe.
> [Fix #940] Mark `Rails/ResponseParsedBody` as unsafe

- changelog/change_mark_rails_find_each_as_unsafe.md
- config/default.yml
- lib/rubocop/cop/rails/find_each.rb
Fixes #694 and #397.
This PR marks `Rails/FindEach` as unsafe.
> [Fix #694] Mark `Rails/FindEach` as unsafe

- config/default.yml
Fixes #888.
This PR makes `Style/InverseMethods` aware of `exists?`. Probably simpler than implementing a new named cop. And there will be no overlap with existing cop as reported in #941.
> [Fix #888] Make `Style/InverseMethods` aware of `exists?`

- changelog/new_make_rails_delegate_aware_of_self.md
- lib/rubocop/cop/rails/delegate.rb
- spec/rubocop/cop/rails/delegate_spec.rb
Fixes #45.
This PR makes `Rails/Delegate` aware of `self`.
> [Fix #45] Make `Rails/Delegate` aware of `self`

- changelog/change_allow_create_table_with_timestamps_for_id_false.md
- lib/rubocop/cop/rails/create_table_with_timestamps.rb
- spec/rubocop/cop/rails/create_table_with_timestamps_spec.rb
Fixes #34.
This PR allows `CreateTableWithTimestamps` when using `id: false` and not include `timestamps`.
There are design arguments for both allowing and disallowing migration file has `timestamps` when `id: false` (join table) . For the following reasons, allow it when `id: false`:
For example, when running `bin/rails g migration create_articles`, the migration file containing `timestamps` is created by default. Perhaps editing `id: false` and removing `timestamps` will be intentional. On the other hand, if it is not intentionally deleted, it will remain.
So I think that it is possible to allow the behavior that `timestamps` is not written for `id: false`. This emphasizes respecting user's editing intentions.
Before submitting the PR make sure the following are …
> [Fix #34] Allow `CreateTableWithTimestamps` when using `id: false` and not include `timestamps`

- changelog/fix_a_false_positive_for_rails_output_safety.md
- lib/rubocop/cop/rails/output_safety.rb
- spec/rubocop/cop/rails/output_safety_spec.rb
Fixes #501.
This PR fixes a false positive for `Rails/OutputSafety` when using `html_safe` for `I18n` methods.
> [Fix #501] Fix a false positive for `Rails/OutputSafety`

- changelog/fix_an_error_for_rails_three_state_boolean.md
- lib/rubocop/cop/rails/three_state_boolean_column.rb
- spec/rubocop/cop/rails/three_state_boolean_column_spec.rb
Fixes #979.
This PR fixes an error for `Rails/ThreeStateBooleanColumn` when using `t.boolean` in `drop_table`.
> [Fix #979] Fix an error for `Rails/ThreeStateBooleanColumn`

- .circleci/config.yml
- .rubocop.yml
- changelog/change_drop_ruby_2_6_support.md
- lib/rubocop/cop/rails/lexically_scoped_action_filter.rb
- lib/rubocop/rails/schema_loader/schema.rb
- rubocop-rails.gemspec
- spec/project_spec.rb
- tasks/changelog.rb
Follow up https://github.com/rubocop/rubocop/pull/11791.
This PR drops Ruby 2.6 support. And JRuby has been dropped from the CI matrix because no JRuby-specific issues have been found and prevents the following build error:
```console
#!/bin/bash -eo pipefail
bundle install
Fetching https://github.com/rubocop/rubocop.git
You need to install git to be able to use gems from git repositories. For help
installing git, please refer to GitHub's tutorial at
https://help.github.com/articles/set-up-git
Exited with code exit status 11
CircleCI received exit code 11
```
https://app.circleci.com/pipelines/github/rubocop/rubocop-minitest/926/workflows/68776b54-5856-4acd-a99a-f41df114634d/jobs/6034
This does not mean no support for JRuby. RuboCop Rails will continue to support JRuby 9.4+. …
> Drop Ruby 2.6 support

- lib/rubocop/cop/rails/file_path.rb
I noticed that you did not use the argument `require_to_s` passed from `#on_dstr` at https://github.com/rubocop/rubocop-rails/commit/b7ac06bf5675a3209fbbe3ff07ef6cb6f465b323. Wouldn't it be more appropriate to change it this way?
> Fix `require_to_s` usage on dstr cases

- changelog/new_add_autocorrection_for_rails_ignored_skip_action_filter_option.md
- lib/rubocop/cop/rails/ignored_skip_action_filter_option.rb
- spec/rubocop/cop/rails/ignored_skip_action_filter_option_spec.rb
If what the message says is true, this autocorrection will not change the behavior and is a safe autocorrection.
> Add autocorrection for `Rails/IgnoredSkipActionFilterOption`

- changelog/fix_rails_file_path_to_detect_offenses_from_complex_string_interpolation.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
So far, this cop has only detected offenses from dstr nodes that end with str node, but I think there are offenses that would be missed if it did so. Therefore, I have changed the `#on_dstr` implementation to detect offenses even in examples such as the one I have added as a test case.
> Fix `Rails/FilePath` to detect offenses from complex string interpolation

- changelog/change_exclude_app_assets_by_default.md
- config/default.yml
This change is for the same reason as the following issue:
- https://github.com/rubocop/rubocop-rails/issues/796
In a typical Rails application, this directory often contains a large number of non-ruby files, and I believe this optimization is reasonable for rubocop-rails to speed things up.
> Exclude `app/assets/**/*` by default

- changelog/new_add_autocorrection_for_rails_file_path.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
> Add autocorrection for `Rails/FilePath`

- changelog/fix_not_allow_not_null_to_work_with_methods_and_variables.md
- lib/rubocop/cop/rails/not_null_column.rb
- spec/rubocop/cop/rails/not_null_column_spec.rb
At the NotNullColumn cop if a method is passed as arguments for `add_column` an error is triggered:
```
NoMethodError:
undefined method `value' for s(:send, nil, :string):RuboCop::AST::SendNode
```
In this commit, we check if the argument is a method and when positive we return its name as a String.
> [Fix #997] Allow NotNullColumn to work with method calls

- changelog/change_make_lint_redundant_safe_navigation_aware_of_several_methods.md
- config/default.yml
This PR makes `Lint/RedundantSafeNavigation` aware of `blank?`, `presence`, and `present?` methods.
> Make `Lint/RedundantSafeNavigation` aware of several methods

- changelog/fix_uniqueness_validation_without_index_explicit_disable_false_positive.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
Fixes: `Rails/UniqueValidationWithoutIndex`
Currently `validates :column_name, uniqueness: false` will report an offence if the schema does not specify a unique index for the corresponding database column. The cop is currently insensitive to the value of the `:uniqueness` option. Any value (including falsy `false` and `nil`) will cause this cop to expect a unique index in the schema.
This pull request fixes this behaviour such that we will now only report offences when the value of the `:uniqueness` option is truthy.
> Fix `Rails/UniquenessValidationWithoutIndex` false positive on explicit disable

- changelog/new_add_autocorrection_for_rails_date.md
- config/default.yml
- lib/rubocop/cop/rails/date.rb
- spec/rubocop/cop/rails/date_spec.rb
For the same reason as `Rails/TimeZone`, this autocorrection is unsafe.
As you can see where `expect_no_corrections`s are added, I could not provide autocorrection for the rule that considers `to_time` as a violation.
> Add autocorrection for `Rails/Date`

- changelog/fix_an_error_for_rails_unique_validation_without_index.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
This PR is fix an error for `Rails/UniqueValidationWithoutIndex`.
Code to reproduce in `models/**/*.rb`:
```ruby
validates :name, presence: true
```
Occurred Error:
```
An error occurred while Rails/UniqueValidationWithoutIndex cop was inspecting /Users/ydah/test/app/models/test.rb:18:2.
undefined method `falsey_literal?' for nil:NilClass
/Users/ydah/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rubocop-rails-2.20.0/lib/rubocop/cop/rails/unique_validation_without_index.rb:34:in `on_send'
/Users/ydah/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rubocop-1.52.1/lib/rubocop/cop/commissioner.rb:143:in `public_send'
/Users/ydah/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rubocop-1.52.1/lib/rubocop/cop/commissioner.rb:143:in `block (2 levels) in trigger_restricted_cops' …
```
> Fix an error for `Rails/UniqueValidationWithoutIndex`

- changelog/fix_error_for_unique_validation_without_index_when_schema_empty.md
- lib/rubocop/rails/schema_loader.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
> Fix an error for `UniqueValidationWithoutIndex` when `db/schema.rb` is empty

- changelog/change_restrict_duplicate_association_cop_to.md
- lib/rubocop/cop/rails/duplicate_association.rb
- spec/rubocop/cop/rails/duplicate_association_spec.rb
Previously this cop would run against all classes, which led to false positives when the class was not descended from `ActiveRecord::Base` and thus might have acceptable use cases for repeating association declarations in ways that would not be acceptable in AR classes.
> Restrict DuplicateAssociation cop to ActiveRecord

- changelog/fix_an_incorrect_autocorrect_for_rails_file_path_when_file_join_with_start_slash.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
This PR is fix an incorrect autocorrect for `Rails/FilePath` when File.join with Rails.root and path starting with `/`.
Auto-correct of following code would change the path.
Code to reproduce:
```ruby
File.join(Rails.root, '/app/models', 'user.rb')
```
Expected behavior:
```ruby
Rails.root.join("app/models/user.rb").to_s
```
Actual behavior:
```ruby
Rails.root.join("/app/models/user.rb").to_s
```
> Fix an incorrect autocorrect for `Rails/FilePath` when File.join with Rails.root and path starting with `/`

- changelog/fix_a_false_positive_for_rails_root_pathname_methods_on_ruby_2_4.md
- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
`Pathname#glob` was added at Ruby 2.5, so it cannot be used on Ruby 2.4 or lower versions.
For example, this false-positive becomes a problem when a gem that uses RuboCop wants to provide code that also supports Ruby 2.4-.
```
$ ruby --version
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-linux]
$ ruby -r pathname -e "Pathname.new('foo').glob('*')"
-e:1:in `<main>': undefined method `glob' for #<Pathname:foo> (NoMethodError)
```
> Fix a false-positive for `Rails/RootPathnameMethods` on Ruby 2.4 or lower

- changelog/new_explicit_style_to_i18n_lazy_lookup.md
- config/default.yml
- lib/rubocop/cop/rails/i18n_lazy_lookup.rb
- spec/rubocop/cop/rails/i18n_lazy_lookup_spec.rb
Adds a new `explicit` style to the `Rails/I18nLazyLookup` cop (and names the default one `lazy`).
This way we can enforce the use of fully qualified i18n key names eg. `"recipes.show.title"` rather than shorthand `".title"`.
See also: https://github.com/cookpad/global-style-guides/pull/203
> Add explicit style to `Rails/I18nLazyLookup`

- changelog/fix_no_offences_for_schema_comment_when_create_table_with_multi_t_columns.md
- lib/rubocop/cop/rails/schema_comment.rb
- spec/rubocop/cop/rails/schema_comment_spec.rb
This PR is fix no offenses for `Rails/SchemaComment`.
```rb
create_table :users, comment: 'Table' do |t|
t.integer :column1 # <- no offenses this line
t.integer :column2 # <- also no offenses this line
end
```
> Fix create_table with multi t columns for `Rails/SchemaComment`

- changelog/change_relax_include_path_for_rails_find_by_and_find_each.md
- config/default.yml
Fixes #1058.
This PR relaxes `Include` path for `Rails/FindBy` and `Rails/FindEach`.
`Rails/FindBy` was introduced in https://github.com/rubocop/rubocop/commit/6188d75. This was before it was extracted to RuboCop Rails, which is probably why it was targeting `app/models`. So, RuboCop Rails targeting Rails would not need it.
`Rails/FindEach` is the same:
https://github.com/rubocop/rubocop/commit/f2e26812
> [Fix #1058] Relax `Include` path for `Rails/FindBy` and `Rails/FindEach`

- changelog/fix_a_false_positive_for_rails_http_status.md
- lib/rubocop/cop/rails/http_status.rb
- spec/rubocop/cop/rails/http_status_spec.rb
Fixes #1060.
This PR fixes a false positive for `Rails/HttpStatus` when using symbolic value that have no numeric value mapping.
> [Fix #1060] Fix a false positive for `Rails/HttpStatus`

- changelog/change_fix_database_adapter_detection_for.md
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
When a database yml is configured with nested named databases (for example: `primary`, `read`, `replica`, etc) the adapter detection fails by only looking for a top-level `adapter` key in the hash.
This changes the detection to try the top-level location first, and then also attempt to look for an `adapter` key in the first nested hash under `development` as well.
> Fix database adapter detection for nested config

- changelog/fix_an_error_for_rails_file_path.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
Fixes #1066.
This PR fixes an error for `Rails/FilePath` when string interpolated `Rails.root` is followed by a message starting with `.`.
> [Fix #1066] Fix an error for `Rails/FilePath`

- changelog/change_make_lint_safe_navigation_chain_allow_presence_in.md
- config/default.yml
Fixes #1031.
This PR makes `Lint/SafeNavigationChain` allow `presence_in`.
It adds `presence_in` method to the default of the RuboCop core: https://github.com/rubocop/rubocop/blob/v1.56.0/config/default.yml#L2265-L2271
> [Fix #1031] Make `Lint/SafeNavigationChain` allow `presence_in`

- changelog/fix_an_incorrect_autocorrect_for_rails_negate_include.md
- lib/rubocop-rails.rb
- spec/rubocop/cli/autocorrect_spec.rb
Fixes #1045.
This PR fixes an incorrect autocorrect for `Rails/NegateInclude` when using `Style/InverseMethods`'s autocorrection together.
> [Fix #1045] Fix an incorrect autocorrect for `Rails/NegateInclude`

- changelog/new_add_allow_methods_and_allow_patterns_to_transaction_exit_statement.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
Hi. 
We differentiate transactions by using methods with different names depending on the target DB. 
So I would like to be able to leave the transaction on_lock as the default and add another method name to use it.
like..
```yaml
Rails/TransactionExitStatement:
TransactionMethods:
- transaction
- on_lock
- some_custom
```
* ~~[ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~~
* ~~[ ] If this is a new cop, consider making a corresponding update to the [Rails Style Guide](https://github.com/rubocop/rails-style-guide).~~
> Add Configurable option for `Rails/TransactionExitStatement`

- changelog/new_add_allow_methods_and_allow_patterns_to_transaction_exit_statement.md
- changelog/new_add_transaction_methods_to_transaction_exit_statement.md
- config/default.yml
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
Follow up https://github.com/rubocop/rubocop-rails/pull/1072.
This PR renames `AllowedMethods` to `TransactionMethods` for `Rails/TransactionExitStatement` because it's a configuration for detecting, not for allowing custom transaction methods.
> Rename `AllowedMethods` to `TransactionMethods` for `Rails/TransactionExitStatement`

- lib/rubocop/cop/rails/action_controller_test_case.rb
- lib/rubocop/cop/rails/root_pathname_methods.rb
- Remove unnecessary backquotes.
- https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsactioncontrollertestcase
- Add backquotes  to prevent apostrophe-S from being interpreted as a [single curved quote](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-formatting).
- https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsrootpathnamemethods
> Fix incorrect comments as AsciiDoc inline code

- changelog/fix_a_false_negative_for_lexically_scoped_action_filter.md
- lib/rubocop/cop/rails/lexically_scoped_action_filter.rb
- spec/rubocop/cop/rails/lexically_scoped_action_filter_spec.rb
Resolves https://github.com/rubocop/rubocop-rails/issues/1078
This PR fixes the edge case where the class/module body does not define any methods at all.
> [Fix #1078] Fix false negative for `Rails/LexicallyScopedActionFilter`

- lib/rubocop/cop/rails/where_exists.rb
Remove invalid example:
```ruby
User.exists?('name = ?', 'john')
```
The example raises an `ArgumentError`: "wrong number of arguments (given 2, expected 0..1)"
> Update cops_rails.adoc - Removes invalid example

- changelog/change_make_style_invertible_unless_condition_aware_of_as_methods.md
- config/default.yml
Resolves #1015.
This PR makes `Style/InvertibleUnlessCondition` aware of Active Support methods. It still inherits the default disabled.
> [Fix #1015] Make `Style/InvertibleUnlessCondition` aware of Active Support methods

- changelog/change_make_rails_http_status_aware_of_string_number_status.md
- lib/rubocop/cop/rails/http_status.rb
- spec/rubocop/cop/rails/http_status_spec.rb
Resolves #1080.
This PR makes `Rails/HttpStatus` aware of string number status.
> [Fix #1080] Make `Rails/HttpStatus` aware of string number status

- changelog/fix_error_for_rails_redundant_active_record_all_method_when_all_is_an_argument_for_ar_methods.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
Resolved the following issues #1109, #1111
As pointed out in the mentioned issues, there was an oversight. I apologize for the mistake.
- ~~[ ] If this is a new cop, consider making a corresponding update to the [Rails Style Guide](https://github.com/rubocop/rails-style-guide).~~
> [Fix: #1109] Fix error for `Rails/RedundantActiveRecordAllMethod` when `all` is an argument for AR methods

- changelog/fix_false_positive_for_rails_redundant_active_record_all_method_when_all_has_any_parameters.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
Resolved the following issue: https://github.com/rubocop/rubocop-rails/issues/1110
As pointed out in the mentioned issue, there was an oversight. I apologize for the mistake.
In this PR, the cop treats `all` with parameters as not being an ActiveRecord method and excludes it from offenses.
* ~~[ ] If this is a new cop, consider making a corresponding update to the [Rails Style Guide](https://github.com/rubocop/rails-style-guide).~~
> [Fix: #1110] Fix false positive for `Rails/RedundantActiveRecordAllMethod` when `all` has any parameters

- changelog/fix_an_incorrect_autocorrect_for_rails_time_zone.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
Fixes #1108.
This PR fixes an incorrect autocorrect for `Rails/TimeZone` when using `String#to_time`.
> [Fix #1108] Fix an incorrect autocorrect for `Rails/TimeZone`

- README.md
- docs/modules/ROOT/pages/usage.adoc
Some `rails generators` may not generate `*.rb`. (e.g. `bin/rails g stimulus`)
In this case, `parsable_files` is empty, so RuboCop will parse all files.
This behavior is not intended, so it fixes the doc.
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
* [-] If this is a new cop, consider making a corresponding …
> [Doc] Prevent unintended auto-correct with after_generate

- changelog/fix_an_incorrect_autocorrect_for_rails_redundant_active_record_all_method_when_all_has_parentheses.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
Fix: https://github.com/rubocop/rubocop-rails/issues/1119
This PR fixes an incorrect autocorrect for `Rails/RedundantActiveRecordAllMethod` when `all` has parentheses.
* ~~[ ] If this is a new cop, consider making a corresponding update to the [Rails Style Guide](https://github.com/rubocop/rails-style-guide).~~
> [Fix: #1119] Fix an incorrect autocorrect for `Rails/RedundantActiveRecordAllMethod`  when `all` has parentheses

- lib/rubocop/cop/rails/unused_render_content.rb
@shepmaster [reported](https://github.com/rubocop/rubocop-rails/issues/1116) that, by following the examples for the Rails/UnusedRenderContent cop from the rubocop-rails documentation, they were seeing errors in their Rails application. Please see the issue for a full discussion of the issue.
TLDR:
Using `render` without specifying a content option (for example `:json` option), will cause Rails to look for a view template matching the controller/action name. If a matching view template cannot be found, Rails will raise a `ActionView::MissingTemplate` error. This is true even for no-content response statuses.
The documentation should demonstrate and recommend the use of `head` instead of `render` to avoid these errors.
Before submitting the PR make sure the following are …
> [Fix #1116] Update Rails/UnusedRenderContent documentation to recommend use of `head` instead of `render`

- changelog/fix_bug_unique_validation_without_index.md
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- spec/rubocop/cop/rails/unique_validation_without_index_spec.rb
This PR fixes #1130 , a bug in `Rails/UniqueValidationWithoutIndex` that raises an exception if some (admittedly invalid) code is encountered.
It's just a method call on an object that might be nil. Since `&.` was added in ruby 2.3 and the gemspec requires ruby 2.7, I used that to fix it.
Tests that trigger the exception are added.
I'm happy to make any changes requested.
> [Fix #1130] Fix crash for Rails/UniqueValidationWithoutIndex with bare validate

- changelog/fix_false_positive_for_rails_redundant_active_record_dll_method.md
- config/default.yml
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
Fixes #1124.
This PR fixes false positives for `Rails/RedundantActiveRecordAllMethod` when receiver is not an Active Record model.
> [Fix #1124] Fix false positives for `Rails/RedundantActiveRecordAllMethod`

- lib/rubocop/cop/mixin/index_method.rb
We were trying to add a custom cop called `Struct/RequiresTypedStructHelper`, but ran into a problem where we got an error like:
```
undefined method `new' for RuboCop::Cop::Struct:Module
/Users/technicalpickles/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-rails-2.21.1/lib/rubocop/cop/mixin/index_method.rb:105:in `module:IndexMethod'
/Users/technicalpickles/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-rails-2.21.1/lib/rubocop/cop/mixin/index_method.rb:6:in `module:Cop'
/Users/technicalpickles/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-rails-2.21.1/lib/rubocop/cop/mixin/index_method.rb:4:in `module:RuboCop'
/Users/technicalpickles/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-rails-2.21.1/lib/rubocop/cop/mixin/index_method.rb:3:in `top (required)' …
```
> Qualify Struct reference to avoid collisions with possible cop namespace

- spec/support/shared_contexts.rb
This adds a shared context for the upcoming Rails 7.1, whose release candidate was released yesterday. As a release candidate indicates APIs are likely stable, we can begin writing/updating cops for it.
This commit was extracted from #906, and could be used in #894.
* ~Commit message starts with `[Fix #issue-number]` (if the related issue exists).~
* ~Added tests.~
* ~Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~
* ~If …
> Add `:rails71` shared context

- config/default.yml
This PR removes the style guide link from `Rails/DefaultScope` because the URL is missing. 
The style guide section was not merged in https://github.com/rubocop/rails-style-guide/pull/267.
* ~~[ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~~
* ~~[ ] Added tests.~~
* ~~[X] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~~
* ~~[ ] If this is a new cop, consider making a corresponding …
> [Doc] Remove missing style guide link from `Rails/DefaultScope`

- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/rails/helper_instance_variable.rb
This replaces "re-use" with "reuse", which was [flagged](https://github.com/rubocop/rubocop-rails/actions/runs/6418291313/job/17425777413?pr=38) on #38 for some reason. That PR didn't touch those files, but I figured I'd fix them anyway.
* ~Added tests.~
* ~Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~
* ~If this is a new cop, consider making a corresponding update to the [Rails Style …
> Replace "re-use" with "reuse"

- changelog/change_rails_unknown_env_to_add_local.md
- lib/rubocop/cop/rails/unknown_env.rb
- spec/rubocop/cop/rails/unknown_env_spec.rb
Fixes https://github.com/rubocop/rubocop-rails/issues/893
> Support `local` as an environment for `Rails/UnknownEnv` from Rails 7.1 onward.

- changelog/fix_a_false_positive_for_rails_output.md
- lib/rubocop/cop/rails/output.rb
- spec/rubocop/cop/rails/output_spec.rb
Fixes #1041.
This PR fixes a false positive for `Rails/Output` when output method is called with block argument.
The output method for the bad case is not designed to take a block argument. Thus, by ignoring this, it can likely reduce false positives.
> [Fix #1041] Fix a false positive for `Rails/Output`

- changelog/fix_false_positives_for_redundant_presence_validation_on_belongs_to.md
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
- spec/rubocop/cop/rails/redundant_presence_validation_on_belongs_to_spec.rb
Fixes #1105.
This PR fixes false positives for `Rails/RedundantPresenceValidationOnBelongsTo` when using `validates` with `:if` or `:unless` options.
> [Fix #1105] Fix false positives for `Rails/RedundantPresenceValidationOnBelongsTo`

- changelog/new_support_trilogy_adapter_for_mysql.md
- lib/rubocop/cop/mixin/database_type_resolvable.rb
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
This PR supports the Trilogy adapter for MySQL.
https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released#built-in-support-for-the-trilogy-mysql-adapter
> Support the Trilogy adapter for MySQL

- changelog/fix_a_false_positive_for_rails_not_null_column.md
- config/default.yml
- lib/rubocop/cop/rails/not_null_column.rb
- spec/rubocop/cop/rails/not_null_column_spec.rb
Fixes #952.
This PR fixes a false positive for `Rails/NotNullColumn` when using `null: false` for MySQL's TEXT type.
> [Fix #952] Fix a false positive for `Rails/NotNullColumn`

- changelog/change_deprecate_rails_action_filter_cop.md
- lib/rubocop/cop/rails/action_filter.rb
Fixes #1039.
This PR deprecates `Rails/ActionFilter` cop. Because the `*_filter` methods were removed in Rails 4.2, and that Rals version is no longer supported by RuboCop Rails. This cop will be removed in RuboCop Rails 3.0.
> [Fix #1039] Deprecate `Rails/ActionFilter` cop

- changelog/new_support_rails_7_1_methods_for_redundant_active_record_all_method.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
Follow up https://github.com/rails/rails/pull/44446, https://github.com/rails/rails/pull/37944, https://github.com/rails/rails/pull/46503, and https://github.com/rails/rails/pull/47010.
This PR supports some Rails 7.1's new querying methods for `Rails/RedundantActiveRecordAllMethod`.
> Support some Rails 7.1's new querying methods for `Rails/RedundantActiveRecordAllMethod`

- changelog/fix_has_many_or_has_one_dependent_false_positive.md
- lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb
- spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb
Fixes: https://github.com/rubocop/rubocop-rails/issues/1158
> [Fix #1158] Rails/HasManyOrHasOneDependent reports false positive when has_many or has_one called on explicit receiver

- changelog/fix_an_error_for_rails_redundant_active_record_all_method.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
Fixes #1143.
This PR fixes an error for `Rails/RedundantActiveRecordAllMethod` when using RuboCop 1.51 or lower.
> [Fix #1143] Fix an error for `Rails/RedundantActiveRecordAllMethod`

- changelog/fix_a_false_positive_for_rails_duplicate_association.md
- lib/rubocop/cop/rails/duplicate_association.rb
- spec/rubocop/cop/rails/duplicate_association_spec.rb
Fixes #1145.
This PR fixes a false positive for `Rails/DuplicateAssociation` when using duplicate `belongs_to` associations of same class without other arguments.
> [Fix #1145] Fix a false positive for `Rails/DuplicateAssociation`

- changelog/fix_an_error_for_rails_unknown_env.md
- lib/rubocop/cop/rails/unknown_env.rb
- spec/rubocop/cop/rails/unknown_env_spec.rb
Fixes #1172.
This PR fixes an error for `Rails/UnknownEnv` when using Rails 7.1.
> [Fix #1172] Fix an error for `Rails/UnknownEnv`

- changelog/change_require_rubocop_ast_1_30.md
- lib/rubocop/cop/rails/after_commit_override.rb
- lib/rubocop/cop/rails/bulk_change_table.rb
- lib/rubocop/cop/rails/dangerous_column_names.rb
- lib/rubocop/cop/rails/file_path.rb
- lib/rubocop/cop/rails/inverse_of.rb
- lib/rubocop/cop/rails/rake_environment.rb
- lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb
- lib/rubocop/cop/rails/reversible_migration.rb
- lib/rubocop/cop/rails/unique_validation_without_index.rb
- lib/rubocop/cop/rails/validation.rb
- lib/rubocop/rails/schema_loader/schema.rb
- rubocop-rails.gemspec
Follow up https://github.com/rubocop/rubocop/pull/12305.
> Require RuboCop AST 1.30.0+

- changelog/change_rails_redundant_active_record_all_method.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
This PR changes `Rails/RedundantActiveRecordAllMethod` to ignore `delete_all` and `destroy_all` when the receiver is an association (e.g., user.articles.all.delete_all). It only checks cases where the receiver is a model.
As pointed out in https://github.com/rubocop/rails-style-guide/issues/347, it has been found that when the receiver of `all` is an association, omitting `all` can change the behavior of certain methods.  I think that in cases where behavior could change, it would be better for the cop not to add an offense.
Currently, among the methods targeted by this cop, the following methods have been confirmed to change behavior when `all` is omitted from an association:
- `delete_all`
- `destroy_all`
**delete_all**
```ruby
user.articles.all.delete_all
user.articles.delete_all
``` …
> Change `Rails/RedundantActiveRecordAllMethod` to ignore `delete_all` and `destroy_all` when receiver is an association

- .github/workflows/test.yml
- changelog/fix_error_for_rails_redundant_active_record_all_method.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
Fixes #1173.
This PR fixes an error for `Rails/RedundantActiveRecordAllMethod` cop when using RuboCop 1.51 or lower.
> [Fix #1173] Fix an error for `Rails/RedundantActiveRecordAllMethod` cop

- changelog/new_support_postgis_adapter_for_postgresql.md
- docs/modules/ROOT/pages/cops_rails.adoc
- lib/rubocop/cop/mixin/database_type_resolvable.rb
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
When using the `postgis` adapter, this the `Rails/BulkChangeTable` cop interprets this as a database which does not support bulk alter statements.  Since postgis is an extension for postgreSQL, it should be treated the same as postgreSQL when determining if this cop should be run.
> support postGIS adapter for postgreSQL

- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
This PR removes NOTE tag from `Rails/RedundantActiveRecordAllMethod` description for readability.
The inline code written in the NOTE section is not being displayed in the [RuboCop Rails documentation](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsredundantactiverecordallmethod), making it difficult to read.
I think removing the NOTE tag would enhance the documentation's readability.
> Remove NOTE tag from `Rails/RedundantActiveRecordAllMethod` description for readability

- changelog/fix_false_negatives_for_rails_pluck.md
- lib/rubocop/cop/rails/pluck.rb
- spec/rubocop/cop/rails/pluck_spec.rb
Fixes #1189.
This PR fixes false negatives for `Rails/Pluck` when using safe navigation method calls.
> [Fix #1189] Fix false negatives for `Rails/Pluck`

- changelog/fix_error_for_where_missing_where_joins_called_without_args.md
- lib/rubocop/cop/rails/where_missing.rb
- spec/rubocop/cop/rails/where_missing_spec.rb
> Fix an error for `Rails/WhereMissing` where join method is called without arguments

- changelog/change_support_nokogiri_html_parse.md
- config/default.yml
- lib/rubocop/cop/rails/response_parsed_body.rb
- spec/rubocop/cop/rails/response_parsed_body_spec.rb
Since Rails 7.1, `response.parse_body` now supports `Content-Type: text/html` responses:
- https://github.com/rails/rails/pull/47144
So, how about adding support for this in the `Rails/ResponseParsedBody` cop?
> Support `Nokogiri::HTML.parse` and `Nokogiri::HTML5.parse` on `Rails/ResponseParsedBody`

- changelog/change_support_where_not_for_pluck_in_where.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/cop/rails/pluck_in_where.rb
- spec/rubocop/cop/rails/pluck_in_where_spec.rb
> Support `where.not` for `Rails/PluckInWhere`

- changelog/change_support_ids_for_pluck_in_where.md
- lib/rubocop/cop/rails/pluck_in_where.rb
- spec/rubocop/cop/rails/pluck_in_where_spec.rb
> Update `Rails/PluckInWhere` to check for `.ids` call

- changelog/fix_make_some_cops_aware_of_safe_navigation_operator.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/cop/rails/active_support_aliases.rb
- lib/rubocop/cop/rails/find_by.rb
- lib/rubocop/cop/rails/find_by_id.rb
- lib/rubocop/cop/rails/inquiry.rb
- lib/rubocop/cop/rails/pick.rb
- lib/rubocop/cop/rails/pluck_id.rb
- lib/rubocop/cop/rails/pluck_in_where.rb
- lib/rubocop/cop/rails/where_equals.rb
- lib/rubocop/cop/rails/where_exists.rb
- lib/rubocop/cop/rails/where_not.rb
- spec/rubocop/cop/rails/active_support_aliases_spec.rb
- spec/rubocop/cop/rails/find_by_id_spec.rb
- spec/rubocop/cop/rails/find_by_spec.rb
- spec/rubocop/cop/rails/inquiry_spec.rb
- spec/rubocop/cop/rails/pick_spec.rb
- spec/rubocop/cop/rails/pluck_id_spec.rb
- spec/rubocop/cop/rails/pluck_in_where_spec.rb
- spec/rubocop/cop/rails/where_equals_spec.rb
- spec/rubocop/cop/rails/where_exists_spec.rb
- spec/rubocop/cop/rails/where_not_spec.rb
Fixes #1191, #1192, #1193, #1194, #1196, #1197, #1201, and #1202.
This PR makes `Rails/ActiveSupportAliases`, `Rails/FindBy`, `Rails/FindById`, `Rails/Inquiry`, `Rails/Pick` `Rails/PluckId`, `Rails/PluckInWhere`, `Rails/WhereEquals`, `Rails/WhereExists`, and `Rails/WhereNot` cops aware of safe navigation operator.
> Make some cops aware of safe navigation operator

- changelog/fix_where_not_with_implicit_receiver.md
- lib/rubocop/cop/rails/where_not.rb
- spec/rubocop/cop/rails/where_not_spec.rb
Fix an exception in `Rails/WhereNot` when calling `.where` on an implicit receiver (e.g. inside model code).
Fixes #1221
> Fix Rails/WhereNot when using implicit receiver

- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
When adding a test to `redundant_active_record_all_method_spec`, I was sometimes confused about which context to include the test in. So, I have refactored the test in structure to improve clarity and maintainability.
I've split the commits for better readability, so it might be easier to review them individually.
(If it would be better to split the PR, I am willing to do so.)
> Refactor test structure in redundant_active_record_all_method_spec

- changelog/change_fix_do_not_allow.md
- config/default.yml
- docs/modules/ROOT/pages/cops_rails.adoc
- spec/rubocop/cop/rails/environment_variable_access_spec.rb
The description of the cop states `Do not access ENV directly after initialization.`. However in some ways, the application is already initialized when we get to `config/**/*.rb`:
1. `config_for(:service)` is already available to read config from `service.yml`
2. `Rails.application.credentials` is already available to read application credentials / secrets
I think it could make sense to push people to move their config in either of these two places. If they want to access their config / secrets in a Ruby file, let's say, `config/initializers/service.rb` they can use `credentials` or `config_for`, no need to access `ENV` directly again.
Also see https://guides.rubyonrails.org/initialization.html.
I understand this is a bit nuanced, so if this is not desired, that's completely fine ✌️ …
> do not allow EnvironmentVariableAccess in initializers

- changelog/change_remove_object_id_from.md
- lib/rubocop/cop/rails/dangerous_column_names.rb
Rails 7.1.3 has been released and it includes a change that `object_id` is no longer a dangerous column, so let's remove this from `Rails/DangerousColumnNames` as well.
- https://github.com/rails/rails/releases/tag/v7.1.3
- https://github.com/rails/rails/pull/50162
This change was originally planned in the following comments:
- https://github.com/rubocop/rubocop-rails/pull/1152#issuecomment-1837319370
> Remove `object_id` from `Rails/DangerousColumnNames` targets

- changelog/fix_an_incorrect_autocorrect_for_rails_find_by.md
- lib/rubocop/cop/rails/find_by.rb
- spec/rubocop/cop/rails/find_by_spec.rb
Fixes #1234.
This PR fixes an incorrect autocorrect for `Rails/FindBy` when using multi-line leading dot method calls.
> [Fix #1234] Fix an incorrect autocorrect for `Rails/FindBy`

- changelog/fix_error_for_rails_where_exists.md
- lib/rubocop/cop/rails/where_exists.rb
- spec/rubocop/cop/rails/where_exists_spec.rb
`EnforcedStyle: exists` works fine, but since there was no test for this I added one.
>  Fix an error for `Rails/WhereExists` with `EnforcedStyle: where` and implicit recievers

- .github/workflows/test.yml
- Gemfile
- Rakefile
- changelog/new_support_prism.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- lib/rubocop/rails/schema_loader.rb
- rubocop-rails.gemspec
- spec/rubocop/cop/rails/blank_spec.rb
- spec/rubocop/cop/rails/exit_spec.rb
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
- spec/rubocop/cop/rails/present_spec.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
- spec/rubocop/cop/rails/safe_navigation_spec.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
- spec/rubocop/cop/rails/strip_heredoc_spec.rb
- spec/rubocop/cop/rails/where_exists_spec.rb
- spec/rubocop/rails/schema_loader_spec.rb
- spec/spec_helper.rb
Follow up https://github.com/rubocop/rubocop-ast/pull/277
Internally, the Parser gem API is used directly to parse db/schema.rb. This has been replaced with `RuboCop::AST::ProcessedSource` from RuboCop AST 1.31, which is compatible with the Prism parser API of the Parser gem API.
This change resolves error (e.g., `uninitialized constant Parser::Ruby33`) related to db/schema.rb parsing when Prism is specified as the parser engine, enabling paring with Prism.
> Support Prism as a Ruby parser

- changelog/fix_a_false_positive_for_rails_action_controller_flash_before_render.md
- lib/rubocop/cop/rails/action_controller_flash_before_render.rb
- spec/rubocop/cop/rails/action_controller_flash_before_render_spec.rb
> [Fix #1244] Fix a false positive for `Rails/ActionControllerFlashBeforeRender` when returning `redirect_to`

- changelog/fix_an_error_for_rails_unused_ignored_column.md
- lib/rubocop/rails/schema_loader/schema.rb
- spec/rubocop/cop/rails/unused_ignored_columns_spec.rb
Fixes #1247.
This PR fixes an error for `Rails/UnusedIgnoredColumns` when without tables in db/schema.rb.
> [Fix #1247] Fix an error for `Rails/UnusedIgnoredColumns`

- changelog/fix_and_error_for_rails_expanded_date_range.md
- lib/rubocop/cop/rails/expanded_date_range.rb
- spec/rubocop/cop/rails/expanded_date_range_spec.rb
`:monday` is the default, however this can be set per request/overwritten in the config so an offense is not possible here.
> Fix an error for `Rails/ExpandedDateRange` when passing an argument only to the first method call

- changelog/fix_error_for_rails_active_support_load_hook.md
- lib/rubocop/cop/rails/active_support_on_load.rb
- spec/rubocop/cop/rails/active_support_on_load_spec.rb
> Fix an error for `Rails/ActiveSupportOnLoad` when calling without arguments

- changelog/change_add_more_load_hooks_to_rails_active_support_on_load.md
- config/default.yml
- lib/rubocop/cop/rails/active_support_on_load.rb
- spec/rubocop/cop/rails/active_support_on_load_spec.rb
Mostly from Rails 7.1, except for `active_record_sqlite3adapter` which has been around for longer but wasn't documented until recently.
Reference list: https://guides.rubyonrails.org/engines.html#available-load-hooks
Rails PRs:
* `ActiveRecord::TestFixtures`/`active_record_fixtures`: https://github.com/rails/rails/pull/47690
* `ActiveModel::Model`/`active_model`: https://github.com/rails/rails/pull/48698
* `ActionText::EncryptedRichText`/`action_text_encrypted_rich_text`: https://github.com/rails/rails/pull/47737 7.1
* `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter`/`active_record_postgresqladapter`: https://github.com/rails/rails/pull/44601
* `ActiveRecord::ConnectionAdapters::Mysql2Adapter`/`active_record_mysql2adapter`: https://github.com/rails/rails/pull/48012
* …
> Add more load hooks to `Rails/ActiveSupportOnLoad`

- changelog/fix_an_error_for_rails_where_missing.md
- lib/rubocop/cop/rails/where_missing.rb
- spec/rubocop/cop/rails/where_missing_spec.rb
This only happens if `where` comes before `left_joins`. I added tests for both anyways.
> Fix an error for `Rails/WhereMissing` without receiver

- changelog/fix_make_rails_time_zone_aware_of_safe_navigation.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
`parse` raises on `nil` so autocorrect is not possible in this case.
> [Fix #1200] Make `Rails/TimeZone` aware of safe navigation

- changelog/fix_an_error_for_rails_uniq_before_pluck.md
- lib/rubocop/cop/rails/uniq_before_pluck.rb
- spec/rubocop/cop/rails/uniq_before_pluck_spec.rb
> Fix an error for `Rails/UniqBeforePluck` with `EnforcedStyle: aggressive` when no receiver

- changelog/fix_false_positive_for_rails_save_bang.md
- lib/rubocop/cop/rails/save_bang.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
There are a few more cases I can think of that should potentially be handled, like
```rb
while (post = User.create(params).persisted?
params = new_params
end
```
but I'd wait until someone actually complains. It doesn't look like very practical code to me.
> [Fix #1230] Fix a false positive for `Rails/SaveBang` if `persisted?` is checked on parenthesised expression.

- changelog/fix_unknown_env_causing_cache_issues.md
- lib/rubocop/cop/rails/unknown_env.rb
- spec/rubocop/cop/rails/unknown_env_spec.rb
After upgrading to Rails 7.1 we noticed a significant slowdown of RuboCop (52s -> 3m 52s).
We found that the cache file path for certain files was changing throughout the RuboCop execution, resulting in cache misses. One of the components of the cache file path is the [cop config](https://github.com/rubocop/rubocop/blob/f9b3b1ed1ddb6129cd5bf7c16824261041f107d5/lib/rubocop/result_cache.rb#L160). 
When diffing the cop config throughout RuboCops execution we find that "Rails/UnknownEnv"."Environments"  is changing: 
When Rails/UnknownEnv runs as part of the [warm_cache](https://github.com/rubocop/rubocop/blob/f9b3b1ed1ddb6129cd5bf7c16824261041f107d5/lib/rubocop/runner.rb#L72) step in RuboCop it mutates the config, which subsequently modifies the file checksums. When RuboCop runs …
> [Fix #1260] Fix performance regression caused by `Rails/UnknownEnv` on rails 7.1

- changelog/change_disable_rails_unused_ignored_columns.md
- config/default.yml
- lib/rubocop/cop/rails/unused_ignored_columns.rb
Fix #1249
This cop can't be used to effectivly check for unused columns because the development and production schema can be out of sync until the migration has been run on production.
As such, this cop can cause `ignored_columns` to be removed even though the production schema still contains the column, which can lead to downtime when the migration is actually executed.
Users can manually enable this cop if they know this isn't an issue that can/will impact them.
cc @rafaelfranca, let me know if the added tidbit to the cops documentation is not correct.
> [Fix #1249] Disable `Rails/UnusedIgnoredColumns` by default

- changelog/change_migrate_to_requires_gem_api.md
- lib/rubocop/cop/mixin/target_rails_version.rb
- spec/rubocop/config_spec.rb
This PR updates the `TargetRailsVersion` to conditionally use the [`requires_gem` API](https://github.com/rubocop/rubocop/pull/12186/files) when available (depending on the version of the base RuboCop gem). This has several advantages:
1. It resolves a circular dependancy.
* `rubocop-rails` depends on `rubocop` (e.g. for `RuboCop::Cop::Base`), and that's fine, but there's also a hidden reverse dependency, where `rubocop` implicitly depends on `rubocop-rails`.
* Now it's just one-way. `rubocop-rails` registers its minimum version requirements, and `rubocop` knows how to understand those without needing to call back into `rubcop-rails`.
2. It removes a "snowflake" case that's treated specially. For now we need to support both for backwards compatibility, but eventually when old versions are …
> Migrate `TargetRailsVersion` to the new `requires_gem` RuboCop API

- changelog/fix_an_incorrect_autocorrect_for_rails_validation.md
- lib/rubocop/cop/rails/validation.rb
- spec/rubocop/cop/rails/validation_spec.rb
Fixes #1270.
This PR fixes an incorrect autocorrect for `Rails/Validation` when using `validates_size_of`.
> [Fix #1270] Fix an incorrect autocorrect for `Rails/Validation`

- changelog/change_make_rails_http_status_aware_of_rails_specific_response_assertions.md
- lib/rubocop/cop/rails/http_status.rb
- spec/rubocop/cop/rails/http_status_spec.rb
This PR makes the `HttpStatus` Cop aware of the Rails-specific assertions  that test responses from Rails applications, such as `assert_response` and `assert_redirect_to`.
This Cop enforces a consistent method of specifying HTTP status in `render`, `redirect_to`, and `head`, either symbolic or numeric. However, it did not account for `assert_response` and `assert_redirect_to` used in testing, which also accepts HTTP status as a parameter in a manner consistent with those methods.
This PR ensures that the `HttpStatus` Cop can enforce a uniform way of specifying HTTP status in both application and testing code. Specifically, it addresses the previously possible inconsistency in specifying HTTP Status when using `assert_response` and `assert_redirect_to`.
Before submitting …
> Make Rails/HttpStatus aware of Rails specific response assertions

- changelog/change_inspect_change_table_for_not_null_column.md
- lib/rubocop/cop/rails/not_null_column.rb
- spec/rubocop/cop/rails/not_null_column_spec.rb
I noticed this cop was not aware of columns added inside a `change_table` block, so added support for that.
> Rails/NotNullColumn: Inspect change_table calls for offenses

- config/default.yml
- lib/rubocop/cop/rails/not_null_column.rb
Clarify that the cop is only for NOT NULL without a default, and only for existing tables. Also point users in the direction of how to add a NOT NULL column to an existing table.
> [Fix #237] Improve documentation for Rails/NotNullColumn

- spec/rubocop/cop/rails/blank_spec.rb
- spec/rubocop/cop/rails/exit_spec.rb
- spec/rubocop/cop/rails/present_spec.rb
- spec/rubocop/cop/rails/safe_navigation_spec.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
- spec/rubocop/cop/rails/where_exists_spec.rb
This PR restores skipped specs for Prism. They have already been resolved in Prism, so they can be tested.
> Restore skipped specs for Prism

- lib/rubocop/cop/rails/pick.rb
The `RuboCop::Cop::Rails::Pick` cop "Enforces the use of ‘pick` over `pluck(…).first`."
When using this cop on an existing code base, it's not possible for the cop to detect whether the relation already has a limit applied.
In these cases, following the advice will cause a subquery to be added to the resulting query.
`Model.limit(100).pluck(:a).first` is not equivalent to `Model.limit(100).pick(:a)`. The former generates a SQL query with a `LIMIT 100`. The latter generates a query with `LIMIT 1` and subquery with `LIMIT 100`.
This proposed documentation update highlights the scenario so the developer can better judge when to obey the cop.
Example: https://gitlab.com/gitlab-org/gitlab/-/issues/455116
Note: I haven't updated `docs/modules/ROOT/pages/cops_rails.adoc` as I believe this is …
> Warn about subqueries when replacing pluck with pick

- changelog/fix_safe_navigator_for_skips_model_validation.md
- lib/rubocop/cop/rails/skips_model_validations.rb
- spec/rubocop/cop/rails/skips_model_validations_spec.rb
Fixes #1278.
This PR fixes a false positive for `Rails/SkipsModelValidations` when using `insert` or `insert!` with a safe navigator.
> [Fix #1278] Fix a false positivie for Rails/SkipsModelValidations

- changelog/change_mark_rails_skips_model_validations_as_unsafe.md
- config/default.yml
- lib/rubocop/cop/rails/skips_model_validations.rb
Fixes #1286.
`Rails/SkipsModelValidations` cop is unsafe if the receiver object is not an Active Record object. So, this PR marks `SkipsModelValidations` as unsafe.
> [Fix #1286] Mark `Rails/SkipsModelValidations` as unsafe

- changelog/fix_change_column_null_in_bulk_change_table.md
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
`change_column_null` is only combinable with PostgreSQL, and is only available as `change_null` within a `change_table` block since Rails 6.1, so target to only those cases.
> [Fix #1280] Handle change_column_null for BulkChangeTable

- changelog/fix_where_range_complex_expressions.md
- lib/rubocop/cop/rails/where_range.rb
- spec/rubocop/cop/rails/where_range_spec.rb
Fixes #1281.
We can't for sure tell when we not need parentheses (without reimplementing `Style/RedundantParentheses` cop), so I excluded the most popular and obvious variants.
> [Fix #1281] Fix `WhereRange` autocorrect for complex expressions

- changelog/change_where_range_unsafe_autocorrect.md
- config/default.yml
- lib/rubocop/cop/rails/where_range.rb
> [Fix #1283] Mark `WhereRange` as unsafe autocorrect

- changelog/change_add_link_to_if_and_unless_to_link_blank.md
- lib/rubocop/cop/rails/link_to_blank.rb
- spec/rubocop/cop/rails/link_to_blank_spec.rb
Fix #1288 (but not adding link_to_unless_current) by adding respective methods to the `RESTRICT_ON_SEND` list, hoping that this is the right approach.
I sketched an approach for the specs, but it would mean executing very similar specs three times - see relevant commit for a very brief discussion: 70db8e4f498ee3f3af4e23e5022717b4fa2d28e7 . What do you think?
> [Fix #1288] Let LinkToBlank find violations in link_to_if and link_to_unless

- changelog/fix_error_for_rails_not_null_column.md
- lib/rubocop/cop/rails/not_null_column.rb
- spec/rubocop/cop/rails/not_null_column_spec.rb
> Fix an error for `Rails/NotNullColumn` when the block for `change_table` is empty

- changelog/change_1295_covers_validates_comparison_of_in.md
- lib/rubocop/cop/rails/validation.rb
- spec/rubocop/cop/rails/validation_spec.rb
Fixes #1295 
[Rails/Validation](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsvalidation) covers replacing old-style attribute validation macros with newer, more flexible `validates` calls. However currently, it doesn't check for `validates_comparison_of`. This covers validates_comparison_of, and adds a new test case for procs as arguments.
> [Fix #1295] Covers validates_comparison_of in Rails/Validations

- changelog/fix_make_pluralization_grammar_aware_of_bytes.md
- lib/rubocop/cop/rails/pluralization_grammar.rb
- spec/rubocop/cop/rails/pluralization_grammar_spec.rb
These methods are also singular/pluralized, see https://api.rubyonrails.org/classes/Numeric.html
```rb
1.byte
2.bytes
1.bytes
2.byte
```
> Make `Rails/PluralizationGrammar` aware of byte methods

- changelog/new_support_rails_7_syntax_for_rails_enum_uniqueness_cop.md
- lib/rubocop/cop/rails/enum_uniqueness.rb
- spec/rubocop/cop/rails/enum_uniqueness_spec.rb
Rails 7.0 introduced a new enum syntax ( https://github.com/rails/rails/pull/41328 ):
```ruby
enum :status, [:active, :archived]
```
Rails/EnumUniqueness cop does't support the new syntax yet. This PR adds the new syntax support.
> Support Rails 7 enum syntax for Rails/EnumUniqueness cop

- lib/rubocop/cop/rails/pluck_in_where.rb
Clarifies the existing wording to be easier to understand and adds an additional paragraph about possible performance implications of this cop.
These implications have been mentioned before in https://github.com/rubocop/rubocop-rails/issues/310#issuecomment-1151687469, but weren't explicitly mentioned in the cop's documentation.
---
The linked issue mentions MySQL and I have found the same issue multiple times showing up in MySQL on Stack Overflow, but I ran into it on PostgreSQL today. The query was something along the lines of this, albeit a bit more complicated:
```rb
query = %{
(type = ? AND model_id IN (?)) OR
(type = ? AND model_id IN (?))
}
Foo.where(query, 'bar', bar_ids,
'baz', Baz.where(condition: true).pluck(:id))
```
The `pluck` in the last line was replaced with a `select`, …
> Clarify the wording of the `Rails/PluckInWhere` cop

- changelog/change_compact_blank_to_handle_select_present.md
- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
> Change `Rails/CompactBlank` to handle `select(&:present?)`

- changelog/fix_false_positive_for_rails_compact_blank.md
- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
This PR fixes false positives for `Rails/CompactBlank` when using `collection.reject!`.
`reject!(&:blank?)` is not equivalent to `compact_blank!`:
```ruby
{}.reject!(&:blank?)            # => nil
{}.reject! { |_k, v| v.blank? } # => nil
{}.compact_blank!               # => {}
```
This PR prioritizes safer behavior with plain hashes and arrays.
> Fix false positives for `Rails/CompactBlank`

- lib/rubocop/cop/rails/date.rb
Fix few typos. Use right ticks to escape code in examples.
> Use right ticks

- .github/workflows/test.yml
- changelog/fix_make_style_collection_compact_aware_of_params.md
- config/default.yml
- rubocop-rails.gemspec
Follow up https://github.com/rubocop/rubocop/pull/11909 and fixes https://github.com/rubocop/rubocop/issues/11908.
> Allow `params` receiver by default for `Style/CollectionMethods`

- changelog/fix_false_negatives_for_action_controller_flash_before_render.md
- lib/rubocop/cop/rails/action_controller_flash_before_render.rb
- spec/rubocop/cop/rails/action_controller_flash_before_render_spec.rb
This PR fixes two false negatives in `Rails/ActionControllerFlashBeforeRender`. One pertains to implicit render with branch blocks, and the other to rescue blocks.
The cop should register an offense when `flash` is used within an if block or rescue block, and the action ends without an explicit call to render or redirect_to, resulting in an implicit render.
```
class HomeController < ActionController::Base
def create
flash[:alert] = "msg" if condition
^^^^^ Use `flash.now` before `render`.
end
end
```
```
class HomeController < ActionController::Base
def create
begin
do_something
flash[:alert] = "msg in begin"
^^^^^ Use `flash.now` before `render`.
rescue
flash[:alert] = "msg in rescue"
^^^^^ Use `flash.now` before `render`.
end
end
end
```
No offenses are registered.
The cop should …
> Fix false negatives for Rails/ActionControllerFlashBeforeRender when using implicit render or rescue block

- docs/modules/ROOT/pages/cops_rails.adoc
Correct a typo in the `Rails/WhereEquals` documentation.
> Correct typo in Rails/WhereEquals documentation

- changelog/fix_false_positive_for_rails_redundant_presence_validation_on_belongs_to.md
- lib/rubocop/cop/rails/redundant_presence_validation_on_belongs_to.rb
- spec/rubocop/cop/rails/redundant_presence_validation_on_belongs_to_spec.rb
If presence is the only validation option and other non-validation options are present, removing it will cause rails to error.
> [Fix #1319] Fix false positive for `RedundantPresenceValidationOnBelongsTo`

- changelog/fix_where_equals_error.md
- lib/rubocop/cop/rails/where_equals.rb
- spec/rubocop/cop/rails/where_equals_spec.rb
> Fix an error for `Style/WhereEquals` when the second argument is not yet typed

- changelog/fix_error_rails_render_plain_text_constant.md
- lib/rubocop/cop/rails/render_plain_text.rb
- spec/rubocop/cop/rails/render_plain_text_spec.rb
Or other nodes that don't respond to `value` like local variables
> Fix an error for `Rails/RenderPlainText` when the content type is passed as a constant

- changelog/fix_error_rails_where_not_no_second_argument.md
- lib/rubocop/cop/rails/where_not.rb
- spec/rubocop/cop/rails/where_not_spec.rb
This is basically #401 again, and a bit of #1321
> Fix an error for `Rails/WhereNot` without second argument

- changelog/fix_make_rails_where_equals_aware_of_not.md
- config/default.yml
- lib/rubocop/cop/rails/where_equals.rb
- spec/rubocop/cop/rails/where_equals_spec.rb
Fix #1199
This copies a bit of logic from `WhereRange` but they need slighly different handling and it doesn't seem worth to extract yet.
> [Fix #1199] Make `Rails/WhereEquals` aware of `where.not(...)`

- changelog/change_rails_root_pathname_methods_to_detect_offenses_on_dir_index.md
- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
Added support for `Dir.[]`.
One of the most commonly used example of this pattern is the following code, generated by rspec-rails gem:
```ruby
Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
Rails.root.glob('spec/support/**/*.rb').each { |f| require f }
```
> Change `Rails/RootPathnameMethods` to detect offenses on `Dir.[]`

- spec/project_spec.rb
Also update cop filtering for https://github.com/rubocop/rubocop/pull/13123
> Don't use deprecated `Cop.registry` in specs

- changelog/fix_error_rails_bulk_change_table.md
- lib/rubocop/cop/rails/bulk_change_table.rb
- spec/rubocop/cop/rails/bulk_change_table_spec.rb
The error only occurs when the block is empty, the test for no block at all is just to make sure.
> Fix an error for `Rails/BulkChangeTable` when the block for `change_table` is empty

- changelog/new_support_rails_7_syntax_for_rails_enum_hash_cop.md
- lib/rubocop/cop/rails/enum_hash.rb
- spec/rubocop/cop/rails/enum_hash_spec.rb
Rails 7.0 introduced a new enum syntax ( https://github.com/rails/rails/pull/41328 ):
```ruby
enum :status, [:active, :archived]
enum :status, { active: 0, archived: 1 }
```
[Rails/EnumHash](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsenumhash) cop does't support the new syntax yet. This PR adds the new syntax support.
> Support Rails 7 syntax for Rails/EnumHash cop

- changelog/fix_error_rails_validation.md
- lib/rubocop/cop/rails/validation.rb
- spec/rubocop/cop/rails/validation_spec.rb
In the first commit, I port the specs over to using `expect_offense` and similar. It's shorter and easier to understand.
> Fix an error for `Rails/Validation` when passing no arguments

- lib/rubocop/cop/rails/action_order.rb
- lib/rubocop/cop/rails/active_record_callbacks_order.rb
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
The minimum required version right now is >= 1.52
> Remove RuboCop < 1.52 compatibility code

- .rubocop.yml
- lib/rubocop/cop/rails/present.rb
- lib/rubocop/cop/rails/skips_model_validations.rb
This works fine right now.
I did a bit of spelunking for `NilOrEmpty` in `Rails/Present` and I believe it is a copy-paste error. Added together with `Rails/Blank` in https://github.com/rubocop/rubocop/pull/4133/ which does contain this config value. There are no tests or docs for this config value.
> Enable `InternalAffairs/UndefinedConfig`

- changelog/fix_false_positive_database_qualified.md
- lib/rubocop/cop/rails/where_equals.rb
- lib/rubocop/cop/rails/where_not.rb
- lib/rubocop/cop/rails/where_range.rb
- spec/rubocop/cop/rails/where_equals_spec.rb
- spec/rubocop/cop/rails/where_not_spec.rb
- spec/rubocop/cop/rails/where_range_spec.rb
And `Rails/WhereNot`/`Rails/WhereRange` as well. Fixes #1340
I'd like to extract some of this logic to a module sometime since it is looking rather similar.
The original issue mentions Redshift, and I know that MSSQL allows cross-database queries as well
> [Fix #1340] Fix a false positive for `Rails/WhereEquals` when qualifying the database name

- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
Fix #1345
The current message is confusing/nonsensical for `Dir[]`.  Let's display the correct code instead to show what needs to be done.
I also added the Dir offenses to the example section.
> [Fix #1345] Improve offense message for `Rails/RootPathnameMethods`

- changelog/fix_false_negatives_enum_syntax.md
- lib/rubocop/cop/rails/enum_syntax.rb
- spec/rubocop/cop/rails/enum_syntax_spec.rb
Fix #1343. I don't believe there is any issue with just looking at all value types. It just translates `foo: bar` into `:foo, bar`.
> [Fix #1343] False negatives for `Rails/EnumSyntax`

- changelog/change_enum_syntax_to_autoccorect_underscored_options.md
- lib/rubocop/cop/rails/enum_syntax.rb
- spec/rubocop/cop/rails/enum_syntax_spec.rb
Currently, the cop only suggests that the outdated syntax for options is used, but it does not autocorrect.
> Change `Rails/EnumSyntax` to autocorrect underscored options

- changelog/change_application_record_to_ignore_migrations.md
- config/default.yml
- lib/rubocop/cop/rails/application_record.rb
> Change `Rails/ApplicationRecord` to ignore migrations

- spec/rubocop/cop/rails/compact_blank_spec.rb
This PR adds missing tests for `Rails/CompactBlank` when the receiver is a hash.
https://github.com/rubocop/rubocop-rails/blob/master/lib/rubocop/cop/rails/compact_blank.rb#L25
~~* [] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~~
~~* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~~
~~* [ ] If this is a new cop, consider making a corresponding update to the [Rails Style …
> Add missing tests for `Rails/CompactBlank` when receiver is a hash

- changelog/change_support_filter_in_rails_compact_blank.md
- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
This PR modifies `Rails/CompactBlank` to support `filter`.
Since `filter` is an alias for `select` in both Array and Hash, I think it can be handled in the same way as `select`. 
- https://docs.ruby-lang.org/en/3.3/Array.html#method-i-filter
- https://docs.ruby-lang.org/en/3.3/Hash.html#method-i-filter
* ~~[ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~~
* ~~[ ] If this is a new cop, consider making a corresponding update to the [Rails Style Guide](https://github.com/rubocop/rails-style-guide).~~
> Support `filter` in `Rails/CompactBlank`

- lib/rubocop/cop/rails/compact_blank.rb
- spec/rubocop/cop/rails/compact_blank_spec.rb
This PR fixes `Rails/CompactBlank` to avoid reporting offense for `filter` in Ruby versions below 2.6.
This change is related to https://github.com/rubocop/rubocop-rails/pull/1359. Apologies for the confusion earlier, as I initially mixed up the runtime version with the analysis version when considering Rubocop's supported versions.
`Rails/CompactBlank` applies to [Rails 6.1 and above, where the required Ruby version is 2.5](https://rubygems.org/gems/rails/versions/6.1.0). However, since `filter` method was introduced in Ruby 2.6, using `filter` in environments running Ruby 2.5 may result in false positives.
Additionally, since https://github.com/rubocop/rubocop-rails/pull/1359 is still unreleased, I am unsure whether this change should be added to the changelog. I would appreciate any …
> Fix `Rails/CompactBlank` to avoid reporting offense for `filter` in Ruby versions below 2.6

- changelog/fix_revert_flash_before_render.md
- lib/rubocop/cop/rails/action_controller_flash_before_render.rb
- spec/rubocop/cop/rails/action_controller_flash_before_render_spec.rb
Relates to #1269.
This cop would need to do control flow analysis which it just doesn't do. RuboCop also has no mechanism for that.
So just reverting this for now to fix the newly introduces false positives. No "Fix" in the commit since the original problem from the issue still occurs.
* [x ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
> Revert #1311 - false negatives for `Rails/ActionControllerFlashBeforeRender`

- changelog/fix_false_positives_for_rails_enum_syntax.md
- lib/rubocop/cop/rails/enum_syntax.rb
- spec/rubocop/cop/rails/enum_syntax_spec.rb
Fixes #1362.
This PR fixes false positives for `Rails/EnumSyntax` when using Ruby 2.7.
The warning shown in https://github.com/rubocop/rubocop-rails/issues/1238 appears starting from Rails 7.2 (Requires Ruby 3.1+). On the other hand, if users use Ruby 2.7, the warning reported in https://github.com/rubocop/rubocop-rails/issues/1362 will be displayed.
Therefore, it would be appropriate to enable this cop only when analyzing Ruby 3.0+.
Nothing will happen when using Ruby 2.7 with Rails 7.0 or Rails 7.1, but the warning in https://github.com/rubocop/rubocop-rails/issues/1238 will not be displayed either. Meanwhile, in Rails 7.2, which requires Ruby 3.1+, Ruby 2.7 cannot be used, so there is no issue.
[1]: …
> [Fix #1362] Fix false positives for `Rails/EnumSyntax`

- changelog/fix_wrong_autocorrect_for_rails_file_path.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
`File.join` actually accepts nested arrays and will unflatten them as necessary.
Don't bother implementing autocorrect for these cases, seems complicated and not worth the effort.
The current correction for these testcases look like this:
```rb
Rails.root.join().to_s
```
> Fix wrong autocorrect for `Rails/FilePath` when passing an array to `File.join`

- spec/rubocop/cop/rails/save_bang_spec.rb
I found test cases without `*` and `**` arguments  in `Rails/SaveBang` and fixed them.
> Fix test cases for `*` and `**` arguments in `Rails/SaveBang`

- changelog/change_disable_transaction_exit_rails_7.2.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
- spec/support/shared_contexts.rb
Fix #727
On Rails 7.2, the behavior is exactly like it was in earlier Rails. On Rails 7.1, it is controlled by `active_record.commit_transaction_on_non_local_return`.
https://github.com/rails/rails/commit/eccc6061f4f3abdfdeb9a363987a898418d9498f
https://github.com/rails/rails/pull/48600
> [Fix #727] Disable `Rails/TransactionExitStatement` on Rails >= 7.2

- changelog/change_env_local_to_handle_negated_conditions.md
- lib/rubocop/cop/rails/env_local.rb
- spec/rubocop/cop/rails/env_local_spec.rb
Currently, `EnvLocal` cop does not detect `!Rails.env.development? && !Rails.env.test?` as an offense (`!Rails.env.local?`).
I found a few such cases in my project.
> Change `Rails/EnvLocal` to handle negated conditions

- changelog/fix_rails_time_zone_string_to_time_with_specifier.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
As `Time.parse("2012-03-02T16:05:37Z")` is allowed, `"2012-03-02T16:05:37Z".to_time` should also be allowed.
> Fix `Rails/TimeZone` should not report offense on `String#to_time` with timezone specifier

- changelog/fix_an_error_for_rails_enum_syntax.md
- lib/rubocop/cop/rails/enum_syntax.rb
- spec/rubocop/cop/rails/enum_syntax_spec.rb
Fixes #1377
This PR fixes an error for `Rails/EnumSyntax` when positional arguments are used and options are not passed as keyword arguments.
> [Fix #1377] Fix an error for `Rails/EnumSyntax`

- changelog/fix_fix_false_negatives_for_ rails_redundant_active_record_all_method.md
- lib/rubocop/cop/rails/redundant_active_record_all_method.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
This PR fixes false negatives for `Rails/RedundantActiveRecordAllMethod` when methods in `POSSIBLE_ENUMERABLE_BLOCK_METHODS` are used in a block.
```
expect { subject }.to change { User.all.count }
^^^ Redundant `all` detected.
```
No offenses are registered.
Run `bundle ex rubocop --only Rails/RedundantActiveRecordAllMethod` on the code below:
```
expect { subject }.to change { User.all.count }
```
```
1.67.0 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 3.2, running on ruby 3.2.0) [x86_64-darwin21]
- rubocop-rails 2.27.0
```
> Fix false negatives for `Rails/RedundantActiveRecordAllMethod` when using `POSSIBLE_ENUMERABLE_BLOCK_METHODS` in a block

- changelog/change_modify_rails_pluck_to_ignore_map_collect.md
- lib/rubocop/cop/rails/pluck.rb
- spec/rubocop/cop/rails/pluck_spec.rb
This PR modifies the `Rails/Pluck` cop to ignore `map/collect` when used inside blocks to prevent potential N+1 queries.
When the receiver's relation is not loaded and `pluck` is used inside an iteration, it can result in N+1 queries. This happens because ` pluck ` executes a database query on every iteration when the relation is not loaded.
```ruby
users = User.all
5.times do
users.map { |user| user[:id] } # Only one query is executed
end
```
```ruby
users = User.all
5.times do
users.pluck(:id) # A query is executed on every iteration
end
```
```ruby
users = User.all
users.load
5.times do
users.pluck(:id) # Since the records are loaded, only one query is executed
end
```
As shown above, replacing `map/collect` with `pluck` in such cases can degrade performance due to the N+1 queries. To …
> Modify `Rails/Pluck` to ignore `map/collect` when used inside blocks to prevent potential N+1 queries

- changelog/fix_fix_an_incorrect_autocorrect_for.md
- lib/rubocop/cop/rails/select_map.rb
- spec/rubocop/cop/rails/select_map_spec.rb
This PR fixes an incorrect autocorrect for `Rails/SelectMap` when `select` has no receiver and method chains are used between `select` and `map`.
For example: `select(:column_name).where(conditions).map(&:column_name)`
```
where(conditions).pluck(:column_name)
```
```ruby
.where(conditions)pluck(:column_name)
```
Run `bundle ex rubocop -A --only Rails/SelectMap` on the code below:
```
select(:column_name).where(conditions).map(&:column_name)
```
```
1.67.0 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 3.2, running on ruby 3.2.0) [x86_64-darwin21]
- rubocop-rails 2.27.0
```
> Fix an incorrect autocorrect for `Rails/SelectMap` when `select` has no receiver and method chains are used

- changelog/fix_rails_file_path_cop_error_with_rescued_rails_root.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
```console
echo "\"#{Rails.root rescue '.'}/config\"" | rubocop --stdin bug.rb --only Rails/FilePath -d
An error occurred while Rails/FilePath cop was inspecting bug.rb:1:0.
undefined method `method?' for an instance of RuboCop::AST::RescueNode
lib/rubocop/cop/rails/file_path.rb:156:in `autocorrect_slash_after_rails_root_in_dstr'
lib/rubocop/cop/rails/file_path.rb:81:in `block in check_for_slash_after_rails_root_in_dstr'
```
> Fix `Rails/FilePath` cop error with rescued `Rails.root`

- changelog/fix_merge_pull_request_1392_from.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
```console
echo 'join(Rails.root, path)' | rubocop --only Rails/FilePath  --stdin bug.rb -d
n error occurred while Rails/FilePath cop was inspecting bug.rb:1:0.
undefined method `each_node' for nil
lib/rubocop/cop/rails/file_path.rb:54:in `rails_root_nodes?'
lib/rubocop/cop/rails/file_path.rb:60:in `rails_root_join_nodes?'
lib/rubocop/cop/rails/file_path.rb:108:in `check_for_rails_root_join_with_string_arguments'
lib/rubocop/cop/rails/file_path.rb:70:in `on_send'
```
> Fix `Rails/FilePath` cop error on `join` method with implicit receiver

- README.md
- changelog/new_intro_migrated_schema_version.md
- config/default.yml
- docs/modules/ROOT/pages/usage.adoc
- lib/rubocop/cop/mixin/migrations_helper.rb
- lib/rubocop/cop/rails/add_column_index.rb
- lib/rubocop/cop/rails/bulk_change_table.rb
- lib/rubocop/cop/rails/dangerous_column_names.rb
- lib/rubocop/cop/rails/migration_class_name.rb
- lib/rubocop/cop/rails/not_null_column.rb
- lib/rubocop/cop/rails/reversible_migration.rb
- lib/rubocop/cop/rails/reversible_migration_method_definition.rb
- lib/rubocop/cop/rails/schema_comment.rb
- lib/rubocop/cop/rails/three_state_boolean_column.rb
- spec/rubocop/cop/rails/add_column_index_spec.rb
- spec/rubocop/cop/rails/dangerous_column_names_spec.rb
- spec/rubocop/cop/rails/migration_class_name_spec.rb
- spec/rubocop/cop/rails/not_null_column_spec.rb
- spec/rubocop/cop/rails/reversible_migration_method_definition_spec.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
- spec/rubocop/cop/rails/schema_comment_spec.rb
- spec/rubocop/cop/rails/three_state_boolean_column_spec.rb
This PR introduces `AllCops: MigratedSchemaVersion` config.
By specifying `MigratedSchemaVersion` option, migration files that have been migrated can be ignored. When `MigratedSchemaVersion: '20241231000000'` is set. Migration files lower than or equal to '20250101000000' will be ignored. For example, this is the timestamp in db/migrate/20250101000000_create_articles.rb.
```yaml
AllCops
MigratedSchemaVersion: 20250101000000
```
This prevents inspecting schema settings for already applied migration files and avoids having different database schemas depending on when `bin/rails db:migrate` is executed.
> Introduce `AllCops: MigratedSchemaVersion` config

- changelog/fix_fix_an_incorrect_autocorrect_for_rails_timezone_when_time_new_has_a_string_augument.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
This PR fixes incorrect autocorrect for Rails/TimeZone when `Time.new` has a string argument.
```ruby
Time.new("2024-12-21 12:00:00")
Time.zone.parse("2024-12-21 12:00:00")
```
```ruby
Time.new("2024-12-21 12:00:00")
Time.zone.local("2024-12-21 12:00:00")
```
Autocorrected code doesn't work.
```ruby
irb(main):002> Time.zone.local("2024-12-21 12:00:00")
(irb):2:in `<main>': invalid value for Integer(): "2024-12-21 12:00:00" (ArgumentError)
time = Time.utc(*args)
^^^^^
```
Run `bundle ex rubocop -a --only Rails/TimeZone` on the code below:
```ruby
Time.new("2024-12-21 12:00:00")
```
``` console
❯ rubocop -v
1.68.0
```
Before submitting the PR make sure the following are …
> Fix an incorrect autocorrect for `Rails/TimeZone` when Time.new has a string argument

- changelog/fix_index_by_index_with_numblock.md
- lib/rubocop/cop/mixin/index_method.rb
- lib/rubocop/cop/rails/index_by.rb
- lib/rubocop/cop/rails/index_with.rb
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
Addresses one item from https://github.com/rubocop/rubocop-rails/issues/1315.
> Update `Rails/IndexBy` and `Rails/IndexWith` to support numbered block parameters

- changelog/fix_index_with_hash_literal_without_braces.md
- lib/rubocop/cop/mixin/index_method.rb
- spec/rubocop/cop/rails/index_with_spec.rb
Addresses another item from https://github.com/rubocop/rubocop-rails/issues/1315.
This is the same fix that was applied to `Style/HashTransformValues` in https://github.com/rubocop/rubocop/pull/9941.
> Fix autocorrection for `Rails/IndexWith` when the value is a hash literal without braces

- changelog/fix_index_by_index_with_enclosing_block.md
- lib/rubocop/cop/mixin/index_method.rb
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
Related to https://github.com/rubocop/rubocop-rails/issues/1315.
While working on https://github.com/rubocop/rubocop-rails/pull/1405, I noticed another fix applied to `Style/HashTransform{Keys,Values}` that also affects `Rails/Index{By,With}` (https://github.com/rubocop/rubocop/pull/10171).
> Fix autocorrection for `Rails/IndexBy` and `Rails/IndexWith` when `map { ... }.to_h` is enclosed in another block

- changelog/fix_error_reversible_migration.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
As it happens when you type it
> Fix an error for `Rails/ReversibleMigration` when calling `drop_table` without any arguments

- changelog/change_make_registered_cops_aware_of_all_cops_migrated_schema_version.md
- lib/rubocop-rails.rb
- lib/rubocop/cop/mixin/migrations_helper.rb
- lib/rubocop/cop/rails/add_column_index.rb
- lib/rubocop/cop/rails/bulk_change_table.rb
- lib/rubocop/cop/rails/dangerous_column_names.rb
- lib/rubocop/cop/rails/migration_class_name.rb
- lib/rubocop/cop/rails/not_null_column.rb
- lib/rubocop/cop/rails/reversible_migration.rb
- lib/rubocop/cop/rails/reversible_migration_method_definition.rb
- lib/rubocop/cop/rails/schema_comment.rb
- lib/rubocop/cop/rails/three_state_boolean_column.rb
- lib/rubocop/rails/migration_file_skippable.rb
- spec/rubocop/cop/rails/presence_spec.rb
When implementing #1383, the detection of `AllCops: MigratedSchemaVersion` was initially considered only for cops related to migrations.
However, feedback received later, such as in #1410, indicated that it is also expected to apply to `Style`, `Lint`, and other categories. This suggestion is reasonable, as warnings for migrated files may not be limited to database columns but could also include Ruby programming logic. Excluding `Style` and `Lint` from this consideration would not align with this feedback.
This PR modifies the behavior so that all registered cops can detect the value of `AllCops: MigratedSchemaVersion`.
Fixes #1410.
> [Fix #1410] Make registered cops aware of `AllCops: MigratedSchemaVersion`

- changelog/new_add_new_rails_strong_parameters_expect_cop.md
- config/default.yml
- lib/rubocop/cop/rails/strong_parameters_expect.rb
- lib/rubocop/cop/rails_cops.rb
- spec/rubocop/cop/rails/strong_parameters_expect_spec.rb
This PR adds new `Rails/StrongParametersExpect` cop that enforces the use of `ActionController::Parameters#expect` as a method for strong parameter handling.
As a starting point for this cop, the implementation in this PR will detect the following cases.
```ruby
params.require(:user).permit(:name, :age)
params.permit(user: [:name, :age]).require(:user)
params.expect(user: [:name, :age])
```
This cop's autocorrection is considered unsafe because there are cases where the HTTP status may change from 500 to 400 when handling invalid parameters. This change, however, reflects an intentional incompatibility introduced for valid reasons by the `expect` method, which aligns better with strong parameter conventions.
This cop does not detect the following cases for the reasons outlined below. …
> Add new `Rails/StrongParametersExpect` cop

- changelog/fix_rails_http_positional_arguments_cop_false_positivies_with_arguments_forwarding.md
- lib/rubocop/cop/rails/http_positional_arguments.rb
- spec/rubocop/cop/rails/http_positional_arguments_spec.rb
Prior to these changes, these examples would be marked as offenses:
```ruby
def perform_request(**)
get(:list, **)
end
```
```ruby
def perform_request(...)
get(:list, ...)
end
```
> Fix `Rails/HttpPositionalArguments` cop false positives with arguments forwarding

- changelog/fix_an_incorrect_autocorrect_for_rails_strong_parameters_expect.md
- lib/rubocop/cop/rails/strong_parameters_expect.rb
- spec/rubocop/cop/rails/strong_parameters_expect_spec.rb
This PR fixes an incorrect autocorrect for `Rails/StrongParametersExpect` when using a leading dot multiline call to `params.require(:user).permit(:name, :age)`.
Fixes #1417.
> [Fix #1417] Fix an incorrect autocorrect for `Rails/StrongParametersExpect`

- changelog/fix_rails_root_pathname_to_handle_type_error_caused_by_an_array.md
- lib/rubocop/cop/rails/root_pathname_methods.rb
- spec/rubocop/cop/rails/root_pathname_methods_spec.rb
Fix https://github.com/rubocop/rubocop-rails/issues/1389
> [Fix #1389] Handle `TypeError` caused by passing array literals as arguments to `File` methods in `Rails/RootPathnameMethods` cop

- changelog/fix_an_error_for_rails_strong_parameters_expect.md
- lib/rubocop/cop/rails/strong_parameters_expect.rb
- spec/rubocop/cop/rails/strong_parameters_expect_spec.rb
This PR fixes an error for `Rails/StrongParametersExpect` when using `permit` with no arguments.
Fixes #1423.
> [Fix #1423] Fix an error for `Rails/StrongParametersExpect`

- .rubocop_todo.yml
- changelog/fix_rails_file_path_to_handle_type_error_caused_by_an_array.md
- lib/rubocop/cop/rails/file_path.rb
- spec/rubocop/cop/rails/file_path_spec.rb
Fix https://github.com/rubocop/rubocop-rails/issues/1389
> [Fix #1389] Handle `TypeError` caused by passing array literals as arguments to `File` methods in `Rails/FilePath` cop

- changelog/fix_rails_duplicate_association_to_handle_alias.md
- lib/rubocop/cop/rails/duplicate_association.rb
- spec/rubocop/cop/rails/duplicate_association_spec.rb
Fix https://github.com/rubocop/rubocop-rails/issues/1356
> [Fix #1356] Enhance `Rails/DuplicateAssociation` to handle alias

- lib/rubocop/cop/rails/belongs_to.rb
- lib/rubocop/cop/rails/skips_model_validations.rb
`rubocop-ast` defines some node groups (https://github.com/rubocop/rubocop-ast/blob/85bfe84/lib/rubocop/ast/node.rb#L89-L116) that can be used in place of a union of node types.
> Use node groups in node patterns to replace unions of types

- changelog/fix_rails_delegate_to_handle_self_class_constants_instance_variables_and_class_variables.md
- lib/rubocop/cop/rails/delegate.rb
- spec/rubocop/cop/rails/delegate_spec.rb
> [Fix #912] Enhance `Rails/Delegate` by adding delegation detection for `self.class`, constants, instance variables, and class variables

- lib/rubocop/cop/rails/delegate.rb
- spec/rubocop/cop/rails/delegate_spec.rb
This PR fixes the following error for `Rails/Delegate` when delegation to a cbase namespaced constant.
```console
1) RuboCop::Cop::Rails::Delegate detects delegation to a cbase namespaced constant
Failure/Error: return node.source unless node.namespace
NoMethodError:
undefined method 'namespace' for an instance of RuboCop::AST::Node
```
Follow-up to https://github.com/rubocop/rubocop-rails/pull/1438.
There is no changelog entry since this is a bug fix for the above PR that has not been released yet.
> Fix an error for `Rails/Delegate`

- changelog/fix_an_incorrect_behavior_when_using_migrated_schema_version.md
- config/default.yml
This PR fixes an incorrect behavior when using `AllCops: MigratedSchemaVersion`.
This suppresses the following warning when `MigratedSchemaVersion` is defined on the user side:
```console
$ bundle exec rubocop
(snip)
Warning: AllCops does not support MigratedSchemaVersion parameter.
Supported parameters are:
- RubyInterpreters
- Include
- Exclude
- DefaultFormatter
- DisplayCopNames
- DisplayStyleGuide
- StyleGuideBaseURL
- DocumentationBaseURL
- DocumentationExtension
- ExtraDetails
- StyleGuideCopsOnly
- EnabledByDefault
- DisabledByDefault
- NewCops
- UseCache
- MaxFilesInCache
- CacheRootDirectory
- AllowSymlinksInCacheRootDirectory
- TargetRubyVersion
- ParserEngine
- SuggestExtensions
- ActiveSupportExtensionsEnabled
- StringLiteralsFrozenByDefault
```
The default value of `AllCops: …
> Fix an incorrect behavior when using `AllCops: MigratedSchemaVersion`

- changelog/fix_an_error_when_using_target_rails_version.md
- lib/rubocop/rails/plugin.rb
This PR fixes an incorrect behavior when using `AllCops: TargetRailsVersion`.
This suppresses the following warning when `TargetRailsVersion` is defined on the user side:
```console
$ bundle exec rubocop
(snip)
Warning: AllCops does not support TargetRailsVersion parameter.
Supported parameters are:
- RubyInterpreters
- Include
- Exclude
- DefaultFormatter
- DisplayCopNames
- DisplayStyleGuide
- StyleGuideBaseURL
- DocumentationBaseURL
- DocumentationExtension
- ExtraDetails
- StyleGuideCopsOnly
- EnabledByDefault
- DisabledByDefault
- NewCops
- UseCache
- MaxFilesInCache
- CacheRootDirectory
- AllowSymlinksInCacheRootDirectory
- TargetRubyVersion
- ParserEngine
- SuggestExtensions
- ActiveSupportExtensionsEnabled
- StringLiteralsFrozenByDefault
```
This is a dirty hack relying on a …
> [Fix #1442] Fix an incorrect behavior when using `AllCops: TargetRailsVersion`

- changelog/fix_false_positives_for_rails_delegate_when_module_function_is_used.md
- lib/rubocop/cop/rails/delegate.rb
- spec/rubocop/cop/rails/delegate_spec.rb
> [Fix #1446] Fix false positives for `Rails/Delegate` when `module_function` is used

- changelog/fix_wrong_autocorrect_rails_pluck_uniq.md
- lib/rubocop/cop/rails/uniq_before_pluck.rb
- spec/rubocop/cop/rails/uniq_before_pluck_spec.rb
This introduces a bit of whitespace when the expression spans multiple lines, but that seesm fine. Layout cops can take care of that.
> [Fix #1427] Fix an error for `Rails/UniqBeforePluck` with multi-line expression

- changelog/fix_a_false_positive_for_rails_lexically_scoped_action_filter.md
- lib/rubocop/cop/rails/lexically_scoped_action_filter.rb
- spec/rubocop/cop/rails/lexically_scoped_action_filter_spec.rb
Fixes: https://github.com/rubocop/rubocop-rails/issues/1447
Currently, `Rails/LexicallyScopedActionFilter` only looks for explicitly defined (`def`) action methods, and aliased action methods (`alias`, `alias_method`), but not action methods defined via delegation `delegate :my_action, to: ...`
This PR fixes that.
> Fix false positive for `Rails/LexicallyScopedActionFilter` when action methods are delegated

- changelog/change_accept_method_calls_on_local_variables.md
- lib/rubocop/cop/rails/reflection_class_name.rb
- spec/rubocop/cop/rails/reflection_class_name_spec.rb
Fix https://github.com/rubocop/rubocop-rails/issues/1179
> ReflectionClassName: accept method calls on local variables

- changelog/change_lint_useless_access_modifier_as_concern.md
- config/default.yml
Ref https://github.com/rubocop/rubocop/issues/7298
Allow code like this by default:
```rb
module Foo
extend ActiveSupport::Concern
private
def private_instance_bar
end
class_methods do
private
def private_class_bar
end
end
end
```
> Make `Lint/UselessAccessModifier` aware of `ActiveSupport::Concern`

- changelog/fix_save_bang_numblocks.md
- lib/rubocop/cop/rails/save_bang.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
> Make `Rails/SaveBang` aware of numblocks

- changelog/fix_transaction_exit_numblocks.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
This fixes both false positives and negatives:
* Since Rails 7.2, the first argument yielded is the transaction itself
* Don't register an offense when breaking out of a numblock loop
> Make `Rails/TransactionExitStatement` aware of numblocks

- changelog/change_no_delegate_controllers.md
- config/default.yml
- lib/rubocop/cop/rails/delegate.rb
- spec/rubocop/cop/rails/delegate_spec.rb
Followup to https://github.com/rubocop/rubocop-rails/pull/1450
> Disable `Rails/Delegate` for controllers

- changelog/fix_false_positive_table_timestamp_numblock.md
- lib/rubocop/cop/mixin/active_record_migrations_helper.rb
- spec/rubocop/cop/rails/create_table_with_timestamps_spec.rb
This should also take care of https://github.com/rubocop/rubocop-rails/issues/1413, once `itblock` is introduces
> Fix a false positive for `Rails/CreateTableWithTimestamps` with numblocks

- changelog/fix_false_positive_reversible_migration_numblock.md
- lib/rubocop/cop/rails/reversible_migration.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
There's also up_only and similar, but they don't yield any arguments
> Fix a false positive for `Rails/ReversibleMigration` in `drop_table` with numblock

- changelog/fix_false_positive_relative_date_const_numblock.md
- lib/rubocop/cop/rails/relative_date_constant.rb
- spec/rubocop/cop/rails/relative_date_constant_spec.rb
Not much of these left here I think
> Fix a false positive for `Rails/RelativeDateConstant` when assigning a lambda/proc with numblock

- changelog/fix_false_positive_uniq_before_pluck_numblock.md
- lib/rubocop/cop/rails/uniq_before_pluck.rb
- spec/rubocop/cop/rails/uniq_before_pluck_spec.rb
> Fix a false positive for `Rails/UniqBeforePluck` when using a numblock with `uniq`

- changelog/fix_avoid_warnings_about_redefined_methods.md
- lib/rubocop/cop/mixin/enforce_superclass.rb
Fix #1465
This change avoids the printing of warnings about some methods (`included`, `on_class`, and `on_send`) of the `RuboCop::Cop::EnforceSuperclass` module being redefined. These warnings are printed because, in addition to the definition of that module here in `rubocop-rails`, that module is first [also defined in `rubocop`][1]. (The module has been extracted to `rubocop-rails`, but is also left in `rubocop`, for backwards compatibility.)
[1]: https://github.com/rubocop/rubocop/blob/v1.73.2/lib/rubocop/cop/mixin/enforce_superclass.rb
This change avoids the warnings by first undefining the `RuboCop::Cop::EnforceSuperclass` module (the one from `rubocop`) before then redefining that module here in `rubocop-rails`.
Before submitting the PR make sure the following are …
> Avoid warnings about redefined methods in EnforceSuperclass module

- lib/rubocop-rails.rb
- lib/rubocop/cop/mixin/database_type_resolvable.rb
- lib/rubocop/cop/rails/reflection_class_name.rb
- lib/rubocop/cop/rails/schema_comment.rb
Rubocop already defined its own `blank?` method (🙁), so ruby always warns when it is loaded again.
There's no real point in using the extension though, so just not using it seems ideal.
> Don't load the active_support `blank` core extension

- lib/rubocop/cop/rails/output.rb
This way it's just checking for a block body instead of caring about the specific type
> Future-proof `Rails/Output` for `itblock`

- .github/workflows/test.yml
- changelog/new_support_itblock_in_rails_cops.md
- lib/rubocop/cop/mixin/index_method.rb
- lib/rubocop/cop/rails/index_by.rb
- lib/rubocop/cop/rails/index_with.rb
- lib/rubocop/cop/rails/pluck.rb
- lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb
- lib/rubocop/cop/rails/reversible_migration.rb
- rubocop-rails.gemspec
- spec/rubocop/cop/rails/create_table_with_timestamps_spec.rb
- spec/rubocop/cop/rails/index_by_spec.rb
- spec/rubocop/cop/rails/index_with_spec.rb
- spec/rubocop/cop/rails/output_spec.rb
- spec/rubocop/cop/rails/pluck_spec.rb
- spec/rubocop/cop/rails/redundant_active_record_all_method_spec.rb
- spec/rubocop/cop/rails/redundant_receiver_in_with_options_spec.rb
- spec/rubocop/cop/rails/relative_date_constant_spec.rb
- spec/rubocop/cop/rails/reversible_migration_spec.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
- spec/rubocop/cop/rails/uniq_before_pluck_spec.rb
- spec/spec_helper.rb
This PR supports `it` block parameter in `Rails` cops.
Closes #1413
> Support `it` block parameter in `Rails` cops

- lib/rubocop/cop/rails/arel_star.rb
> [Fix #1353] Fix incorrect escaping of asterisk in docs and comments

- changelog/fix_schema_comment_local_var.md
- lib/rubocop/cop/rails/schema_comment.rb
- spec/rubocop/cop/rails/schema_comment_spec.rb
Fix #1477
To do that, be more specific about what type you expect to call blank? on (strings only).
Caused by https://github.com/rubocop/rubocop-rails/pull/1467
> [Fix #1477] Fix an error for `Rails/SchemaComment` when the comment is passed as a local variable

- changelog/fix_rails_time_zone_cop_error_on_invalid_string_literal_encoding.md
- lib/rubocop/cop/rails/time_zone.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
In some cases (e.g. for testing purposes) we might to want to use invalid string literal -- in that case IMO we should not register an offense.
> Fix `Rails/TimeZone` cop error on invalid string literal encoding

- changelog/fix_index_with_nested_offenses.md
- lib/rubocop/cop/mixin/index_method.rb
- spec/rubocop/cop/rails/index_with_spec.rb
Currently, code that registers nested offenses for `Rails/IndexWith`:
```ruby
x.each_with_object({}) do |el, h|
h[el] = el.each_with_object({}) do |inner_el, inner_h|
inner_h[inner_el] = foo(inner_el)
end
end
```
will fail on autocorrection with `Parser::ClobberingError: Parser::Source::TreeRewriter detected clobbering` error.
This PR fixes autocorrection by ignoring the node after first autocorrection, so the correction is done in multiple passes.
Since this cop shares logic with `Rails/IndexBy`, technically that cop is affected as well by this change.
> Fix autocorrection error with nested offenses for `Rails/IndexWith`

- changelog/fix_bugs_in_rails_pluck_id_and_rails_pluck_in_where.md
- lib/rubocop/cop/mixin/active_record_helper.rb
- spec/rubocop/cop/rails/pluck_id_spec.rb
- spec/rubocop/cop/rails/pluck_in_where_spec.rb
I found a bug in the implementation of `#in_where?`.
In the previous implementation, it would return `true` not only when the node was included in the arguments of `where`, but also when the node was the receiver of the `where` call.
This bug causes false negatives in `Rails/PluckId`:
```console
$ echo 'Post.pluck(:id).where(id: 1)' | bundle exec rubocop --stdin example.rb --only Rails/PluckId
.
1 file inspected, no offenses detected
```
and also causes false positives in `Rails/PluckInWhere`:
```console
$ echo 'Post.pluck(:id).where(id: 1)' | bundle exec rubocop --stdin example.rb --only Rails/PluckInWhere
C
Offenses:
example.rb:1:6: C: [Correctable] Rails/PluckInWhere: Use select instead of pluck within where query method.
Post.pluck(:id).where(id: 1) …
```
> Fix bugs in `Rails/PluckId` and `Rails/PluckInWhere`

- changelog/change_exclude_controllers_and_mailers_from.md
- config/default.yml
This is a proposal to address the following issues:
- https://github.com/rubocop/rubocop/issues/8667
- https://github.com/rubocop/rubocop-rails/issues/343
Currently, `Rails/LexicallyScopedActionFilter` is enabled by default for controllers and mailers. 
https://github.com/rubocop/rubocop-rails/blob/f57c3bacb1d57da2e3c2b14fcd6c3403016df27c/config/default.yml#L670-L678
Given this, I thought it would be reasonable to disable `Lint/UselessMethodDefinition` by default for them as well.
> Exclude controllers and mailers from `Lint/UselessMethodDefinition`

- changelog/fix_false_positives_for_rails_transaction_exit_statement.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
This PR fixes false positives for `Rails/TransactionExitStatement` when `break` is used in loop in transactions.
Fixes #1495.
> [Fix #1495] Fix false positives for `Rails/TransactionExitStatement`

- changelog/fix_false_positives_for_rails_output.md
- lib/rubocop/cop/rails/output.rb
- spec/rubocop/cop/rails/output_spec.rb
This PR fixes false positives for `Rails/Output` when `p` method is a DSL.
Fixes #1486.
> [Fix #1486] Fix false positives for `Rails/Output`

- changelog/change_make_rails_enum_syntax_aware_of_lib.md
- config/default.yml
This PR makes `Rails/EnumSyntax` include the lib directory by default.
Fixes #1474.
> [Fix #1474] Make `Rails/EnumSyntax` include the lib directory by default

- changelog/fix_error_transaction_exit.md
- lib/rubocop/cop/rails/transaction_exit_statement.rb
- spec/rubocop/cop/rails/transaction_exit_statement_spec.rb
Fix #1508
In that case, it's not the rails transaction method.
> [Fix #1508] Fix an error for `Rails/TransactionExitStatement` when method is chained

- changelog/fix_an_error_for_rails_read_write_attribute_cop.md
- lib/rubocop/cop/rails/read_write_attribute.rb
- spec/rubocop/cop/rails/read_write_attribute_spec.rb
Resolves https://github.com/rubocop/rubocop-rails/issues/1488
Basically we should not assume AST literals are not frozen.
> [Fix #1488] Fix an error for `Rails/ReadWriteAttribute` cop

- changelog/fix_autocorrect_for_find_by_memo.md
- lib/rubocop/cop/rails/find_by_or_assignment_memoization.rb
- spec/rubocop/cop/rails/find_by_or_assignment_memoization_spec.rb
Followup to https://github.com/rubocop/rubocop-rails/commit/501e5d39f0815b189f0ce480b5a58855071c7bb9
This type of autocorrect can only happen if the method contains no other code. Otherwise, it would exist early if followed by other code. Docs only contained example code for it happening inside of a method in that way, but the cop actually checks for the pattern regardless of context. In such cases, the longer form of autocorrect must happen.
Ref https://github.com/rubocop/rubocop-rails/issues/1513
> Fix wrong autocorrect for `Rails/FindByOrAssignmentMemoization`

- changelog/fix_error_find_by_block.md
- lib/rubocop/cop/rails/find_by.rb
- spec/rubocop/cop/rails/find_by_spec.rb
The rails method doesn't take a block, so it should do nothing.
> Fix an error for `Rails/FindBy` when `where` takes a block

- changelog/fix_false_positives_for_rails_find_by_or_assignment_memoization.md
- lib/rubocop/cop/rails/find_by_or_assignment_memoization.rb
- spec/rubocop/cop/rails/find_by_or_assignment_memoization_spec.rb
This PR fixes false positives for `Rails/FindByOrAssignmentMemoization` when assigning a memoization instance variable at `initialize` method.
Fixes #1532.
> [Fix #1532] Fix false positives for `Rails/FindByOrAssignmentMemoization`
