lib/rubocop/cop/rails/bulk_change_table.rb

This PR imports rubocop-hq/rubocop#6160.

Fix sentence for Rails/BulkChangeTable docs

---

lib/rubocop/cop/rails/find_each.rb
spec/rubocop/cop/rails/find_each_spec.rb

This PR imports rubocop-hq/rubocop#6161.

Add scope methods to `Rails/FindEach` cop

---

Gemfile
Rakefile
manual/cops_rails.md
tasks/cops_documentation.rake

This PR adds some documentation tasks to rake command. 
```console
% bundle exec rake -T
rake build            # Build rubocop-rails-0.5.0.gem into the pkg directory
rake clean            # Remove any temporary products
rake clobber          # Remove any generated files
rake coverage         # Run RSpec with code coverage
rake install          # Build and install rubocop-rails-0.5.0.gem into system gems
rake install:local    # Build and install rubocop-rails-0.5.0.gem into system gems without network access
rake release[remote]  # Create tag v0.5.0 and build and push rubocop-rails-0.5.0.gem to rubygems.org
rake spec             # Run RSpec code examples
```
```console
% bundle exec rake -T
rake build                            # Build rubocop-rails-0.5.0.gem into the pkg directory
rake …
```

Add rake documentation tasks

---

lib/rubocop-rails.rb
lib/rubocop/rails.rb
lib/rubocop/rails/inject.rb

This PR imports inject mechanism based on RuboCop RSpec.
https://github.com/rubocop-hq/rubocop-rspec/blob/v1.32.0/lib/rubocop/rspec/inject.rb
Refer https://github.com/rubocop-hq/rubocop/issues/5976#issuecomment-433828766.

Add inject mechanism

---

mkdocs.yml
readthedocs.yml

This PR adds settings for Read the Docs.

Add readthedocs.yml

---

tasks/cops_documentation.rake

Solve the same issue as below.
https://github.com/rubocop-hq/rubocop-performance/pull/62
Therefore this PR imports the following code from RuboCop core.
https://github.com/rubocop-hq/rubocop/blob/v0.71.0/tasks/cops_documentation.rake#L234-L246
Built-in Environment Variable `CI` by default `true` on CircleCI.
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

Assert manual synchronized for CI

---

lib/rubocop/cop/rails/safe_navigation.rb
manual/cops_rails.md

This PR is a change of document format for `Rails/SafeNavigation`.

Restyle example formatting for `Rails/SafeNavigation`

---

Gemfile

This reverts commit 36d736bfc81cdac6b4190ffaf69f6691827f9522.

Revert "Workaround for broke CI with YARD 0.9.20"

---

spec/rubocop/cop/rails/application_job_spec.rb
spec/rubocop/cop/rails/application_mailer_spec.rb
spec/rubocop/cop/rails/application_record_spec.rb
spec/rubocop/cop/rails/bulk_change_table_spec.rb
spec/rubocop/cop/rails/http_positional_arguments_spec.rb
spec/rubocop/cop/rails/inverse_of_spec.rb
spec/rubocop/cop/rails/redundant_receiver_in_with_options_spec.rb
spec/support/shared_contexts.rb

This PR updates testing context for Rails versions.
With this change testing context can be specified by minor version.

Update testing context for Rails versions

---

README.md

Follow up of https://github.com/rubocop-hq/rubocop-rails/pull/201#issuecomment-587240346.
This PR adds a documentation link to README.md.

Add a documentation link to README.md

---

config/default.yml
spec/project_spec.rb

This PR imports several project specs from RuboCop core.

Add project specs for config/default.yml

---

.github/PULL_REQUEST_TEMPLATE.md

I think it's good try keep rubocop-rails aligned with the styleguide.

Add suggestion to update Rails Style Guide in PR checklist

---

lib/rubocop/cop/rails/link_to_blank.rb

Add rubocop exception for CyclomaticComplexity in LinkToBlank

---

CONTRIBUTING.md

I think Real World Rails by @eliotsykes is a very useful resource for rubocop-rails development.
Thoughts on adding this?

Add link to Real World Rails

---

CHANGELOG.md
rubocop-rails.gemspec

https://github.com/rubocop-hq/rubocop-rails/pull/267 requires https://github.com/rubocop-hq/rubocop/pull/8216.

Requrie RuboCop 0.87 or higher

---

docs/modules/ROOT/pages/cops_rails.adoc
lib/rubocop/cop/rails/unknown_env.rb

Add documentation for `Environments` config variable of Rails/UnknownEnv

---

.circleci/config.yml

Follow https://github.com/rubocop-hq/rubocop-rails/pull/328.
This PR adds `documentation-checks` to CircleCI workflows.

Add `documentation-checks` to CircleCI workflows

---

README.md

This PR shows the code for the code style badges.
Follow https://github.com/rubocop-hq/rubocop/commit/4f20367 and https://metaredux.com/posts/2020/11/03/ruby-style-guide-badges.html.

Show the code for the code style badges

---

lib/rubocop/cop/rails/link_to_blank.rb

https://app.circleci.com/pipelines/github/rubocop-hq/rubocop-rails/944/workflows/74532948-c579-4623-a2b8-a9e5907c4e46/jobs/5921

Fix spec failure due to new `Style/RedundantArgument` cop

---

changelog/change_migration_cops_multiple_databases.md
config/default.yml
lib/rubocop/cop/mixin/migrations_helper.rb
lib/rubocop/cop/rails/reversible_migration.rb
lib/rubocop/cop/rails/reversible_migration_method_definition.rb
lib/rubocop/cop/rails_cops.rb
spec/rubocop/cop/rails/reversible_migration_method_definition_spec.rb
spec/rubocop/cop/rails/reversible_migration_spec.rb

Support multiple databases for `ReversibleMigration` and `ReversibleMigrationMethodDefinition` cops

---

.github/workflows/linting.yml
.rubocop.yml
.yamllint.yml
mkdocs.yml

Follow up https://github.com/rubocop/rubocop/pull/10392.

Add `yamllint` GitHub workflow

---

changelog/fix_false_positive_for_action_controller_flash_before_render.md
lib/rubocop/cop/rails/action_controller_flash_before_render.rb
spec/rubocop/cop/rails/action_controller_flash_before_render_spec.rb

[Fix #808] Flash is accepted only if followed by redirect_to

---

config/default.yml
lib/rubocop/cop/rails/belongs_to.rb
lib/rubocop/cop/rails/bulk_change_table.rb
lib/rubocop/cop/rails/ignored_skip_action_filter_option.rb
lib/rubocop/cop/rails/inverse_of.rb
lib/rubocop/cop/rails/reversible_migration.rb
lib/rubocop/cop/rails/transaction_exit_statement.rb

Follow up: https://github.com/rubocop/rubocop/pull/11317
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

Move to Reference in config/default.yml and remove the `@see` tag

---

docs/modules/ROOT/pages/cops_rails.adoc
lib/rubocop/cop/rails/blank.rb
lib/rubocop/cop/rails/present.rb

Fix typo of inabled, should be enabled.

fix: fix inabled typo to enabled

---

lib/rubocop/cop/rails/reversible_migration.rb

Improve examples for `ReversibleMigration` cop

---

changelog/change_pluck_as_unsafe.md
config/default.yml
lib/rubocop/cop/rails/pluck.rb

Mark `Rails/Pluck` as unsafe autocorrection

---

changelog/fix_three_state_boolean_column_for_dynamic_values.md
lib/rubocop/cop/rails/three_state_boolean_column.rb
spec/rubocop/cop/rails/three_state_boolean_column_spec.rb

Fix `Rails/ThreeStateBooleanColumn` for dynamic tables/columns

---

changelog/change_support_flash_now_for.md
lib/rubocop/cop/rails/i18n_locale_texts.rb
spec/rubocop/cop/rails/i18n_locale_texts_spec.rb

Closes https://github.com/rubocop/rubocop-rails/issues/1007.

Support `flash.now` for `Rails/I18nLocaleTexts`

---

changelog/fix_save_bang_to_ignore_parenthesis.md
lib/rubocop/cop/rails/save_bang.rb
spec/rubocop/cop/rails/save_bang_spec.rb

Fix `Rails/SaveBang` to ignore parenthesis

---

changelog/fix_where_range_spaces.md
lib/rubocop/cop/rails/where_range.rb
spec/rubocop/cop/rails/where_range_spec.rb

[Fix #1282] Fix `WhereRange` to correctly handle template strings with extra spaces

---

changelog/change_where_range_unsafe_autocorrect.md
changelog/fix_change_column_null_in_bulk_change_table.md
changelog/fix_where_range_complex_expressions.md
changelog/fix_where_range_spaces.md

It's of course mostly rails here but lets be consistent

Consistently specify department in current changelog entries

---

changelog/change_ignored_skip_action_filter_option_multiple_callbacks.md
lib/rubocop/cop/rails/ignored_skip_action_filter_option.rb
spec/rubocop/cop/rails/ignored_skip_action_filter_option_spec.rb

Change `Rails/IgnoredSkipActionFilterOption` to handle multiple callbacks

---

lib/rubocop/cop/rails/pluralization_grammar.rb

I fixed the example in `Rails/PluralizationGrammar`.
~~* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~~
~~* [ ] Added tests.~~
~~* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-rails/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~~
~~* [ ] If this is a new cop, consider making a corresponding update to the [Rails Style Guide](https://github.com/rubocop/rails-style-guide).~~

Fix example in `Rails/PluralizationGrammar`

---

changelog/change_select_map_safe_navigation_handle_safe_navigation.md
lib/rubocop/cop/rails/select_map.rb
spec/rubocop/cop/rails/select_map_spec.rb

Change `Rails/SelectMap` to handle safe navigation operators

---

lib/rubocop/cop/mixin/target_rails_version.rb
tasks/cops_documentation.rake

Fix #1203
Requires https://github.com/rubocop/rubocop/pull/13251

[Fix #1203] Insert the target rails version into docs

---

.github/workflows/linting.yml
.github/workflows/spell_checking.yml
.github/workflows/test.yml

RuboCop has gotten some changes to CI that can be imported here. I made multiple commits and annotated their source PR/commit. The last commit is a grab-bag of smaller miscellaneous changes.
Not sure if this should be squashed or left as is. You decide.

CI sync with RuboCop

---

changelog/fix_rails_save_bang_to_handle_instance_variables.md
lib/rubocop/cop/rails/save_bang.rb
spec/rubocop/cop/rails/save_bang_spec.rb

[Fix #1228] Enhance `Rails/SaveBang` to properly handle instance variables
